### ISSUE TITLE
synchronization in a distributed environment: what about Symbolic links

### ISSUE THREAD

**Issue by nicolabertoldi** [ModernMT/MMT#101]
Let us assume that an engine on the master sets its models using symbolic links to other engine's models or to other not official paths. like

engines/defaults/models/phrase_tables   ->     /home/ubuntu/ModernMT/engines/b1/models/phrase_tables

This works fine with a slave running on the same machine

Let us assume I used a second slave on a different machine.
I noticed that in the synchonization phase the links are preserved,
but the actual models are not synced.

Hence, the second remote slave cannot work properly,
unless you already have the actual models in the right (linked) position.
Am I right?

Nicola

**Comment by marcotrombetti** [comment]
This is tricky and it is also common to use symbolic links due to space constrains in MMT partition.

I propose this:
We follow sym links and create a static structure in the slave.
We have to assume that the Slave has space.

**Comment by davidecaroselli** [comment]
Implemented and tested in develop branch
