### ISSUE TITLE
Tuning - Wrong reference during tuning

### ISSUE THREAD

**Issue by davidecaroselli** [ModernMT/MMT#102]
I've checked the current behavior of the tuning algorithm, and I found a bug.
The reference used during tuning is tokenized, tags are correctly stripped, but numbers are not replaced with placeholders.

@mfederico @nicolabertoldi @cattoni @marcotrombetti @cattoni

**Comment by davidecaroselli** [comment]
Tuning made with today builds have this problems (I've merged the placeholders features yesterday night).

The fix of this bug has been pushed to develop branch right now. I'm running a tuning right now on an engine trained on benchmark 1.0.
The engine has all the features developed during sprint 3.

**Comment by mfederico** [comment]
So can we then expect further performance improvements? 
M

-------
Short from my mobile phone

**Comment by davidecaroselli** [comment]
Absolutely yes!

Il sabato 5 marzo 2016, Marcello Federico <notifications@github.com> ha
scritto:

> So can we then expect further performance improvements?
> M
>
> -------
> Short from my mobile phone
>
> > On 04 mar 2016, at 6:33 PM, Davide Caroselli <notifications@github.com
