### ISSUE TITLE
mmt evaluate without context-analyzer?

### ISSUE THREAD

**Issue by cattoni** [ModernMT/MMT#103]
Is it possible to use "mmt evaluate" without using the context-analyzer?
Rephrased: is there an option in "mmt evaluate" similar to --skip-context-analysis available for "mmt tune"?

For some of the contrastive runs (e.g. without context-weights) this option is very useful otherwise I have to decouple and manage individually the two steps (translation and evaluation).

**Comment by davidecaroselli** [comment]
Currently there is not such option, but it should be very simple to
introduce it! We can work on that on Monday.

Il sabato 5 marzo 2016, Roldano <notifications@github.com> ha scritto:

**Comment by davidecaroselli** [comment]
I'm closing it because we successfully completed this task without adding this flag to the command.
