### ISSUE TITLE
"mmt stop" of a non-existent engine reports success instead of error

### ISSUE THREAD

**Issue by cattoni** [ModernMT/MMT#105]
When stopping a non-existent engine such as:
    mmt stop -e  NON_EXISTENT_LUPO_ALBERTO_ENGINE
the report is:
    Stopping MMT engine 'NON_EXISTENT_LUPO_ALBERTO_ENGINE'... OK

Should be
    ERROR Illegal State: engine not found: NON_EXISTENT_LUPO_ALBERTO_ENGINE
(same as mmt status -e NON_EXISTENT_LUPO_ALBERTO_ENGINE)

**Comment by davidecaroselli** [comment]
Solved in the develop branch
