### ISSUE TITLE
LM - Training sanity check

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#106]
Today, if the LM training crashes it may results in a usable but incomplete LM.

We should add a sanity check suring the training phase.
If the sanity check fail the training must abort with an error message.

Important but not priority, assigning to milestone 0.13

**Comment by nicolabertoldi** [comment]
I am already working on this

Any suggestion how to run tests on this?
We should create critical situations and verify whether the software is able to spot them.

Nicola

**Comment by ugermann** [comment]
Isn't the easiest way to determine crashes to check exit codes?

- use "set -e" in bash scripts to make them exit immediately if something
goes wrong
- never pipe or write to the final output file directly; pip/write into a
temporary file and rename at the end
- if a program produces several output files, write into a temporary
directory and then move the contents of that directory to the final
destination.

E.g.,

#!/bin/bash
set -e
myprogram > output.tmp && mv output.tmp output.final


On Mon, Mar 7, 2016 at 3:48 PM, Nicola Bertoldi <notifications@github.com>
wrote:

> I am already working on this
>
> Any suggestion how to run tests on this?
> We should create critical situations and verify whether the software is
> able to spot them.
>
> Nicola
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ModernMT/MMT/issues/106#issuecomment-193307445>.
>



-- 
Ulrich Germann
Senior Researcher
School of Informatics
University of Edinburgh

**Comment by davidecaroselli** [comment]
These scripts are no longer used in MMT (currently we use KenLM as base LanguageModel)
