### ISSUE TITLE
Loading Models -> Syncing Models on Slave

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#108]
I added a slave server and MMT said "Loading" instead of "Syncing". 
Rsync is running on the master, so I guess it is just a typo.

```
Starting MMT engine 'b1_sprint3'... OK
Loading models...
```

**Comment by davidecaroselli** [comment]
That step is signaling two phases actually:
* Synchronizing models from master (only performed on remote slave)
* Loading models from disk (Moses)

Right now the python process has no indication of which step the java initializer is performing, so it can only output 1 line for both. Previously the line was `Synchronizing models..` but this info confuse the user who run all processes on the same machine.
I decided than to output a more general "Loading" info that can indicate both phases. In next releases we will divide the two step into "Sync" and "Load".

**Comment by davidecaroselli** [comment]
Solved in develop branch
