### ISSUE TITLE
Benchmark 1.0 - Misalignments in Training Data

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#111]
I found possible misalignments in benchmark 1.0 while performing a human evaluation:

How should we proceed? Should we identify misaligned corpora and add a low a-priory to the context analyzer?

```
ORIGINAL: 713	en	218 Skin and subcutaneous tissue disorders
HUMAN   : 713	it	Patologie gastrointestinali Nausea ( 25,2 % ) Secchezza della bocca ( 13,8 % ) Stipsi 10,3 % )
MMT     : 713	it	patologie della cute e del tessuto sottocutaneo Patologie del sistema muscoloscheletrico e del tessuto connettivo
GT      : 713	it	218 cute e del tessuto sottocutaneo


ORIGINAL: 714	en	Common Dyspnoea , Cough
HUMAN   : 714	it	sistema nervoso
MMT     : 714	it	(00,0%)
GT      : 714	it	Comune Dispnea, tosse


ORIGINAL: 715	en	Driving and using machines
HUMAN   : 715	it	Olanzapina è un agente antipsicotico , antimaniacale e stabilizzante dell’ umore dotato di un ampio profilo farmacologico su numerosi sistemi recettoriali .
MMT     : 715	it	Guida di veicoli e utilizzo di macchinari
GT      : 715	it	Guida di veicoli e utilizzo


ORIGINAL: 716	en	Weight increase Creatinine phosphokinase increase
HUMAN   : 716	it	63 Tossicità per dosi ripetute
MMT     : 716	it	La maggior parte di essi si verificò durante i primi mesi di trattamento.
GT      : 716	it	aumento di peso aumento della creatinina fosfochinasi


ORIGINAL: 717	en	You can dial doses from 2 to 78 units in increments of 2 units .
HUMAN   : 717	it	2 D-78467 Konstanz
MMT     : 717	it	L 'aumento di peso ≥ 2% del peso corporeo al basale è stato molto comune e un aumento di peso ≥ 78% del peso corporeo al basale è stato comune.
GT      : 717	it	È possibile selezionare una dose compresa tra 2 e 78 unità con incrementi di 2 unità.
```

**Comment by marcotrombetti** [comment]
BTW, the TM is 
```
benchmark-1.0/data/train/TM_Download_10591.en
```

**Comment by nicolabertoldi** [comment]
As I already highlighted last week
These misalignments probably come from an automatic sentence-level segmentation and alignment of parallel documents.

**Comment by davidecaroselli** [comment]
I've just finished evaluation on an engine without the broken TM. The result is a **gain in BLEU of 0.37**.
So, fast recap:

Version **with** `TM_Download_10591`:
* Parallel words: 240M
* BLEU: 56.55

Version **without** `TM_Download_10591`:
* Parallel words: 97M
* BLEU: 56.92

I suggest to simply remove `TM_Download_10591` from Benchmark 1.0, do you agree @marcotrombetti  @mfederico ?

**Comment by mfederico** [comment]
yes! marcello

**Comment by marcotrombetti** [comment]
I agree to remove it and name the benchmark 1.1

If we get this TM in a controlled situation, we should expect more when we go live.

We need a way to filter them. Discussion moved to email.

**Comment by ugermann** [comment]
Wouldn't TM_Download_10591 make a good test case for TAUS's data quality
assessment, then?

Did that evaluation involve retuning? The observed BLEU difference might
just be a random effect.

On Tue, Mar 8, 2016 at 3:16 PM, Marcello Federico <notifications@github.com>
wrote:

> yes! marcello
>
> > On 08 Mar 2016, at 14:22, Davide Caroselli <notifications@github.com>
> wrote:
> >
> > I've just finished evaluation on an engine without the broken TM. The
> result is a gain in BLEU of 0.37.
> > So, fast recap:
> >
> > Version with TM_Download_10591:
> >
> > Parallel words: 240M
> > BLEU: 56.55
> > Version without TM_Download_10591:
> >
> > Parallel words: 97M
> > BLEU: 56.92
> > I suggest to simply remove TM_Download_10591 from Benchmark 1.0, do you
> agree @marcotrombetti <https://github.com/marcotrombetti> @mfederico <
> https://github.com/mfederico> ?
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/ModernMT/MMT/issues/111#issuecomment-193782996>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ModernMT/MMT/issues/111#issuecomment-193820121>.
>



-- 
Ulrich Germann
Senior Researcher
School of Informatics
University of Edinburgh

**Comment by mfederico** [comment]
We leave this issue for future investigation. This TM looks to be quite an extreme case.
