### ISSUE TITLE
mmt evaluate calculates wrong translation speed

### ISSUE THREAD

**Issue by cidermole** [ModernMT/MMT#112]
mmt evaluate output:

    Translation Speed:
      MMT                 : 107.50s per sentence
However, the runtime for ./mmt evaluate ... was much less than 2 hours with my choice of ``pop_limit=1000`` (the reported speed amounts to a runtime of at least 1.8 hours, as implied by the most optimistic interpretation ``nsents*time_per_sent/cores/(60*60) = 1.8 h``, with nsents=990 and cores=16)

From moses logs (hacked in manually), I gather that actual average translation time per sentence was about **15.9 s**, I believe this should be the output.

This was run on a system with  benchmark-1.0 data. Branched off develop 3bd37fb9c0266b9058b4fb663f034437ff8133c0 (and added inconsequential stuff [see branch sa-ranked3]).

**Comment by cidermole** [comment]
(Of course the moses time per sentence does not include startup of the decoder, once per each of the 40 domains. But actual runtime was still far better.)

**Comment by davidecaroselli** [comment]
I found the problem: the current implementation measure the time the HTTP request take to return the translation. This **is not the translation time**, in fact this is the time the translation spent in the MMT input queue plus the actual translation time.

For example, let's assume I have a system capable of only one translation at time (it's mono-thread) and that each translation takes exactly 1 second. My test set is made of only 3 sentences:

* The python script will requests the 3 sentences in parallel, measuring response time for each.
* MMT will process the first translation, and puts the other 2 in its internal queue
* After a second, MMT will output the first translation and start processing the second
* After 2 seconds, MMT will output the second translation and start processing the third
* Python will measure 1 second for the first translation, 2 seconds for the second (1s translation + 1s waiting to be served) and 3 seconds for the third (1s translation + 2s waiting to be served)

I'm going to change in a way that MMT will output also the translation time within the actual translation.
