### ISSUE TITLE
mmt start hangs if moses throws an exception at startup

### ISSUE THREAD

**Issue by cidermole** [ModernMT/MMT#114]
To reproduce:

Create an invalid moses.ini, e.g. by specifying an invalid model file path. Then run `./mmt start`. Moses will throw an exception, visible in `runtime/default/slave/logs/process.log`, but this fact never occurs to the mmt script, which waits happily for the slave to report back, which never happens.

Expected behavior:

`./mmt start` should print an error and exit if the slave has died during startup.

Actual behavior:

```
$ ./mmt start -e baseline    

Starting MMT engine 'baseline'... OK
Loading models...

<hangs indefinitely here>
```

Rationale:

* During development, it is easy to run into a situation where moses throws an exception at startup. `./mmt start` should exit instead of hanging indefinitely after moses (the MMT slave process) has crashed.
* There may be myriad reasons for moses crashing even in production (like out-of-memory, corrupted models, ...), and most of the time a crash will be immediately on startup.

**Comment by davidecaroselli** [comment]
This is the same issue of #81
