### ISSUE TITLE
LC_ALL environment variable

### ISSUE THREAD

**Issue by cettolo** [ModernMT/MMT#117]
I noted that the LC_ALL env variable must be properly set for running MMT. In fact, I got this error by running moses alone (starting MMT does not work and no useful info is provided):

> bin/moses-main -f runtime/default/slave/moses.ini 
Exception: locale::facet::_S_create_c_locale name not valid

Searching on the web it seemed that the error is related to LC_ALL; in fact, in my case it is unset:
> locale
...
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

Setting it, moses (and MMT) works:

> echo "this system" | LC_ALL=en_US.UTF-8 bin/moses-main -f runtime/default/slave/moses.ini 
tale sistema 

I suggest to add a note in the documentation, at least; better: find an automatic solution.

**Comment by mfederico** [comment]
@cettolo 
why not just forcing as default the POSIX C Locale? 
LC_ALL=“C”

Would this work?

**Comment by cettolo** [comment]
Yes, even "C" is a proper value. What I think is that it cannot be assumed that LC_ALL is set, therefore somehow its setting should be forced.

**Comment by davidecaroselli** [comment]
I'm going to add this env variable directly in the **mmt start** command. Thanks for the hint!

**Comment by davidecaroselli** [comment]
@cettolo unfortunately I could not replicate the issue on my Ubuntu instance. However I've just uploaded a possible fix in the develop branch, can you test it and close the issue if everything is working? Thanks.

**Comment by cettolo** [comment]
it works! Thank you and sorry for the very very late check.
