### ISSUE TITLE
problem with GooglePerftools package

### ISSUE THREAD

**Issue by nicolabertoldi** [ModernMT/MMT#118]
On a Redhat 7.3, I run
$> .vendor/compile.sh

moses does not compile because the GooglePerftools package is not found
The error message is:
Could NOT find GooglePerftools (missing:  GooglePerftools_LIBRARIES GooglePerftools_LIBRARIES_DEBUG GooglePerftools_INCLUDE_DIR) 
-- Could NOT find tcmalloc (missing:  GooglePerftools_LIBRARIES) 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.

The GooglePerftools package is correctly installed into a user-defined  path (say "MYGPERPATH")

As reported in "moses/cmake/FindGooglePerftools.cmake"
I set the environment variable GooglePerftools_ROOT_DIR in a shell before running the compilation, but nothing changes.
The reason seems that the variable is not properly set ny cmake. This is its actuak value:
GooglePerftools_ROOT_DIR: GooglePerftools_ROOT_DIR-NOTFOUND

It seems that the following instruction does not work as expected
find_path(GooglePerftools_ROOT_DIR
    NAMES include/google/heap-profiler.h
)

I add the HINTS parameter as follows
find_path(GooglePerftools_ROOT_DIR
    NAMES include/google/heap-profiler.h
    HINTS $ENV{GooglePerftools_ROOT_DIR}
)
and it works

Using this patch, and running sequentially

$> export GooglePerftools_ROOT_DIR=MYGPERPATH
$> ./vendor/compile.sh

everything worked well:
the package was found
-- Found GooglePerftools: /home/bertoldi/software/gperftools/versions/gperftools-2.1/lib/libtcmalloc_minimal.so  
-- Found tcmalloc: /home/bertoldi/software/gperftools/versions/gperftools-2.1/lib/libtcmalloc_minimal.so  

and moses was compiled successfully

I assigned the issue to David, because he is the former developer of the script. Feel free to re-assign to someone else.

If my (or another equivalent) patch is fine, please push it in the branch, and improve the documentation correspondingly

**Comment by davidecaroselli** [comment]
@cidermole can you have a look at this issue? Do you think it can be easy to solve?

**Comment by cidermole** [comment]
@nicolabertoldi can you check if the current develop branch (moses branch mmt-official) works?

With this change:
https://github.com/ModernMT/mosesdecoder/commit/a54ab9eb660fd655d80dbc34629d8f9df82bea64

**Comment by davidecaroselli** [comment]
@nicolabertoldi can you please verify the solution and, in case everything's working, close the issue please?
