### ISSUE TITLE
"mmt evaluate" gets stuck if issued just after "mmt start"

### ISSUE THREAD

**Issue by cattoni** [ModernMT/MMT#120]
After "mmt start", if "mmt evaluate" is issued immediately then it gets stuck during the translation step and never completes.

In order to have "mmt evaluate" complete its task successfully, it is sufficient to issue the example command

```
curl "http://localhost:8045/translate?q=world&context=computer" | python -mjson.tooll
```
just after "mmt start".

Is it possible that the first translation query to the master is in some way special (e.g. for timing issue) and it is not correctly managed by "mmt evaluate"?

**Comment by davidecaroselli** [comment]
Solved with the new Distributed Infrastructure available in the develop branch.
Tested both with small and big models, hot and cold start.
