### ISSUE TITLE
wrong preprocessing of "it" data with env variable LC_ALL=C

### ISSUE THREAD

**Issue by cattoni** [ModernMT/MMT#121]
If the env variable LC_ALL is set to "C" then the preprocessing chain does not produce UTF-8 data.
For example the preprocessed italian data are ASCII files that contain no accented vowels; for example accents are substituted with question mark characters ('?', ASCII code 0x3F).

Here some example of input and wrong preprocessed output:
* perché -> perch ? 
* dirò -> dir ?
* più -> pi ?
* E’   ->  E ? 

Setting LC_ALL is set to "en_US.UTF-8" appears to fix the problem.

**Comment by davidecaroselli** [comment]
@cattoni I should have fixed this issue, could you please test it and, if it's solved, close this issue? Thanks!

**Comment by cattoni** [comment]
@davidecaroselli I have checked the new version, it is ok now, preprocessed Italian data are UTF-8.

By the way the problem was always present in the default engine but we never realized it because the example curl invocation in README.md does not involve Italian accented wovels.
