### ISSUE TITLE
option "--lm.order" in "mmt create" does not work

### ISSUE THREAD

**Issue by cattoni** [ModernMT/MMT#122]
In order to create LMs of order 2 (i,e, lower than the default 5) I have utilized the option "--lm.order 2" in "mmt create".
But the created LMs are still of order 5.

The full issued command was:
```
./mmt create en it /home/ubuntu/Original_Corpora/benchmark-1.1/data/train -e LMQ_lm_n2 -d --no-split --lm.order 2 -s tm_cleanup preprocess lm
```

**Comment by mfederico** [comment]
no manual, no help mode? 
M

**Comment by cattoni** [comment]
Nicola pointed out that:
^ the correct option name is "--muxlm.order" and not "--lm.order"
* if the order is 2, then file scripts/mt/lm.py must be changed at line 51 to set self.prune = False: currently it is set to True so that the string “-—prune 0 0 1” is added to the lmplz, and this string in not compatible with 2-grams
* the command invocation of "lmplz" fails if order is 2

So fist the behaviour of "lmplz" must be checked to work with order=2: if yes, then the lm.py has to be updated asdescribed above. If lmplz cannot manage order=2 then lm.py must changed to forbid order=2.

**Comment by davidecaroselli** [comment]
`lm.order ` argument now changes the KenLM order even when used in conjunction with MultiplexedLM. Pruning is also added only if order > 2.
