### ISSUE TITLE
parameter "alpha" must be changed in both engine.ini and moses.ini

### ISSUE THREAD

**Issue by cattoni** [ModernMT/MMT#123]
In order to change the value of parameter (muxlm) "alpha", both definitions in engine.ini and moses.ini must be updated.
Modifying the value in engine.in only has no effect.

A single modification point (either engine.ini or moses.ini) should be realized.

**Comment by davidecaroselli** [comment]
Starting from commit https://github.com/ModernMT/MMT/commit/c6515a431477cc5b70bceaf6429bbc54c149cc8a only the useful informations are store in the `engine.ini` file. If you want to change some Moses parameter, you can now edit directly the moses ini template under `engines/<your-engine-name>/models/moses.ini`.
