### ISSUE TITLE
ISO 639-1 code for Czech: is 'cs', not 'cz'

### ISSUE THREAD

**Issue by cidermole** [ModernMT/MMT#125]
I tried fixing this in https://github.com/ModernMT/MMT/commit/d1d8e525d03163e6d3e5c221e8c06fcdb41f9ed0

But somebody should verify that it works before closing this.

**Comment by davidecaroselli** [comment]
It seems perfectly ok for me. I close this issue, thanks for the fix!

**Comment by cidermole** [comment]
LanguageAnalyzer.java:59
```
        analyzers.put("cz", org.apache.lucene.analysis.cz.CzechAnalyzer.class);
```

Any other places with hardcoded language codes?

**Comment by davidecaroselli** [comment]
It shouldn't. Thanks for the debugging!
