### ISSUE TITLE
failure when context is not provided

### ISSUE THREAD

**Issue by nicolabertoldi** [ModernMT/MMT#127]
When the engine is queried two times without context, it throws an exception, and crashes
I experience this problem with develop (commit f32417965e64b9de9fc7e48929e95bcc852abf7c)

To reproduce the error
1) create an engine with the example data
./mmt create en it examples/data/train/ 

2) start the server
./mmt start

3) query with context    is fine   all times
curl "http://localhost:8045/translate?q=world&context=computer"
{"translation":"mondo","took":1,"context":[{"id":"ibm","score":0.048597444},{"id":"europarl","score":0.007114725}]}

4) query without context    is   fine the first time
curl "http://localhost:8045/translate?q=world"
{"translation":"mondo","took":2}
curl "http://localhost:8045/translate?q=world&context=computer"
{"translation":"mondo","took":4,"context":[{"id":"ibm","score":0.048597444},{"id":"europarl","score":0.007114725}]}

5) query without context    is   fails  the second time
curl "http://localhost:8045/translate?q=world"
curl: (52) Empty reply from server

Below the error message

`2016-05-16 17:08:54,535 [Thread-19] DEBUG moses.MosesDecoder - Translating: "world"`
`terminate called after throwing an instance of 'util::Exception'`
`  what():  /home/ubuntu/ModernMT_develop/vendor/moses/moses/TargetPhrase.cpp:175 in void`  `Moses::TargetPhrase::EvaluateWithSourceContext(const Moses::InputType&, const Moses::InputPath&)`
 `threw util::Exception because 'scope.get() == __null'.`
`TargetPhrase::EvaluateWithSourceContext() must now have a ContextScope for feature weights.`

**Comment by davidecaroselli** [comment]
It seems a phrase-table related problem so I assign this issue to @cidermole 
David if my guess is wrong please, reassign this to the right person.

**Comment by cidermole** [comment]
I found (and fixed) a regression in 661ea5d05d40bc88b5eee76f608818cedf199309 yesterday; with the global session, I broke changing feature/context weights outside of sessions...
The fix needs to be merged.

**Comment by davidecaroselli** [comment]
ok, in which branch I can find the fix? Does this branch also include other changes?

**Comment by cidermole** [comment]
Why discuss if you can just push the fix to develop :)

**Comment by davidecaroselli** [comment]
;)
