### ISSUE TITLE
./mmt start too slow

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#128]
Follow up, after a discussion with @davidecaroselli 

./mmt start was normally taking 1-2 seconds.

After adding tag projection it takes form 2 minutes to 10 minutes due to the startup of fast_align required by tag projector. Since a very small fraction of users will use tag projection I suggest to remove it from the default startup and add to mmt a --enable-tag-projection 

Todo:
1) remove tag-projection from the default
2) add parameter --enable-tag-projection 
3) Update the tag-projection API to inform the user of the need to enable it by starting mmt with that param.

@luca-mastrostefano sorry for making it non-default, I am happy to reconsider if startup becomes faster.

Marco

**Comment by luca-mastrostefano** [comment]
@marcotrombetti, I agree with you regarding the slowness of the startup due to the loading of the models by Fast Align.

It should be removed from the default startup of MMT while we integrate the new version of Fast Align developed by @PersianNLPer. It will be incredibly fast.

**Comment by cattoni** [comment]
All data sets I'm using for very large model experiments do include tags, so I have to use the tag-project component. This implies long waiting times, in particular in tuning - each iteration step takes at least 10m only for re-start the system.

So I strongly support efforts on reducing fast_align start time.

**Comment by luca-mastrostefano** [comment]
Fortunately during the translation process the alignments needed for the tag projection are already computed by Moses and MMT doesn't need Fast Align to compute them.

If we do not start Fast Align by default, the translation process will be fine anyway.

**Comment by marcotrombetti** [comment]
@davidecaroselli I did review 0.13 that was going to solve the problem.

Few more things missing:
1) By default is still active. Should be off by default
2) The parameter in engine.ini show be named enable_tag_projection not enable_fastalign = true
3) update Tag Projection API documentation

**Comment by davidecaroselli** [comment]
@marcotrombetti this issue is still opened, it means it is not solved yet :)
