### ISSUE TITLE
Quotes should be translatable in French-English translation

### ISSUE THREAD

**Issue by cidermole** [ModernMT/MMT#129]
Problem: French quotes stay in the English output. This hurts our WMT15 evaluation by 0.9 BLEU points.

* `SRC` est prêt à « coopérer » avec l'Allemagne
* `OUT` willing to «cooperate» with Germany
* `REF` ready to "cooperate" with Germany

French people use different quotes than English people. I believe there should be support to change quotes, at least for this language pair.

**Comment by marcotrombetti** [comment]
Makes a lot of sense.

**Comment by ugermann** [comment]
In my opinion I it's totally legitimate to normalize such things before
calculating the BLEU score, as long as we are open and consistent about it.
Acutally, I think it even makes sense to report both numbers (without and
with normalization), to put BLEU into perspective. The same holds, by the
way, for various kinds of dashes (proper hyphen, en-dash, em-dash, and the
many dashes that people might be using from the Unicode code set).
Ultimately, such things should be abstract tokens ("opening double quote",
"closing double quote") and part of the trranslation job specification (by
the customer) on how they want them translated (with some reasonable
default). There is a script in the Moses pipeline that normalizes
punctuation and that is used for calculating BLEU scores in WMT.

- Uli

On Thu, May 19, 2016 at 8:40 PM, Marco Trombetti <notifications@github.com>
wrote:

> Makes a lot of sense.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ModernMT/MMT/issues/129#issuecomment-220429449>
>



-- 
Ulrich Germann
Senior Researcher
School of Informatics
University of Edinburgh
