### ISSUE TITLE
extras/heval improvements

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#132]
Following the discussion with @davidecaroselli 

Add:
- Add Exit Option. If choosen it will calculate score based on the x evaluations done.
- improve formatting (Not clear 0 and 1 and add instructions how to vote)
- chmod 755
- rename to human-eval

**Comment by marcotrombetti** [comment]
@davidecaroselli 

Can you confirm that an "Exit" command has been added.
I read the code and the implementation looks like the old discussions and not what has been summarized in this task.

Marco

**Comment by davidecaroselli** [comment]
@marcotrombetti

The feature you're requesting has been implemented: you can `ctrl+c` at any time the process, it will print the partial results and exit. This behavior is explained in the "Instructions" section that is printed as soon as you launch the command.
