### ISSUE TITLE
Memory leak in recent develop branch

### ISSUE THREAD

**Issue by cidermole** [ModernMT/MMT#134]
I was running repeated tune and evaluate steps in an infinite loop overnight. There seems to be a memory leak somewhere, because this morning, the machines used up all their RAM and were in limbo swapping pages to/from disk.

```
saga (141 GB RAM)
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                          
11386 dmadl     30  10  0.172t 0.117t 3.109g S  11.3 84.5   3097:18 java                             

snotra (283 GB RAM)
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                          
21104 dmadl     30  10  0.340t 0.271t 6.013g S  47.1 97.9   2261:51 java                             
```

This was a `benchmark-1.1` system that usually uses this amount of RAM at runtime (just after fresh startup and started tuning):

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                          
15802 dmadl     30  10  320096  35956   4652 S  1987  0.0  11:54.46 mert                             
 5475 dmadl     30  10 76.093g 0.036t 0.024t S   0.7 12.9  17:59.66 java                             
```

I suspect moses. ContextScope is a candidate since the runtime feature weights change, as is TranslationTask. Both have various weird shared_ptr passing constructions all over the place.

MMT revision 661ea5d05d40bc88b5eee76f608818cedf199309
mosesdecoder revision 9541c42c3e49c5a2e369e144c68786ee6e2b80c4

**Comment by cidermole** [comment]
Davide, `JNITranslator::delete_session(uint64_t id)` is never called when you do a `HTTP DELETE /sessions/2`.

**Comment by davidecaroselli** [comment]
Thanks @cidermole ! This must be a bug introduced with new distributed infrastructure rework.
I'm working on this.
