### ISSUE TITLE
how shall we train MMT with different TMX

### ISSUE THREAD

**Issue by mindaugasDEV** [ModernMT/MMT#136]
Hello,

We would like to train MMT in several domain, eg. Legal, Automotive and Medical. For that we will use corresponding TMXs, lets say European Patents, European Parliament (for legal), then Volvo, Scania, DAF (for automotive) and Medtronics, Philips Healthcare and Johnson and Johnson (for Medical). All names are given only for reference, these are not real projects.

How shall we feed the TMX files to engine so that:
- it would give priority to all Medical TMX if the new project is from a completely new client, not Medtronic (but it should NOT give priority to Automotive TMXs)
- it would give priority to Medtronic TMX if the new project is from Medtronic (not a completely new customer).

I understand that by giving context the Adaptive MT (MMT) will calculate the best match for the language models it has and will apply it before returning the translation via API call, however, if we already know that we are translating Medtronic, can we refer to the Medtronic TMX in API call, not trusting the engine to find out that by itself? You know, in new Medtronic project there can be misleading sentences, more similar to European Parliament corpus rather than Medical devices.

so, 1) how shall we organize the files

Thanks,
Mindaugas

**Comment by mindaugasDEV** [comment]
uups, the keyboard jumped

the last sentence should be 1) how shall we organize, name or TAG the training files (TMX or monolingual) so that later we could refer to them as best context for the projects line
2) how shall we invoke the right language model (the right reference TMX or Mono data) during API call to give Medtronic priority

**Comment by davidecaroselli** [comment]
Hi @mindaugasDEV 

following your example, I would put all my TMX files into one single folder, let's say:
```
data/
  - europatents.tmx
  - europarl.tmx
  - volvo.tmx
  - scania.tmx
  - daf.tmx
  - medtronics.tmx
  - philipshealth.tmx
  - jj.tmx
```

> **Note**: I choose these names, but you can change them as you like it, the only constraints are that the names must contains only alphanumeric chars plus "-" and "_".

Secondly, I would add any other data, both bilingual and monolingual, that I could find to reach 1B monolingual words and 100M bilingual words: this is a good starting point to train a translation engine.

Now to the final part of your question: if you want to skip the context analysis, you can provide directly the weights you want to the Translate API.

For example if you want to give priority to all medical domains, you can pass to the Translate API the following value to the parameter **context_array**:
```json
[{
    "id": "medtronics",
    "score": 1.0
},{
    "id": "philipshealth",
    "score": 1.0
},{
    "id": "jj",
    "score": 1.0
}]
```
If you know you're translating Medtronics documents, you can force the context again with the **context_array** parameter:
```json
[{
    "id": "medtronics",
    "score": 1.0
}]
```
You can even choose you're own domains priority changing the score value, for example if you are translating Johnson and Johnson, but you want to fallback on medical domains you can specify:
```json
[{
    "id": "jj",
    "score": 1.0
},{
    "id": "medtronics",
    "score": 0.5
},{
    "id": "philipshealth",
    "score": 0.5
}]
```

You can find more details int the [Translate API Docs](https://github.com/ModernMT/MMT/blob/master/docs/rest-api/translate.md)

To test the engine I suggest to use the [extras/translate](https://github.com/ModernMT/MMT/blob/master/extras/translate) script; launch MMT (`./mmt start`) an then use this script to translate:
```sh
echo "This is an example" | extras/translate --context-weights medtronics:1
```
To see the full list of options of the **translate** script, just type:
```sh
extras/translate -h
```

If you have any other questions please don't hesitate to ask.

Cheers
