### ISSUE TITLE
how can we apply Glossary and Product Names list during API call

### ISSUE THREAD

**Issue by mindaugasDEV** [ModernMT/MMT#137]
Hello,

I hope my early questions will not disturb you, but will contribute to early user feedback\wishlist.

In ideal scenario we would like to invoke during API the right reference files for the new Medtronic (name is used only as a reference, we dont work with Medtronic) project:
- to apply language models from Medtronic TMX and monolingual data
- to apply Medtronic dictionary (e.g. of 1000 terms)
- to apply Medtronic Product Name „Do not translate“ dictionary

Now MMT works completely automatically, and even applies context in API call depending on neighborhood sentences.

Regards,
Mindaugas

**Comment by davidecaroselli** [comment]
Hi @mindaugasDEV 

as discussed in the other issue https://github.com/ModernMT/MMT/issues/136 you can force the context of a translation to match exactly the distribution you want:
```sh
echo "This is an example" | extras/translate --context-weights medtronics:1
```
 In that case MMT will do the best to translate exactly as that given context (in the example medtronics). So if the engine recognize that some terms are kept equal from source to target, it will replicate that behavior. This is true for the specific domain dictionary as well.

To further enforce this specific feature, you can even add your dictionary/do-not-translate-words list in the training data as parallel text or TMX. For example you can create a file pair called medtronics_dict.en and medtronics_dict.fr as follows:

**medtronics_dict.en**
```
medicine
syringe
...
Medtronics Co.
Aspirin
```
**medtronics_dict.fr**
```
médicament
seringue
...
Medtronics Co.
Aspirin
```
> **Note**: the data is **case sensitive**, so you may want to add also "Medicine", "MEDICINE", "Syringe" and "SYRINGE" to these files if you think you can find these terms in your documents.

And then give an high priority to this new domain:
```sh
echo "This is an example" | extras/translate --context-weights medtronics_dict:1,medtronics:0.9
```
