### ISSUE TITLE
mmt evaluate occasionally gets stuck (in getting MateCat scores?)

### ISSUE THREAD

**Issue by cidermole** [ModernMT/MMT#141]
Occasionally, `mmt evaluate` gets stuck. The engine has translated all 1000 test sentences as evidenced by `node.log`. After tens of minutes, I lose patience and kill it. But I think it can hang for longer.

This is a bummer for running batteries of automatic tests.

I suspect the MateCat scoring: there should be a reasonable timeout on this (is 1 minute OK?)

**Comment by davidecaroselli** [comment]
yes, absolutely!

**Comment by marcotrombetti** [comment]
I also have the same problem.

I cannot reproduce it, but if I increase stack e cube pruning from 1000 to 5000 it happens very often. So I assumed it was a translation request stalled and not the Matecat API.

Anyway I totally agree in setting a timeout. But 1 minutes for all request may be too small.

@luca-mastrostefano can you suggest a good timeout?
