### ISSUE TITLE
found (and fixed) problem in MuxLM with mixed-order LMs

### ISSUE THREAD

**Issue by cattoni** [ModernMT/MMT#150]
The computation of the MuxLM score appears wrong when Multiplexer combines LMs that have different order (e.g. some LMs are 3grams and some LMs are 5grams).

Basically the reason of the problem is that given a targetPhrase the "ngramScore" values to be combined (e.g. with LinearInterpolation) may represent different info according to the lenght of targetPhrase and the order of LM:  if ngramScore is <0 it means the score has been computed during pre-fetching and it is a logProb,  otherwise (ngramScore == 0) it means the score cannot be computed during pre-fetching and will be computed at decoding time. If the values are homogenous then MuxLM is ok; but MuxLM becomes wrong if they are disomogeneous -- this happens for example when a targetPhrase has 3 words, and there are two LMs, with order 5 and 3 respectively.

Together with Nicola I have developed a fix that:
- does not change the translations when MuxLM combine homogenous LMs;
- improves the performance of MuxLM with mixed-order LMs from +0.26 to +2.0 BLEU points.
 

The fix is ready in the vendor/moses dir of the AWS machine on which I work.
@davidecaroselli or @cidermole could you please tell me the procedure to include the fix in the MMT github? Should I simply add a new branch to https://github.com/ModernMT/mosesdecoder  or something is needed also on https://github.comModernMT/MMT ?
Many thanks!

**Comment by davidecaroselli** [comment]
Hi @cattoni 

you can push your fix inside https://github.com/ModernMT/mosesdecoder in a new branch (made starting from mmt-official) and I would take care of testing the solution within MMT and integrate the fix at last.

Can you send me the mosesdecoder branch name as soon as you're ready?

Thank you!

**Comment by cattoni** [comment]
Thanks @davidecaroselli !

I've just pushed on  https://github.com/ModernMT/mosesdecoder the new branch named 
**fix_MuxLM_mixed_order**, made branching mmt-official and applying the fix.

**Comment by davidecaroselli** [comment]
@cattoni  I've tested the fix: everything worked as expected! I've merged the fix in **mosesdecoder/mmt-official** and integrated in MMT with the commit https://github.com/ModernMT/MMT/commit/c3ccaeee81554b4f97ec57ad9cd40d64d72b9e87.

Thanks for the contribution!
