### ISSUE TITLE
Engine training time

### ISSUE THREAD

**Issue by wsuphappyhour** [ModernMT/MMT#151]
Hi,

We recently trained engine and it took only ~25min to train. Engine itself works and translates OK. The time spent just surprises me. With other MT solutions which use Moses it takes +12h to train.
Bilingual data contains around 46M words and  monolingual around 78M words.
All data is around 1GB.
PC resources:
![image](https://cloud.githubusercontent.com/assets/20355306/16685880/c5d42188-4516-11e6-885f-907c0d1bbfd3.png)
Have a nice day!
Thanks.

**Comment by davidecaroselli** [comment]
Hi @wsuphappyhour 

thank you very much, it's really great to hear that all the work we've done is appreciated, it means we are working in the right direction! ;)

Cheers
