### ISSUE TITLE
MMT engine stops randomly while translating continuously.

### ISSUE THREAD

**Issue by wsuphappyhour** [ModernMT/MMT#153]
Hi,

I made up batch test file to translate 6,000+ lines, but the engine stops randomly. 
Error I get:
0curl: (7) Failed to connect to localhost port 8045 connection refused
No JSON object could be decoded

Batch file sample:

curl "http://localhost:8045/translate?q=KALEOS%20warranties" | python -mjson.tool >> MTTESToutput.txt
curl "http://localhost:8045/translate?q=We%20thank%20you%20for%20your%20purchase%20and%20we%20guarantee%20you%20will%20be%20satisfied%20with%20your%20KALEOS\u002E%20Otherwise\u002C%20the%20warranty%20we%20offer%20can%20fix%20pretty%20much%20everything\u002E%20" | python -mjson.tool >> MTTESToutput.txt

Is  there length limit for the line which is translated?

How we should tackle characters which are unsupported by MMT,  change them to Unicode before translating?

Thanks for your help.

**Comment by wsuphappyhour** [comment]
It seems this line was causing engine to stop:
As I suspect it is due line lengh? Can you confirm it?
curl "http://localhost:8045/translate?q=Greater%20dialog%20in%20research%20targeted\u003ABayer%20supports%20innovative%20ideas%20in%20crop%20protection%20Grants4Targets%20program%20aims%20to%20foster%20new%20approaches%20in%20chemical%20crop%20protection%20Financial%20and%20contentual%20support%20for%20innovative%20ideas%20in%20weed\u002C%20disease%20and%20pest%20controlMonheim\u002C%20February%2022\u002C%202016 \u0096%20Bayer%20plans%20to%20drive%20forward%20the%20scientific%20debate%20on%20new%20chemical%20solutions%20in%20crop%20protection\u002E%20Researchers%20from%20universities\u002C%20other%20scientific%20institutions%20and%20start\u002Dup%20companies%20all%20over%20the%20world%20are%20therefore%20being%20encouraged%20to%20take%20part%20in%20Bayer%20Crop%20Science\u0092s%20new%20Grants4Targets%20initiative\u002E%20The%20program%20is%20aimed%20at%20finding%20innovative%20approaches%20in%20the%20field%20of%20weed\u002C%20disease%20and%20pest%20control%20in%20crop%20plants\u002E%20Bayer%20will%20not%20only%20provide%20financial%20support%20for%20promising%20proposals%20but%20also%20accompany%20ideas%20and%20projects%20on%20a%20scientific%20basis\u002E%20During%20the%20fostering%20phase\u002C%20technologies%20from%20Bayer%20can%20also%20be%20used%20for%20further%20research%20into%20promising%20ideas%20and%20projects\u002C%20which%20may%20then%20develop%20into%20regular%20scientific%20collaborations\u002EThe%20objectives%20include%20fostering%20innovative%20ideas%20that%20could%20contribute%20to%20the%20development%20of%20selective%20and%20non\u002Dselective%20herbicides\u002C%20and%20solutions%20to%20control%20plant%20disease%20pathogens%20\u0028such%20as%20fungi\u0029%20and%20plant%20pests%20\u0028such%20as%20insects%20and%20nematodes\u0029\u002E%20The%20focus%20will%20lie%20on%20new%20molecular%20targets%20and%20mechanisms%20of%20action\u002E%20Applications%20for%20the%20program%20can%20be%20submitted%20via%20a%20website%20in%20a%20process%20that%20takes%20a%20few%20minutes\u002E%20Only%20non\u002Dconfidential%20information%20should%20be%20submitted\u003B%20the%20intellectual%20property%20will%20remain%20entirely%20in%20the%20hands%20of%20the%20inventors%20throughout%20the%20collaboration\u002E\u0093The%20challenges%20facing%20agriculture%20are%20so%20great%20that%20we%20need%20all%20of%20the%20ideas%20and%20creativity%20from%20small%20and%20big%20companies\u002C%20universities%20and%20other%20academic%20institutions%20alike\u002C\u0094%20said%20Dr\u002E%20Adrian%20Percy\u002C%20Head%20of%20Research%20and%20Development%20at%20Bayer%20Crop%20Science\u002E%20\u0093We%20want%20to%20talk%20to%20scientists%20from%20all%20over%20the%20world%20about%20their%20approaches%20and%20help%20to%20accelerate%20the%20transition%20from%20fundamental%20research%20to%20products%20that%20are%20ready%20for%20the%20market\u002E\u0094A%20similar%20program%20for%20medical%20applications%20has%20been%20in%20place%20at%20Bayer\u0092s%20Pharmaceuticals%20Division%20since%20May%202009\u002E%20Some%201\u002C100%20proposals%20have%20since%20been%20submitted%20and%20more%20than%20140%20projects%20supported\u002EVisit%20http\u003A\u002F\u002Fgrants4targets\u002Ebayer\u002Ecom\u002Fcropscience\u002F for%20all%20the%20details%20about%20the%20Bayer%20Crop%20Science%20program\u002EBayer\u003A%20Science%20For%20A%20Better%20LifeBayer%20is%20a%20global%20enterprise%20with%20core%20competencies%20in%20the%20Life%20Science%20fields%20of%20health%20care%20and%20agriculture\u002E%20Its%20products%20and%20services%20are%20designed%20to%20benefit%20people%20and%20improve%20their%20quality%20of%20life\u002E%20At%20the%20same%20time\u002C%20the%20Group%20aims%20to%20create%20value%20through%20innovation\u002C%20growth%20and%20high%20earning%20power\u002E%20Bayer%20is%20committed%20to%20the%20principles%20of%20sustainable%20development%20and%20to%20its%20social%20and%20ethical%20responsibilities%20as%20a%20corporate%20citizen\u002E%20In%20fiscal%202014\u002C%20the%20Group%20employed%20around%20119\u002C000%20people%20and%20had%20sales%20of%20EUR%2042\u002E2%20billion\u002E%20Capital%20expenditures%20amounted%20to%20EUR%202\u002E5%20billion\u002C%20R\u0026D%20expenses%20to%20EUR%203\u002E6%20billion\u002E%20These%20figures%20include%20those%20for%20the%20high\u002Dtech%20polymers%20business\u002C%20which%20was%20floated%20on%20the%20stock%20market%20as%20an%20independent%20company%20named%20Covestro%20on%20October%206\u002C%202015\u002E%20For%20more%20information\u002C%20go%20to%20www\u002Ebayer\u002Ecom\u002ENote%20to%20editors\u003AA%20print\u002Dquality%20photo%20can%20be%20downloaded%20from%20the%20internet%20at www\u002Enews\u002Ebayer\u002Ecom\u002EContact\u003AJenny%20Schröter\u002C%20Tel\u002E%20\u002B49%202173%2038\u002D3544E\u002Dmail\u003A%20jenny\u002Eschroeter\u0040bayer\u002Ecomrib%20\u00282016\u002D0023\u0029Forward\u002DLooking%20StatementsThis%20release%20may%20contain%20forward\u002Dlooking%20statements%20based%20on%20current%20assumptions%20and%20forecasts%20made%20by%20Bayer%20management\u002E%20Various%20known%20and%20unknown%20risks\u002C%20uncertainties%20and%20other%20factors%20could%20lead%20to%20material%20differences%20between%20the%20actual%20future%20results\u002C%20financial%20situation\u002C%20development%20or%20performance%20of%20the%20company%20and%20the%20estimates%20given%20here\u002E%20These%20factors%20include%20those%20discussed%20in%20Bayer\u0092s%20public%20reports%20which%20are%20available%20on%20the%20Bayer%20website%20at%20www\u002Ebayer\u002Ecom\u002E%20The%20company%20assumes%20no%20liability%20whatsoever%20to%20update%20these%20forward\u002Dlooking%20statements%20or%20to%20conform%20them%20to%20future%20events%20or%20developments\u002E" | python -mjson.tool >> SYNMTTEST.txt

Thanks

**Comment by davidecaroselli** [comment]
I confirm that the problem occurred because line length.
Thanks for the report!

**Comment by wsuphappyhour** [comment]
Thanks!
