### ISSUE TITLE
mmt evaluate: dirs MMT/ and MMT.raw/ appear the same

### ISSUE THREAD

**Issue by cattoni** [ModernMT/MMT#154]
This is a minor issue.

During 'mmt evaluate', the two directories
```
${MMT_HOME}/runtime/${engine}/tmp/evaluation/translations/MMT 
${MMT_HOME}/runtime/${engine}/tmp/evaluation/translations/MMT.raw
```
appear to have the same exact content, file by file.

Are both of them still useful?
Or are they legacy code related to tokenized/detokenized output?

By the way, the other two directories
```
${MMT_HOME}/runtime/${engine}/tmp/evaluation/translations/Google_Translate/
${MMT_HOME}/runtime/${engine}/tmp/evaluation/translations/Google_Translate.raw/
```
have different content.

**Comment by davidecaroselli** [comment]
Hi @cattoni 

in the current version these two folders are identical, but this could change in the future.
In the ".raw" folder you can find the translation that the Engine has printed as they are, without any transformation. The other folder instead contains the same translation but processed with an XML-encoding normalizer.

In fact, different engines can encode the same XML entities in different ways, the normalization ensures that the encoding is exactly the same, so the following BLEU score calculation won't be affected by encoding problems.

Right now the encoding of MMT and the encoding of the normalizer are exactly the same, but in the future the encoding of the translation engine could change: with this pipeline we will always be sure that no encoding differences will harm the comparison.
