### ISSUE TITLE
mmt train: invalid warning "WARNING: more than 12G of RAM recommended, only 11G available"

### ISSUE THREAD

**Issue by kmlx** [ModernMT/MMT#155]
MMT produced "WARNING: more than 12G of RAM recommended, only 11G available" even though machine has 64G RAM with 60G free.
```
cat /proc/meminfo
MemTotal:       62916388 kB
MemFree:         7275732 kB
Buffers:           16768 kB
Cached:         54451188 kB

free -m
             total       used       free     shared    buffers     cached
Mem:         61441      55471       5970          0         16      54233
-/+ buffers/cache:       1221      60220
Swap:            0          0          0
```

MMT should check the output of ```free -m``` or other similar tools.
More info regarding linux memory caching available here: http://www.linuxatemyram.com/

**Comment by davidecaroselli** [comment]
Thanks for the report @kmlx.
The bug, as you suggested, is that MMT is checking the Mem-free column instead of the -/+ buffers/cache column.

I'm fixing this asap.

**Comment by mfederico** [comment]
free -m is not portable under Mac OSX.

**Comment by davidecaroselli** [comment]
@mfederico you're right,

but the current version of MMT runs only on Ubuntu so, for the moment, we decided to use this platform dependent executable knowing that we have to implement a more portable way to get free memory when we're going to move to other platforms.

**Comment by mfederico** [comment]
Just for the record:
http://apple.stackexchange.com/questions/4286/is-there-a-mac-os-x-terminal-version-of-the-free-command-in-linux-systems
