### ISSUE TITLE
Question: What's the purpose of tags-projection?

### ISSUE THREAD

**Issue by wsuphappyhour** [ModernMT/MMT#157]
Hi @christianbuck,

Could you please describe what is the purpose and future implementation of tags-projection?
I can only speculate few possibilities with matecat.

Thank you!
Have a nice day

**Comment by mfederico** [comment]
Hi, the goal would be to keep tag management outside the decoder, and handle this part entirely via pre-/post-processing: 1. remove tag MT input, 2. word align input and MT output, 3. transfer tag from input to MT output.

**Comment by wsuphappyhour** [comment]
Thank you for your answer!
Have a nice day
