### ISSUE TITLE
Question: Preparering data for training, numbers and NTA elements

### ISSUE THREAD

**Issue by wsuphappyhour** [ModernMT/MMT#159]
Hi,

I have question regarding training data, some engines based on Moses have difficulty to  preserve numbers and NTA elements (i.e AR1000, AR-1000, AR1000AR etc.) in translation.
For example test in MMT:
![image](https://cloud.githubusercontent.com/assets/20355306/16952942/fd82c196-4dd3-11e6-8e04-69ad74793268.png)

You will see that numbers randomly get changed:
2.1 to 0 0
1.6 to 0 0

So should all numbers and NTA elements be deleted from training data? Or you will implement system tags for them i.e. @nta@, @num@, etc.?
How to handle them correctly?

For the future it would be nice if engine would have feature to "lock" some elements using regex expressions and they would be copy pasted to MT output same as tags are now. (Pre-processing)

The same feature could be used for post-processing, but only for MT output this way we could control if engine adds extra spaces, or we ant to apply specific locale (quotation marks, punctuation, abbreviation, etc.)

Thanks!

**Comment by davidecaroselli** [comment]
Hi @wsuphappyhour ,

MMT has already a NumericalExpression module that handle generic numerical expression. So you don't have to do anything in the training data, you should keep the numbers unchanged.
The module we implemented is able also to learn from the training set any language specific numerical encoding, for example it is able to learn and translate the decimal and thousands separators formats:

- english source: 	1**,**000**,**000**.**00 (thousands is comma, decimal is period)
- italian target: 	1**.**000**.**000**,**00 (thousands is period, decimal is comma)

However *the current implementation of this module isn't able to express at most its potential*. The result is that sometimes the code isn't able to restore the correct values and a "default" all-0s placeholder is inserted instead.

Finally, we plan to improve this component and fix any strange result in future release.

Cheers!

**Comment by wsuphappyhour** [comment]
Thanks!
