### ISSUE TITLE
How to use MMT with current translation tools like Trados or MemoQ?

### ISSUE THREAD

**Issue by memoday** [ModernMT/MMT#163]
Hi support team,

First, thanks for providing such great MT engine. It looks very promising. 

Is there any instructions on how to connect MMT with Trados or MemoQ? What about MateCat?

One more thing: I assume MMT supports Arabic as well. Please correct me if I am wrong.

thanks,
Mohamed

**Comment by davidecaroselli** [comment]
Hi @memoday 
Thanks for all the compliments, regarding the integration of MMT with Trados, MemoQ and MateCat: this is definitely a goal of the MMT project and we're going to develop plugins for the integration with the major cat tools.

At the moment we don't have any instructions to do that, the only public available interface is the REST Api.

Regarding Arabic: we have integrated an arabic tokenizer in MMT and the core components of the translation engine are language independent. So MMT is able to handle arabic text, but it is not well tested so you can probably experience some issues in the translations.

Cheers,
Davide

**Comment by memoday** [comment]
Thanks Davide for your prompt reply. I appreciate it.

It's really good to know that you are working on plugins to support major CAT tools.  It's also great to know that Arabic is supported as well :-)

What about the integration with MateCat? 

Do you have a road map?

Thanks again for your hard work and supporting the open-source community with all your amazing projects.

Kind regards,
Mohamed

**Comment by davidecaroselli** [comment]
Currently there is no public roadmap for the MateCAT integration, we are currently working in implementing an online learning system that can dynamically update its models. As soon as we'll have a product that is stable enough, we're going to develop the CAT tools plugin.

Thanks for your support Mohamed!
Regards,
Davide

**Comment by memoday** [comment]
Thanks Davide for the update. Wish you best of luck! 
Thanks,
Mohamed

**Comment by JongleurX** [comment]
Hi there,

I'd love to see a memoQ plug-in available.

Some documentation is available at https://www.memoq.com/en/memoq-extensions/machine-translation-extension-point, but the manual seems a bit out of date -- memoQ now supports the ability to have post-edits sent back to the engine for training, but how do do this is not documented quite yet.

I'm sure the Kilgray team would like to see support for promising new engines. I am reaching out to their support team to see if the documentation can be updated. Kilgray can even provide a sample application that can be adapted for a specific engine.

**Comment by mehow206** [comment]
Hi support team,

Than you for great MT engine.
I've built on it my first neural engine, and would like to use it with memoQ.
Do you have any plans to develop memoq plugin soon?

Regards,
Michal
