### ISSUE TITLE
Manage rsync process from java

### ISSUE THREAD

**Issue by cidermole** [ModernMT/MMT#169]
When java exits, rsync process should be killed as well.

You probably want to run rsync with `--no-detach` (do not detach from the parent) so it remains a child process.

Probably needs an exit handler from Java.

**Comment by davidecaroselli** [comment]
The `rsync` process is no more run by MMT.
Current version of MMT does not support  model-syncing anymore due the more complex model structure for the incremental learning feature.
I'm closing this issue, but we plan to put back this functionality in a future release that probably won't use rsync directly.
