### ISSUE TITLE
training many domains: failure of CA step (too many open files)

### ISSUE THREAD

**Issue by cattoni** [ModernMT/MMT#171]
Training a system with 6090 domains (= 6090 bilingual corpora) failed during the step
   (4 of 7) Context Analyzer training
as follows

> Command 'java -cp /home/ubuntu/ModernMT/build/mmt-0.13.jar -Dmmt.home=/home/ubuntu/ModernMT -Djava.library.path=/home/ubuntu/ModernMT/build/lib eu.modernmt.cli.ContextAnalyzerMain -l en -i /home/ubuntu/ModernMT/engines/st2_bil/models/context -c /home/ubuntu/ModernMT/runtime/st2_bil/tmp/training/clean_tms' failed with exit code 1

The log reports a problems related to the numerb of files (too many):

> Exception in thread "Thread-1" java.lang.IllegalStateException: Bucket not open
>         at eu.modernmt.context.lucene.storage.CorpusBucket.close(CorpusBucket.java:125)
>         at org.apache.commons.io.IOUtils.closeQuietly(IOUtils.java:303)
>         at java.util.HashMap$Values.forEach(HashMap.java:972)
>         at eu.modernmt.context.lucene.storage.CorporaIndex.close(CorporaIndex.java:136)
>         at org.apache.commons.io.IOUtils.closeQuietly(IOUtils.java:303)
>         at eu.modernmt.context.lucene.storage.CorporaStorage$BackgroundTask.run(CorporaStorage.java:288)
> Exception in thread "main" eu.modernmt.context.ContextAnalyzerException: Unable to add domain 4077
>         at eu.modernmt.context.lucene.LuceneAnalyzer.add(LuceneAnalyzer.java:56)
>         at eu.modernmt.cli.ContextAnalyzerMain.main(ContextAnalyzerMain.java:72)
> Caused by: java.io.FileNotFoundException: /home/ubuntu/ModernMT/engines/st2_bil/models/context/storage/_4077 (Too many open files)

The system limit is 1024, that is the command

```
$> ulimit -n
1024
```

Does Lucene open all the files simoultaneously? This would explain the the error.
In this case is there any way to constrain Lucene to use less files simoultaneously?
Or do you envisage alternative solutions?
We need to manage thousand of domains ...

**Comment by davidecaroselli** [comment]
Hi @cattoni 

for sure we have to add the option to limit the amount of open files in MMT. BTW in production environment, for performance reason, is a good idea to have that limit increased and let the program to handle more open files at the same time.

For your testing purpose I'd suggest to change that limit to a high value so not to have annoying error messages anymore.

Davide

**Comment by cattoni** [comment]
Thanks @davidecaroselli 

I've set in  /etc/security/limits.conf
```
* soft nofile 16384
* hard nofile 16384
```
and the training completed successfully

**Comment by davidecaroselli** [comment]
👍

**Comment by marcotrombetti** [comment]
@davidecaroselli please add a note to the INSTALL documentation

**Comment by davidecaroselli** [comment]
@marcotrombetti done!
https://github.com/ModernMT/MMT/blob/master/INSTALL.md#max-open-files-limit

**Comment by marcotrombetti** [comment]
@davidecaroselli @cattoni I also updated the documentation for Docker. 

Closing. Please re-open if I am missing something.
