### ISSUE TITLE
API "translate" returns domain numbers instead of names

### ISSUE THREAD

**Issue by cattoni** [ModernMT/MMT#172]
The translate API now returns domain numbers, it should returns domain names.

For example the invocation reported in the README.md

`curl "http://localhost:8045/translate?q=world&context=computer" | python -mjson.tool`

returns
```

{
    "data": {
        "context": [
            {
                "domain": {
                    "id": 1
                },
                "score": 0.048597444
            },
            {
                "domain": {
                    "id": 3
                },
                "score": 0.007114725
            }
        ],
        "decodingTime": 10,
        "translation": "mondo"
    },
    "status": 200
}
```

where domain with "id":1 should be "ibm" and "id":3 should be "europarl".

BY the way @davidecaroselli @nicolabertoldi  : is there a script/utility to get the map domain name - number?

**Comment by davidecaroselli** [comment]
Hi @cattoni 

in the new incremental version, that has not been published yet, the domains are always identified by a sequential id, we must add the name information in that API as you suggested.

By the way to get the full list of domains you can query MMT with this API:
```
GET /domains
```

in a shell:

```
curl "http://localhost:8045/domains" | python -mjson.tool
```

hope this help!
Davide

**Comment by cattoni** [comment]
Great! thanks @davidecaroselli
