### ISSUE TITLE
some binaries do not find librockslm.so and libfastalign.so 

### ISSUE THREAD

**Issue by cattoni** [ModernMT/MMT#173]
The following binaries under $MMT_HOME/build/bin
`create_alm, create_slm, fa_align, fa_build, query`
fail because they don't find a lib (either librockslm.so or libfastalign.so), even though such libs are present in $MMT_HOME/build/lib

The binaries work correctly after setting 
`export LD_LIBRARY_PATH=${MMT_HOME}/build/lib`

**Comment by davidecaroselli** [comment]
Hi @cattoni 

those binaries are meant to be used by MMT for training. In order to be used also directly from command line you have to export the LD_LIBRARY_PATH like:
```
export LD_LIBRARY_PATH=/path/to/mmt/build/lib
```
