### ISSUE TITLE
Hi, we noticed that Matecat alters .ttx file's header. Is it possible to prevent that?

### ISSUE THREAD

**Issue by wsuphappyhour** [ModernMT/MMT#174]
Hi, we noticed that Matecat alters .ttx file's header. Is it possible to prevent that? 

Original on the left side.
![image](https://cloud.githubusercontent.com/assets/20355306/19232992/7d419fda-8eeb-11e6-8b02-905b14db6d3d.png)
[Changes.zip](https://github.com/ModernMT/MMT/files/519276/Changes.zip)

Thanks!

**Comment by davidecaroselli** [comment]
Hi @wsuphappyhour 

probably you've posted this issue on the wrong board :)
MateCAT has a totally different dev-team than MMT, so please re-post this issue on the MateCAT board.

Thank you!

**Comment by wsuphappyhour** [comment]
Sorry, my bad.
