### ISSUE TITLE
Bug: We noticed that after translation there's still to-do words and only "preview" option is available

### ISSUE THREAD

**Issue by wsuphappyhour** [ModernMT/MMT#176]
Hi,
We noticed that after translation(all segments are approved and revised) there's still to-do words and only "Preview" option is available not "Download Translation".

![image](https://cloud.githubusercontent.com/assets/20355306/19434565/e5198fa4-946e-11e6-92d5-021dd2ef373a.png)

![image](https://cloud.githubusercontent.com/assets/20355306/19434577/f6fcf5bc-946e-11e6-831e-d317259461d8.png)

Thanks!

**Comment by davidecaroselli** [comment]
Hi @wsuphappyhour

probably you've posted this issue on the wrong board :)
MateCAT has a totally different dev-team than MMT, so please re-post this issue on the MateCAT board.

Thank you!
