### ISSUE TITLE
"fa_build" appears to be not thread-safe

### ISSUE THREAD

**Issue by cattoni** [ModernMT/MMT#177]
Given the same input models (with parameter "-s" and "-t"), the executable "fa_build" produces the files "forward.fam" and "backward.fam" that change every time the command is invocated.

The only way to make "fa_build" generate the same "*.fam" files is to set the optional parameter '-n' to  1, i.e. set the number of thread to 1 (== no multi-threading).
Any other setting (li.e. leaving number of thread not specified or setting -n to a number > 1) appears to produce different "*.fam" files.

Since in the training pipeline "fa_build" is used with the -n parameter unspecified, this implies that  the models generates by two invocations of "mmt create" on the same data differ.

This issue has been verified on both v0.13 and v0.14-alpha releases.

**Comment by davidecaroselli** [comment]
Hi @cattoni !

Can you and @nicolabertoldi work on this? It's low priority because this bug does not lower the quality significantly.

Davide

**Comment by nicolabertoldi** [comment]
fastalign is actually thread-safe, in the sense it produces always and exactly the same alignments, although the binary models estimated during training differ.

No further investigation was done to understand why the binary models differ, because this difference does not impact on the performance.
