### ISSUE TITLE
example quick start

### ISSUE THREAD

**Issue by vince62s** [ModernMT/MMT#179]
Hi,
I installed a fresh new Ubuntu 14.04 and followed the full steps (build from source).
Running the example given in the repo.
First start:
create OK, start OK, translate hanging with java process < 3% during for ever. I stopped it
I rebooted
Second start:
start OK, translate OK "hello world" => "hello mondo"
add (ciao) OK but taking quite long (>20 seconds)
translate: no change "hello mondo" not ciao

I have 30GB of ram and 16 cores on my VM (xeon 2550 2.9Ghz) so should be quite fast
but the java process during "add" above is taking less than a few percents.

thanks for your insight.

**Comment by vince62s** [comment]
correction:
After another dist-upgrade and reboot, it works as expected and quite fast.

**Comment by czester13** [comment]
Hi vince62s,
Do you have version compiled from the source or binary distribution? I'm asking about it because I have the same problem - wrong incremental translation and slow adding translations. I have newest binary installation so I don't know what to do to upgrade my system. Would you say more how did you fix this problem?
Regards,
Thomas

**Comment by vince62s** [comment]
did you reboot then update / dist-upgrade, reboot again ?
I compiled from source, but the behavior was actually strange.
after the 2 reboots it worked fine.

**Comment by marcotrombetti** [comment]
@davidecaroselli I also had the problem and it looks similar to the problem we had at the AMTA tutorial.

Adding priority for the 0.14

**Comment by davidecaroselli** [comment]
Hi guys!

I suspect we have a race condition at the MMT launch, and not all its components are starting correctly. Could you please attach the log file `mmt/runtime/default/logs/embedded-kafka.log` ?

Thanks!

**Comment by vince62s** [comment]
here you go.

**Comment by davidecaroselli** [comment]
Hi @vince62s , no file attached

**Comment by davidecaroselli** [comment]
ok, so this log suggests that everything is working as expected. Is this the log from the MMT run that presented the slow(no)-update problem?

**Comment by vince62s** [comment]
of course, sorry for this.
It did not work tuesday night, but then after a reboot I "recreated" the default model yesterday morning.
So yes this is the log of the last build that worked. It overrid the previous one.

**Comment by vince62s** [comment]
Davide, I am rebuilding a new VM from scratch and will give you the detailed log.

**Comment by davidecaroselli** [comment]
Thanks vince62!

Actually the bug should be observed in the `mmt start` part; so you can reuse the same models, they're just perfect as they are!

so if you execute something like:
```
./mmt start
./mmt add ibm "example" "esempio"
```
and the last command takes too much time (normally takes **less than a second**), you've hit the bug! In this case, if you could provide the content of the file `mmt/runtime/default/logs/embedded-kafka.log` and the output of the command `jps`, it would be great!

Thank you!

**Comment by vince62s** [comment]
no it's fast now.

**Comment by davidecaroselli** [comment]
Update on this issue:

The problem was caused by Kafka not starting correctly, and MMT not alerting the problem: the engine kept waiting the update to be published on Kafka that was not running.

We solved both issues and the fix is available starting from commit 67e6a4b63deb5df47672660b095240dc0ce8d426
