### ISSUE TITLE
incremental training clarification

### ISSUE THREAD

**Issue by vince62s** [ModernMT/MMT#180]
Hi,
Just to make things clear. If for a given engine I have at time t=0 domainA.en and domainA.it
I create the engine and if later on I have 2 more files domainB.en and domainB.it that I drop in the same folder. will ./mmt create start from scratch or do incremental training ? or can we use the ./mmt add command with "files" ?
thanks

**Comment by marcotrombetti** [comment]
First sorry, being this a functionality of the Alpha release it has not been documented yet.

If you run 
```
./mmt create
```
you are building from scratch a new engine with DomainA+DomainB

If you want to add data you can use the command line
```
./mmt import -x ~/demo/netplan.tmx
```

Or use the [API](https://github.com/ModernMT/MMT/wiki/API-Documentation#add-a-sentence-to-a-domain-incremental-learning)

**Comment by vince62s** [comment]
Thanks Marco. Your link is dead but if this is your video I watched it.
I was able to train a model with > 20 Mio segements, took some time.
One thing could be helpful though, it's to log some stats about the number of segments imported, size of the PT or SAPT, number of n-grams for the LMs ...
It is now difficult to size properly the RAM when you load the model.

Actually my model loading just crashed on a 30GB machine (so I will allot more) and there is a residual java process that I cannot kill, I may need to reboot.

One last thing: my experience with Moses showed that in most cases you can use cube pruning limit to 400 instead of the defaut value 1000, with no loss in quality and big improvement in speed...
Just letting you know.

Anyhow great work, all of this.

**Comment by cattoni** [comment]
Hi @vince62s 

I confirm the first link is dead. 
But the second one about the API is working:

> https://github.com/ModernMT/MMT/wiki/API-Documentation#add-a-sentence-to-a-domain-incremental-learning

Hopefully you can find it useful.

**Comment by marcotrombetti** [comment]
Link to tutorial fixed.

Thanks for the pruning tip, to @davidecaroselli the final decision.

This alpha was very basic to allow the tutorial at AMTA. In a few weeks we should be able to push a solid and documented build.
