### ISSUE TITLE
add "x86_64" in HW Requirements of Install.md

### ISSUE THREAD

**Issue by cattoni** [ModernMT/MMT#181]
Today a collegue of mine tried to install MMT on a Ubuntu 14.04 machine in the cloud.

After some troubles I helped him and we discovered he was using a *32 hardware-platform instead of *64.

Actually the Install.md file is missing this information explicitely -- well, it could be deducted from the paragraph about Java versions.

I think it is better to add explicitely in the HW Requirements section that a  x86_64 hardware-platform is needed.

I can do this operations on the various branches.

**Comment by marcotrombetti** [comment]
Roldano,

Thanks, please fill free to modify the Install.md on github master.

Marco

**Comment by cattoni** [comment]
Good.
I do it immediately.

  Roldano

**Comment by cattoni** [comment]
Committed and pushed the branch 'develop'.
I don't' have the permission to push the branch 'master' -- and probably this is good :-)

Roldano

**Comment by davidecaroselli** [comment]
just merged into master, thanks @cattoni !
