### ISSUE TITLE
MMT cluster question

### ISSUE THREAD

**Issue by vince62s** [ModernMT/MMT#187]
Hello,

I have some questions regarding the Cluster architecture.

Does it load the models (sapt+lm) on all nodes ? 

Do all nodes play the same role or is there a concept of master / slave ?

What criteria are used for load balancing ? cpu usage ? memory too ?

thanks
Vincent

**Comment by davidecaroselli** [comment]
Hi @vince62s 

first of all, for v014-alpha the cluster feature is not active, so you should not try to use it. I'll explain the cluster feature in version 0.13:
-  All models are automatically synced from the machine you specify in the `--join` option. You don't have to do anything else.
- No master/slave pattern, all machines in the cluster expose the API and they load-balance the computation in the whole cluster. So even if you send the translation request to node A, it can be executed on node B if the first is busy.
- Queries are distributed to nodes that can run them. Every node as a given number of translation thread, if a node has available thread it will run the request. If no nodes have available threads, the request is simply enqueued until a node executes it.

**Comment by davidecaroselli** [comment]
I'm closing this issue, if you have any further questions please reopen it.

Cheers,
Davide
