### ISSUE TITLE
One system - multiple languages

### ISSUE THREAD

**Issue by mehmedes** [ModernMT/MMT#198]
Would it be possible to create one engine supporting multiple languages?

MMT offers the possibility to include various domains in one system. What if I use corpora in different languages and make MMT think it were different domains. Of course, I'd need to use the same language abbreviation as filename appendix so that MMT does think the corpora were simply different domains.

**Comment by marcotrombetti** [comment]
Nice idea. Never tried.

It may work if you have multiple source languages and one target language.
You may still have multiple domains per source language. The context
guesser will do the work.

Not sure how to do multiple target languages without changing the code a
little bit.

If you try this please let us know the results!

**Comment by mehmedes** [comment]
I'll try and keep you updated!
