### ISSUE TITLE
Translate a file? 

### ISSUE THREAD

**Issue by mehmedes** [ModernMT/MMT#200]
Is it/will it be possible to translate a file?

**Comment by marcotrombetti** [comment]
**If you are and end-user:**
MMT does not have yet an interface to do that. But we are working on integrating MMT with [Matecat](http://www.matecat.com) in the next months. This will do that.

**if you are a developer:**
MMT has a sentence level [API](https://github.com/ModernMT/MMT/wiki/API-Documentation). 

If you need to translate a plain text file, just break it into sentences and translate it using the API.

If you want to translate Word, HTML and other 70 files formats, you can to the following:

* Use the [Matecat Filters](http://filters.matecat.com) to convert any file into XLIFF
* Send to the MMT API all the sentences (it will manage tags)
* Put back the translations into the XLIFF
* Use Matecat Filters to get back the target file.

Matecat filters are also available [as a service](https://market.mashape.com/translated/matecat-filters/).

If you implement this we will be happy to add it as a contrib.

**Comment by davidecaroselli** [comment]
@mehmedes if you need to translate *plain text - one line, one sentence* you can use the built-in script in MMT. In the example below the command is translating `examples/data/train/europarl.en`:

```
cat examples/data/train/europarl.en | ./mmt translate --context-file examples/data/train/europarl.en --batch
```

**Comment by mehmedes** [comment]
In your example,  how can I have Europarl.en translated while creating the output Europarl.de, in other words a file containing the translation?

**Comment by davidecaroselli** [comment]
Hi @mehmedes 
you're probably looking for STDOUT redirection:
```
cat examples/data/train/europarl.en | ./mmt translate --context-file examples/data/train/europarl.en --batch > europarl.de
```

**Comment by mehmedes** [comment]
Thanks :)
