### ISSUE TITLE
Preprocessed files location? 

### ISSUE THREAD

**Issue by mehmedes** [ModernMT/MMT#201]
Where's the location of the preprocessed files, e.  g. cleaned up, tokenized corpora, that are used for training.

**Comment by marcotrombetti** [comment]
Are you looking for the location of your corpus cleaned/tokenized/etc or where you can find the data for creating a engine?

**Comment by mehmedes** [comment]
For corpus cleaned/tokenized/etc

**Comment by davidecaroselli** [comment]
Hi @mehmedes 

during creation of an engine, temporary files are usually removed; but you can prevent it by using the `--debug` flag like so:

```
./mmt create en it examples/data/train/ --debug
```

you can find all temporary files under `runtime/default/tmp/training/`

**Comment by mehmedes** [comment]
Thank you for all your answers. These were of great help!
