### ISSUE TITLE
Hardware requirements and setup time

### ISSUE THREAD

**Issue by mwunderlich** [ModernMT/MMT#203]
Hi all, 

Not really an issue as such, but I haven't found any user or developer forums for MMT. I have three basic questions: 
- What are the recommended and minimum hardware specs for running the MT engine? 
- How much effort is it to setup the system when starting from scratch? 
- And finally, how does it compare to other systems (Moses, Phrasal, Apertium) in terms of performance? (I know there is variety of factors influencing this, but maybe someone has experience with a comparative evaluation of these systems)

Thanks a lot. 

Cheers, 
Martin

**Comment by marcotrombetti** [comment]
Martin,

**HW:**
On the INSTALL.md file you will find the hw requirements in relation with the amount of data.
I personally use 16core, 30GB RAM for models of ~100M words.

**Effort:**
If you have your data in TMX or line aligned text files. You will be running an engine in few hours.
```
./mmt create en fr data-folder/
```

**Compare:**
run
```
./mmt evaluate
```
And it will tell you exactly how your engine performs compared to Google.
If you have even a small amount of in domain data it will easily be better than Google.


I hope this answer your questions.

**Comment by mwunderlich** [comment]
Hi Marco,


Thanks so much for the superfast reply. This sounds all very good. 
Apologies, I somehow missed the install.md file. Should've looked more 
closely.


Cheers,


Martin



Am 30.11.16 um 21:28 schrieb Marco Trombetti:

**Comment by marcotrombetti** [comment]
Happy to hear that, let us know how things goes.
