### ISSUE TITLE
Hardware requirements - engine deployment 

### ISSUE THREAD

**Issue by mehmedes** [ModernMT/MMT#204]
Before starting training, MMT checks the hardware and let's me know whether the components are sufficient. In the readme there is a rule of thumb on hardware requirements for training data size. 

Is there also a similar measure for deploying an engine?  I was wondering,  if I've trained a large engine on  a powerful server,  whether I could run that engine on a smaller scale server? What engine size requires what cpu/ram performance?

**Comment by davidecaroselli** [comment]
Hi @mehmedes 

usually you should use more or less the same hardware for training and translating, but you can save:

- **Disk space**: during the training lot of temp files are generated that aren't needed anymore so you could use less disk space for translation.
- **CPUs**: having more CPUs give the system a higher throughput, but if you need to contain the costs you can choose a machine with less cores.
