### ISSUE TITLE
How to train TMX files?

### ISSUE THREAD

**Issue by memoday** [ModernMT/MMT#208]
Hi there,

I am watching your project and I believe it's going to be a great contribution. 

I am trying to build an engine following your wiki "Create an engine from scratch", but I cannot seem to find how to train TMX files. What would be the command? In the wiki page, I see the following:

data/microsoft.en
data/microsoft.fr
data/europarl.en
data/europarl.fr
data/wmt10.en
data/wmt10.fr

but it doesn't say how these were generated? As you know, TMX files have bilingual pairs. What did you do to extract parallel source and target texts? 

One last question, out of curiosity:

How different MMT is from Google TensorFlow?

thanks,
Mohamed

**Comment by marcotrombetti** [comment]
You don't need a special command to train tmx.
Just put them in the folder and run
./mmt create en fr folder/

MMT reads tmx

Regarding the second question:
MMT is a enterprise production ready improvement over statistical mt. Tensorflow translation tutorial is a promising new approach based on deep learning, probably but not suitable to production.

**Comment by davidecaroselli** [comment]
Hi @memoday I'm closing this issue for the moment. If you have any further question please re-open it.

Thanks!
