### ISSUE TITLE
MERT weights going to all-zero when tuning with moses2 (except for DM0_2 = 1.0)

### ISSUE THREAD

**Issue by cidermole** [ModernMT/MMT#209]
Created a new bug for this, because it's a separate issue with MERT hitting these weights in iteration 7 with the toy data from `examples/data/train`:

```
The decoder died. CONFIG WAS -weight-overwrite 'PhrasePenalty0= 0.000000 Sapt= 0.000000 0.000000 0.000000 0.000000 InterpolatedLM= 0.000000 Distortion0= 0.000000 WordPenalty0= -0.000000 DM0= 0.000000 -0.000000 1.000000 0.000000 0.000000 0.000000 0.000000 0.000000'
```

@cattoni reported in #206:

With the new system,  "mmt tune" still fails with this error:

```
INFO: (3 of 4) Tuning...                                               DONE (in 32s)
ERROR Unexpected exception:
	Command '/home/ubuntu/NEW_ModernMT/cli/opt/mert-moses.perl /home/ubuntu/NEW_ModernMT/runtime/ex1/tmp/tuning/corpus.en /home/ubuntu/NEW_ModernMT/runtime/ex1/tmp/tuning/corpus.it /home/ubuntu/NEW_ModernMT/cli/opt/mertinterface.py /tmp/tmpxvdDF0 --threads 16 --mertdir /home/ubuntu/NEW_ModernMT/build/bin --mertargs '--binary --sctype BLEU' --working-dir /home/ubuntu/NEW_ModernMT/runtime/ex1/tmp/tuning/mert --nbest 100 --decoder-flags "--port 8045" --nonorm --closest --no-filter-phrase-table --predictable-seeds --maximum-iterations=25' failed with exit code 2
Traceback (most recent call last):
  File "./mmt", line 589, in <module>
    main()
  File "./mmt", line 567, in main
    actions[command](args)
  File "./mmt", line 115, in main_tune
    random_seeds=args.random_seeds, max_iterations=args.max_iterations)
  File "/home/ubuntu/NEW_ModernMT/cli/cluster.py", line 549, in tune
    shell.execute(' '.join(command), stdout=log, stderr=log)
  File "/home/ubuntu/NEW_ModernMT/cli/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
cli.libs.shell.ShellError: Command '/home/ubuntu/NEW_ModernMT/cli/opt/mert-moses.perl /home/ubuntu/NEW_ModernMT/runtime/ex1/tmp/tuning/corpus.en /home/ubuntu/NEW_ModernMT/runtime/ex1/tmp/tuning/corpus.it /home/ubuntu/NEW_ModernMT/cli/opt/mertinterface.py /tmp/tmpxvdDF0 --threads 16 --mertdir /home/ubuntu/NEW_ModernMT/build/bin --mertargs '--binary --sctype BLEU' --working-dir /home/ubuntu/NEW_ModernMT/runtime/ex1/tmp/tuning/mert --nbest 100 --decoder-flags "--port 8045" --nonorm --closest --no-filter-phrase-table --predictable-seeds --maximum-iterations=25' failed with exit code 2
```

The execution of the above shell command on the command line reports:

```
Using SCRIPTS_ROOTDIR: /home/ubuntu/NEW_ModernMT/cli/opt
File not found: /tmp/tmpxvdDF0 (interpreted as /tmp/tmpxvdDF0). at /home/ubuntu/NEW_ModernMT/cli/opt/mert-moses.perl line 494.
```

The directory runtime/$ENGINE/tmp/tuning/mert/ contains few files:

```
rw-rw-r-- 1 ubuntu ubuntu    167 Dec 13 18:08 features.list
-rw-rw-r-- 1 ubuntu ubuntu 205274 Dec 13 18:08 run1.best100.out
-rw-rw-r-- 1 ubuntu ubuntu    189 Dec 13 18:08 run1.dense
-rw-rw-r-- 1 ubuntu ubuntu    419 Dec 13 18:08 run1.moses.ini
-rw-rw-r-- 1 ubuntu ubuntu   1571 Dec 13 18:08 run1.out
```

It appears that only 2 of the 29 input sentences have been translates (run1.out  contains 2 lines, run1.best100.out 200 lines).

The new system info: 
branch features/moses2
commit 80e8938dc527a0980d652ab7b0c9409d0109c85d
Author: David Madl <git@abanbytes.eu>
Date:   Fri Dec 9 14:26:38 2016 +0100

**Comment by cidermole** [comment]
as written to Davide:

two sentences in an n-best list have almost exactly the same feature value, not exactly but ~ up to 32-bit float machine precision (epsilon). [ASCII deserialized]

The Powell search algo in MERT is looking for changing line slopes along a feature weight in `Optimizer::LineOptimize()`. The intersection point of two lines with almost exactly the same slope lies very far away in `intersect()` and unfortunately that's a sentence on the border having the best BLEU.

There's no reason not to have n-best sentences with the same feature weight (note the reordering statistics in that DM0_2 feature [DiscontinuousLeftOrientation] are rational numbers).

A quick and simple hack should be to change MERT to avoid going in straight axis directions, and always go in a random direction.

**Comment by cidermole** [comment]
867960a should finally fix this.

**Comment by cidermole** [comment]
@cattoni would you confirm?

**Comment by cattoni** [comment]
Just tested, I confim it works.
Thanks @cidermole !
