### ISSUE TITLE
Corpora preprocessing crashes

### ISSUE THREAD

**Issue by mehmedes** [ModernMT/MMT#210]
Corpora preprocessing crashes with the following error message:

INFO: (1 of 7) TMs clean-up...                                         DONE (in 332s)
INFO: (2 of 7) Corpora preprocessing...                                DONE (in 1315s)
ERROR Unexpected exception:
        Command 'java -cp /home/sariymx/mmt/build/mmt-0.14.jar -Dmmt.home=/home/sariymx/mmt -Djava.library.path=/home/sariymx/mmt/build/lib eu.modernmt.cli.TrainingPipelineMain -s en -t de -v /home/sariymx/mmt/engines/ende/models/vocabulary --output /home/sariymx/mmt/runtime/ende/tmp/training/preprocessed --input /home/sariymx/mmt/runtime/ende/tmp/training/training_corpora --dev /home/sariymx/mmt/engines/ende/data/dev --test /home/sariymx/mmt/engines/ende/data/test' failed with exit code -6
Traceback (most recent call last):
  File "./mmt", line 583, in <module>
    main()
  File "./mmt", line 561, in main
    actions[command](args)
  File "./mmt", line 383, in main_create
    debug=args.debug, steps=args.training_steps, split_trainingset=args.split_corpora)
  File "/home/sariymx/mmt/cli/engine.py", line 209, in build
    (self._engine.data_path if split_trainingset else None)
  File "/home/sariymx/mmt/cli/mt/processing.py", line 142, in process
    shell.execute(command, stdin=shell.DEVNULL, stdout=shell.DEVNULL, stderr=shell.DEVNULL)
  File "/home/sariymx/mmt/cli/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
cli.libs.shell.ShellError: Command 'java -cp /home/sariymx/mmt/build/mmt-0.14.jar -Dmmt.home=/home/sariymx/mmt -Djava.library.path=/home/sariymx/mmt/build/lib eu.modernmt.cli.TrainingPipelineMain -s en -t de -v /home/sariymx/mmt/engines/ende/models/vocabulary --output /home/sariymx/mmt/runtime/ende/tmp/training/preprocessed --input /home/sariymx/mmt/runtime/ende/tmp/training/training_corpora --dev /home/sariymx/mmt/engines/ende/data/dev --test /home/sariymx/mmt/engines/ende/data/test' failed with exit code -6

Thanks for your support!

**Comment by davidecaroselli** [comment]
Hi @mehmedes 

could you please send me the training data and the command you run in order to replicate the bug?
Thanks!

**Comment by mehmedes** [comment]
I tried reducing the the corpust size and now got past the preproccesing steps. Now, it crashes during language model training,  however:

`INFO: (1 of 7) TMs clean-up...                                         DONE (in 23s)
INFO: (2  DONE (in 2065s)eprocessing...
INFO: (3 of 7) Context Analyzer training...                            DONE (in 73s)
INFO: (4 of 7) Aligner training...                                     DONE (in 4056s)
INFO: (5 of 7) Translation Model training...                           DONE (in 4513s)
INFO: (6 of 7) Language Model training...                              DONE (in 14782s)
ERROR Unexpected exception:
        Command '/home/sariyildiznureddin/mmt/build/bin/create_alm -m /home/sariyildiznureddin/mmt/engines/ende/models/lm/foreground.alm -i /home/sariyildiznureddin/mmt/runtime/ende/tmp/training/lm/alm_train -b 100000000' failed with exit code -6
Traceback (most recent call last):
  File "./mmt", line 583, in <module>
    main()
  File "./mmt", line 561, in main
    actions[command](args)
  File "./mmt", line 383, in main_create
    debug=args.debug, steps=args.training_steps, split_trainingset=args.split_corpora)
  File "/home/sariyildiznureddin/mmt/cli/engine.py", line 243, in build
    working_dir, log_file)
  File "/home/sariyildiznureddin/mmt/cli/mt/lm.py", line 162, in train
    shell.execute(command, stdout=log, stderr=log)
  File "/home/sariyildiznureddin/mmt/cli/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
cli.libs.shell.ShellError: Command '/home/sariyildiznureddin/mmt/build/bin/create_alm -m /home/sariyildiznureddin/mmt/engines/ende/models/lm/foreground.alm -i /home/sariyildiznureddin/mmt/runtime/ende/tmp/training/lm/alm_train -b 100000000' failed with exit code -6`

 I used the data provided by the WMT16 Translation Task. These are the exact corpora I used:
[corpora.txt](https://github.com/ModernMT/MMT/files/691392/corpora.txt)

**Comment by AndrewLauder** [comment]
I experienced the same crash when attempting to create en it with example data included in the distribution.

**Comment by davidecaroselli** [comment]
We made some important enhancement in the training logging in the latest MMT master commit.
Could you please try to:
- Delete everything inside `runtime` folder.
- Launch the training process.
- If it crash, attach here all the content of the folder `runtime/<your-engine>/logs`, and the whole output of the `mmt create` command.

In order to have the newest MMT release, you could follow [these instructions](https://github.com/ModernMT/MMT/blob/master/INSTALL.md#option-3---installing-from-source-for-contributors).

Thank you!

**Comment by mehmedes** [comment]
Thanks!

**Comment by mehmedes** [comment]
[ende.zip](https://github.com/ModernMT/MMT/files/764569/ende.zip)

I've just tried v0.14.1. Preprocessing is still crashing. My parallel corpora have the following size:

´´
-rw-rw-r-- 1 sariymx sariymx 40915734 Jan  2 06:34 allg.de
-rw-rw-r-- 1 sariymx sariymx 34663420 Jan  2 06:34 allg.en
-rw-rw-r-- 1 sariymx sariymx 20003432 Jan  2 06:36 chem.de
-rw-rw-r-- 1 sariymx sariymx 19187568 Jan  2 06:36 chem.en
-rw-rw-r-- 1 sariymx sariymx  5680532 Jan  2 06:36 for.de
-rw-rw-r-- 1 sariymx sariymx  5138381 Jan  2 06:36 for.en
-rw-rw-r-- 1 sariymx sariymx 12700145 Jan  2 06:37 iqs.de
-rw-rw-r-- 1 sariymx sariymx 10153772 Jan  2 06:37 iqs.en
-rw-rw-r-- 1 sariymx sariymx  4801689 Jan  2 06:38 klin.de
-rw-rw-r-- 1 sariymx sariymx  3987652 Jan  2 06:38 klin.en
-rw-rw-r-- 1 sariymx sariymx  1371560 Jan  2 06:38 pol.de
-rw-rw-r-- 1 sariymx sariymx  1108077 Jan  2 06:38 pol.en
-rw-rw-r-- 1 sariymx sariymx  2953389 Jan  2 06:39 prod.de
-rw-rw-r-- 1 sariymx sariymx  2619523 Jan  2 06:39 prod.en
-rw-rw-r-- 1 sariymx sariymx  1417679 Jan  2 06:39 recht.de
-rw-rw-r-- 1 sariymx sariymx  1219750 Jan  2 06:39 recht.en
´´

**Comment by davidecaroselli** [comment]
Hi @mehmedes 

can you send me the log file "runtime/<engine_name>/logs/training.log" please?

**Comment by davidecaroselli** [comment]
sorry just realized the zip you sent me is not the training set but the logs :)

**Comment by davidecaroselli** [comment]
you should have this file: "/home/sariymx/mmt/hs_err_pid8891.log"
can you send me it too please?

**Comment by mehmedes** [comment]
Sure !

**Comment by mehmedes** [comment]
[hs_err_pid7685.zip](https://github.com/ModernMT/MMT/files/764606/hs_err_pid7685.zip)

**Comment by davidecaroselli** [comment]
Ok so, the problem is related to an internal native library used by MMT.
It would be possible for you to try compiling MMT directly on your Ubuntu 14.04 machine?
The procedure is not so complicated and it is well documented here: [INSTALL.md - Installing from source](https://github.com/ModernMT/MMT/blob/master/INSTALL.md#option-3---installing-from-source-for-contributors).

If you have any issues in compiling the project, don't hesitate to post any questions here.

**Comment by mehmedes** [comment]
Building from source worked fine:

```
[INFO] Reactor Summary:
[INFO]
[INFO] MMT Root Module ................................... SUCCESS [
[INFO] MMT Model Classes ................................. SUCCESS [
[INFO] MMT Common Interfaces ............................. SUCCESS [
[INFO] Text Processing Module ............................ SUCCESS [
[INFO] FastAlign-based MMT aligner ....................... SUCCESS [
[INFO] Lucene-based Context Analyzer ..................... SUCCESS [
[INFO] MMT Interpolated Language Model ................... SUCCESS [
[INFO] MMT Suffix Array PhraseTable ...................... SUCCESS [
[INFO] Moses-based Decoder ............................... SUCCESS [0
[INFO] RocksDB-based Vocabulary .......................... SUCCESS [
[INFO] SQLite Persistence implementation ................. SUCCESS [
[INFO] MMT Core .......................................... SUCCESS [0
[INFO] Jetty-based REST API .............................. SUCCESS [0
[INFO] Command-line Interface ............................ SUCCESS [1
[INFO] --------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] --------------------------------------------------------------
[INFO] Total time: 24:18 min
[INFO] Finished at: 2017-02-10T04:14:43-06:00
[INFO] Final Memory: 256M/6957M
[INFO] --------------------------------------------------------------
```

This time  it crashes during Aligner training:
```

INFO: (1 of 7) TMs clean-up...                                         DONE (in 3s)
INFO: (2 of 7) Corpora preprocessing...                                DONE (in 36s)
INFO: (3 of 7) Context Analyzer training...                            DONE (in 7s)
INFO: (4 of 7) Aligner training...                                     DONE (in 0s)
ERROR Unexpected exception:
        Command '/home/sariymx/ModernMT/build/bin/fa_build -s /home/sariymx/ModernMT/runtime/ende/tmp/training/aligner/merge.en -t /home/sariymx/ModernMT/runtime/ende/tmp/training/aligner/merge.de -m /home/sariymx/ModernMT/engines/ende/models/align -I 4' failed with exit code 127
Traceback (most recent call last):
  File "./mmt", line 549, in <module>
    main()
  File "./mmt", line 526, in main
    actions[command](args)
  File "./mmt", line 357, in main_create
    debug=args.debug, steps=args.training_steps, split_trainingset=args.split_corpora)
  File "/home/sariymx/ModernMT/cli/engine.py", line 251, in build
    self._engine.aligner.build(cleaned_bicorpora, working_dir, log=logger.stream)
  File "/home/sariymx/ModernMT/cli/mt/phrasetable.py", line 59, in build
    shell.execute(command, stdout=log, stderr=log)
  File "/home/sariymx/ModernMT/cli/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
cli.libs.shell.ShellError: Command '/home/sariymx/ModernMT/build/bin/fa_build -s /home/sariymx/ModernMT/runtime/ende/tmp/training/aligner/merge.en -t /home/sariymx/ModernMT/runtime/ende/tmp/training/aligner/merge.de -m /home/sariymx/ModernMT/engines/ende/models/align -I 4' failed with exit code 127
```

[ende.zip](https://github.com/ModernMT/MMT/files/766381/ende.zip)

**Comment by davidecaroselli** [comment]
Error in the log says: `/home/sariymx/ModernMT/build/bin/fa_build: error while loading shared libraries: libboost_filesystem.so.1.55.0: cannot open shared object file: No such file or directory`

This is very strange because while installing from source, you should have been run the command:
```
sudo apt-get install libboost1.55-all-dev
```

and you should have *boost  1.55* installed in `/usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.55.0`, correct?

And also, could you please run:
```
ldd /path/to/mmt/build/lib/libfastalign.so
```

and copy here the output please?

**Comment by mehmedes** [comment]
```
linux-vdso.so.1 =>  (0x00007ffd089c2000)
        libboost_filesystem.so.1.55.0 => not found
        libboost_system.so.1.55.0 => not found
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f702a213000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7029f0d000)
        libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f7029cdf000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f7029ac7000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7029702000)
        /lib64/ld-linux-x86-64.so.2 (0x000055e0f2e12000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f70294e4000)
```

**Comment by davidecaroselli** [comment]
it seems you have not installed libboost. Can you please re-run this command?
```
sudo apt-get install libboost1.55-all-dev
```

and check again if you solve the **not found** issues?

**Comment by mehmedes** [comment]
Great! Thanks for your support!

```

INFO: (1 of 7) TMs clean-up...                                         DONE (in 3s)
INFO: (2 of 7) Corpora preprocessing...                                DONE (in 35s)
INFO: (3 of 7) Context Analyzer training...                            DONE (in 8s)
INFO: (4 of 7) Aligner training...                                     DONE (in 2m 57s)
INFO: (5 of 7) Translation Model training...                           DONE (in 4m 43s)
INFO: (6 of 7) Language Model training...                              DONE (in 5m 1s)
INFO: (7 of 7) Writing config files...                                 DONE (in 0s)

=========== TRAINING SUCCESS ===========
```

**Comment by davidecaroselli** [comment]
Great!
