### ISSUE TITLE
Running 2 engines on the same machine

### ISSUE THREAD

**Issue by vince62s** [ModernMT/MMT#212]
Something is unclear to me.

if I start a first engine with -p 8046
then a second one with no -p (default port 8045)
it raises an Illegal state error related to some "cluster-port" port 5016 already in use.

Not using cluster right now, so what should be the syntax to use 2 engines on the same machine ?

thanks

**Comment by vince62s** [comment]
well I guess I need to specify some other cluster ports too.

**Comment by vince62s** [comment]
ok, not enough
throwing another error due to port 9092 already in use:
[2017-01-07 20:28:18,674] WARN No meta.properties file under dir /home/moses/ModernMT/engines/en-fr-canada/models/kafka/meta.properties (kafka.server.BrokerMetadataCheckpoint)
[2017-01-07 20:28:18,739] FATAL [Kafka Server 0], Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
kafka.common.KafkaException: Socket server failed to bind to 0.0.0.0:9092: Address already in use.

**Comment by vince62s** [comment]
ok I read this : https://github.com/ModernMT/MMT/issues/205
Do you think you will make this one available shortly ?
I would prefer not to have to install a new VM for each language pair.
Thanks.

**Comment by davidecaroselli** [comment]
Hi @vince62s 
I've just pushed a fix that allows you to specify also the Datastream (aka Kafka) port:
```
./mmt start -p 8046 --cluster-ports 5018 5019 --datastream-port 9093
```

**Comment by vince62s** [comment]
it works, thanks.
