### ISSUE TITLE
Tuning with different tuning set crashes

### ISSUE THREAD

**Issue by mehmedes** [ModernMT/MMT#213]
When tuning my engine on a different tuning set other than the corpus MMT (0.13) created when preprocessing the training files, I get the following error:

`ERROR Unexpected exception:
        Command '/home/sariyildiznureddin/mmt/opt/bin/moses-mmt-dev_2c29__c231/scripts/mert-moses.pl /home/sariyild
iznureddin/mmt/runtime/ende/tmp/tuning/corpus.en /home/sariyildiznureddin/mmt/runtime/ende/tmp/tuning/corpus.de /ho
me/sariyildiznureddin/mmt/scripts/mertinterface.py /tmp/tmpnTh3jy --threads 8 --mertdir /home/sariyildiznureddin/mm
t/opt/bin/moses-mmt-dev_2c29__c231/bin --mertargs '--binary --sctype BLEU' --working-dir /home/sariyildiznureddin/m
mt/runtime/ende/tmp/tuning/mert --nbest 100 --decoder-flags "--port 8045" --nonorm --closest --no-filter-phrase-tab
le' failed with exit code 2
Traceback (most recent call last):
  File "./mmt", line 440, in <module>
    main()
  File "./mmt", line 416, in main
    main_tune(args)
  File "./mmt", line 109, in main_tune
    node.tune(corpora=corpora, debug=args.debug, context_enabled=args.context_enabled)
  File "/home/sariyildiznureddin/mmt/scripts/cluster.py", line 381, in tune
    shell.execute(' '.join(command), stdout=log, stderr=log)
  File "/home/sariyildiznureddin/mmt/scripts/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
scripts.libs.shell.ShellError: Command '/home/sariyildiznureddin/mmt/opt/bin/moses-mmt-dev_2c29__c231/scripts/mert-
moses.pl /home/sariyildiznureddin/mmt/runtime/ende/tmp/tuning/corpus.en /home/sariyildiznureddin/mmt/runtime/ende/t
mp/tuning/corpus.de /home/sariyildiznureddin/mmt/scripts/mertinterface.py /tmp/tmpnTh3jy --threads 8 --mertdir /hom
e/sariyildiznureddin/mmt/opt/bin/moses-mmt-dev_2c29__c231/bin --mertargs '--binary --sctype BLEU' --working-dir /ho
me/sariyildiznureddin/mmt/runtime/ende/tmp/tuning/mert --nbest 100 --decoder-flags "--port 8045" --nonorm --closest
 --no-filter-phrase-table' failed with exit code 2`

This is the dev set I used:
[http://data.statmt.org/wmt16/translation-task/dev.tgz](url)

**Comment by davidecaroselli** [comment]
Hi @mehmedes 

I've just fixed issue https://github.com/ModernMT/MMT/issues/207 can you check if that solved the issue? Just pull master branch and try tuning again.

Davide

**Comment by mehmedes** [comment]
Thanks Davide!
Cleaning up the dev set did the trick.
