### ISSUE TITLE
Add Neural Language Model?

### ISSUE THREAD

**Issue by mehmedes** [ModernMT/MMT#214]
Would it be possible to enhance the statistical language model by a neural language model, similar to [Rico Sennrich's 2015 WMT submission](https://github.com/rsennrich/wmt2014-scripts/blob/master/example/toy_example_2015_5.config)

`custom-training = "mkdir -p $working-dir/lm/nplm/nplm$nplm-working-dir && $moses-script-dir/training/train-neurallm.py \
                   --nplm-home $nplm-dir --working-dir $working-dir/lm/nplm/nplm$nplm-working-dir \
                   --output-dir $working-dir/lm/nplm/nplm$nplm-working-dir --output-model nplm \
                   --vocab-size 500000 --noise 100 --order $order \
                   --epochs 10"`

**Comment by mfederico** [comment]
Not yet, but we are currently investigating several “neural” enhancements.
More to come in the next months.

**Comment by mehmedes** [comment]
Ok. Thanks!
