### ISSUE TITLE
Bug in Numeric Expression Post-processor

### ISSUE THREAD

**Issue by davidecaroselli** [ModernMT/MMT#222]
As reported by @vince62s there is a bug with the Numeric Expressions Post-processor, here's an example:

```
There were more then 150 000 new cases of cancer => Il y a eu plus de 000 000 nouveaux cas de cancer
There were more then 150000 new cases of cancer => Il y a eu plus de 150000 nouveaux cas de cancer
There were more then 180,000 new cases of cancer => Il y a eu plus de 180,000 180,000 nouveaux cas de cancer
```

NE Post-processor does not handle well multiple target placeholders for the same source word.

**Comment by nicolabertoldi** [comment]
branch: master commit:3185b56b42162cfcc58bb1e2b786a772b1bbbfe0

mvn clean install fails, with this error:

Failed tests:   testBigNumber_NotMatching(eu.modernmt.processing.numbers.NumericWordTest): expected:<147[530.]50> but was:<147[.530,]50>
  testMultiple_Matching(eu.modernmt.processing.numbers.NumericWordTest): expected:<147[ ]530> but was:<147[]530>
  testCurrency_NotMatching(eu.modernmt.processing.numbers.NumericWordTest): expected:<[$1.76]> but was:<[1,76$]>
  testMultiple_NotMatching(eu.modernmt.processing.numbers.NumericWordTest): expected:<147.530[ ]??> but was:<147.530[]??>

**Comment by davidecaroselli** [comment]
Just pushed the fix into master.

Thanks @nicolabertoldi, sorry for that!
