### ISSUE TITLE
./mmt evaluate hanging

### ISSUE THREAD

**Issue by vince62s** [ModernMT/MMT#223]
Hi,

I am having just one instance where ./mmt evaluate is hanging after translating (MMT) all the test segments.

the node.log does not show anything special
I see the last segment transmitted and all responses but it hangs.
any clue ?

**Comment by vince62s** [comment]
second run on the same engine / test
translations steps finish fine.
matecat measurement and bleu measurement return a 414 error with a never ending string.
could be linked to some kind of weird strings of character in the test sets I imagine.

**Comment by vince62s** [comment]
last feed back: I found the issue, due to a very long and weird segment (made of a lot of escape codes).
maybe filtering the test sets on length could avoid that.
cheers.

**Comment by davidecaroselli** [comment]
Thanks @vince62s !
Good point, we are already working on a more precise cleaning step during training, so we are going to have something like that in the next MMT release.

I close this issue, if you want to add comments or need more help, please re-open it.
