### ISSUE TITLE
installation of g++ required on Ubuntu 16.04

### ISSUE THREAD

**Issue by nicolabertoldi** [ModernMT/MMT#225]
g++   compilers is not installed by default on the "Ubuntu 16.04 LTS" (virtual Machine from Azure) 

I suggest to enhanced the INSTALL.md, with a note like the one for java in the section related to "Option 3 - Installing from source)"

Something like:
Install g++ if not present
  sudo apt-get install g++

or alternatively make it mandatory as the others

By default on Ubuntu 16.04, the following version is installed
"g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609"

**Comment by davidecaroselli** [comment]
Merged into issue #231.
