### ISSUE TITLE
installation of zlib1g-dev required on Ubuntu 16.04

### ISSUE THREAD

**Issue by nicolabertoldi** [ModernMT/MMT#226]
The library zlib1g-dev is not installed by default on the "Ubuntu 16.04 LTS" (virtual Machine from Azure), but it is required by MMT.

I suggest to enhanced the INSTALL.md, with a note like the one for java in the section related to "Option 3 - Installing from source)"

Something like:
Install g++ if not present
  sudo apt-get install zlib1g-dev

 or alternatively make it mandatory as the others

**Comment by davidecaroselli** [comment]
Merged into issue #231.
