### ISSUE TITLE
version of libboost on Ubuntu 16.04 required

### ISSUE THREAD

**Issue by nicolabertoldi** [ModernMT/MMT#227]
By default on the "Ubuntu 16.04 LTS" (virtual Machine from Azure), the library libboost1.55-all-dev is not provided. The only boost library present is libboost1.58-all-dev;

and hence the installation command suggested in INSTALL.md fails

I suggest to add a note about this
or even better avoid to specify the version of the boost library (i.e. "libboost-all-dev"); in this way the OS should install the latest.

new suggested command (including zlib1g-dev, but not g++)
sudo apt-get install zlib1g-dev libbz2-dev libboost-all-dev libsparsehash-dev cmake openjdk-8-jdk git maven

**Comment by davidecaroselli** [comment]
Merged into issue #231.
