### ISSUE TITLE
German translation quality 

### ISSUE THREAD

**Issue by mehmedes** [ModernMT/MMT#229]
The German MMT engines I've tested (based on opus corpora) tend to rather major omissions and forcefully try to nominalize almost any verb. The output for Romance languages is outstanding!!!  Will there be future development on German? Would syntax-based model creation make a difference?

**Comment by davidecaroselli** [comment]
Hi @mehmedes 

we do have plans for improving translation quality, in fact the main goal for MMT in 2017 is to develop a *neural engine* that will have a better output for those languages that are problematic for regular phrase-based systems.

**Comment by mehmedes** [comment]
Wow! That sounds great!

I was wondering how you would react to Google's NMT. In 2016, my MMT output was always better than Google Translate. Since they've launched GNMT, they mostly outperform my MMT engines.

Will your neural engine require GPU or will it be possible set up and run the engine on CPU?

**Comment by davidecaroselli** [comment]
> Will your neural engine require GPU or will it be possible set up and run the engine on CPU?

very hard to answer at this stage of development, probably you will have decent speed performance on GPUs, but you will have all the details once this new version will be released.

**Comment by mehmedes** [comment]
By the way, is it possible to use MMT's API with other engines?
Let's I trained a Moses engine without MMT, could I load that engine into MMT?
And, could I actually run an Nematus or OpenNMT engine on MMT's API?

**Comment by davidecaroselli** [comment]
We have heavily customized the Moses engine in order to make it context-aware and support our online-learning model. For this reason what your asking is not possible off-the-shelf.

It is instead possible to develop custom "Decoder" implementations and plug them into the MMT framework, but this will require and effort in code development.

**Comment by mehmedes** [comment]
Ok. Thanks! That's good to know.
