### ISSUE TITLE
Additional install steps for Ubuntu 16.04

### ISSUE THREAD

**Issue by davidecaroselli** [ModernMT/MMT#231]
This issue refers to previous issues #228 #227 #226 #225.

@nicolabertoldi could you please report here all the additional steps needed in order to build MMT on Ubuntu 16.04 please?

**Comment by nicolabertoldi** [comment]
Ubuntu 14.04 (LTS) and Ubuntu 16.04 LTS (Virtual Machine from Azure) have few differences in the libraries and packages installed by default.

The MMT documentation ([INSTALL.md](https://github.com/ModernMT/MMT/blob/master/INSTALL.md)),  which describes how to install the MMT system from source (see Section "Option 3 - Installing from source (for contributors)", refers to **Ubuntu 14.04**.
Small changes are hence required to install MMT system on **Ubuntu 16.04**.

* The Python module **Requests** is not pre-installed, but it is mandatory for MMT.  To install, please run the following:
``` 
sudo apt-get install python-pip
sudo pip install -U requests
```

* The **g++** compiler is not installed by default, but it is mandatory for MMT. To install, please run the following:
```
sudo apt-get install g++
```

* The libraries **zlib1g-dev** and **libboost1.55-all-dev** are not provided by default. The only boost library present is libboost1.58-all-dev; to avoid issues with the actual version of the library, it is possible to refer to a __generic__ **libboost-all-dev**, which is is just a pointer to the most recent version available.
To install these two libraries together with the other required libraries, please run the following:
```
sudo apt-get install zlib1g-dev libbz2-dev libboost-all-dev libsparsehash-dev cmake openjdk-8-jdk git maven
```

**Comment by davidecaroselli** [comment]
@AndRossi could you please integrate a this infos in the [INSTALL.md](https://github.com/ModernMT/MMT/blob/master/INSTALL.md) document?

**Comment by AndRossi** [comment]
Hi @nicolabertoldi, I've integrated your infos in INSTALL.md.
Now both the procedures for Ubuntu 14.04 and Ubuntu 16.04 are described.
