### ISSUE TITLE
Getting an error while creating a new engine "EN-AR"

### ISSUE THREAD

**Issue by memoday** [ModernMT/MMT#232]
Hello support team,

I followed the instructions mentioned here https://github.com/ModernMT/MMT/issues/208#issuecomment-266766252, but I am getting the following error when I type the following command: 

`./mmt create en ar examples/data/train`

I am also getting the same error when using the command in readme

`./mmt create en ar examples/data/train`

Here is the full error log:

`root@modernmt-VirtualBox:/home/modernmt/Downloads/mmt# ./mmt create en ar examples/data/train
> WARNING: more than 0G of RAM recommended, only 0G available

=========== TRAINING STARTED ===========

ENGINE:  default
BILINGUAL CORPORA: 15 documents
MONOLINGUAL CORPORA: 0 documents
LANGS:   en > ar

INFO: (1 of 7) TMs clean-up...                                         DONE (in 3s)
ERROR Unexpected exception:
	Command 'java -cp /home/modernmt/Downloads/mmt/build/mmt-0.14.1.jar -Dmmt.home=/home/modernmt/Downloads/mmt -Djava.library.path=/home/modernmt/Downloads/mmt/build/lib eu.modernmt.cli.CleaningPipelineMain -s en -t ar --output /home/modernmt/Downloads/mmt/runtime/default/tmp/training/clean_tms --input /home/modernmt/Downloads/mmt/examples/data/train' failed with exit code 1
Traceback (most recent call last):
  File "./mmt", line 549, in <module>
    main()
  File "./mmt", line 526, in main
    actions[command](args)
  File "./mmt", line 357, in main_create
    debug=args.debug, steps=args.training_steps, split_trainingset=args.split_corpora)
  File "/home/modernmt/Downloads/mmt/cli/engine.py", line 222, in build
    unprocessed_bicorpora, self._get_tempdir('clean_tms'), log=logger.stream)
  File "/home/modernmt/Downloads/mmt/cli/mt/processing.py", line 99, in clean
    shell.execute(command, stdout=log, stderr=log)
  File "/home/modernmt/Downloads/mmt/cli/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
cli.libs.shell.ShellError: Command 'java -cp /home/modernmt/Downloads/mmt/build/mmt-0.14.1.jar -Dmmt.home=/home/modernmt/Downloads/mmt -Djava.library.path=/home/modernmt/Downloads/mmt/build/lib eu.modernmt.cli.CleaningPipelineMain -s en -t ar --output /home/modernmt/Downloads/mmt/runtime/default/tmp/training/clean_tms --input /home/modernmt/Downloads/mmt/examples/data/train' failed with exit code 1
`
How can this be fixed?

thanks,
Mohamed

P.S. I am using Ubuntu 14.04 VirtualBox image to run this test.

**Comment by davidecaroselli** [comment]
Hi @memoday !

can you please post the file `runtime/<engine-name>/logs/training.log`?

**Comment by memoday** [comment]
Here it's:

`2017-02-17 12:14:22,779 [INFO] - Training started: engine=default, bilingual=15, monolingual=0, langpair=en-ar
2017-02-17 12:14:22,779 [INFO] - Training step "TMs clean-up" (1/7) started
2017-02-17 12:14:22,779 [DEBUG] - Shell exec: java -cp /home/modernmt/Downloads/mmt/build/mmt-0.14.1.jar -Dmmt.home=/home/modernmt/Downloads/mmt -Djava.library.path=/home/modernmt/Downloads/mmt/build/lib eu.modernmt.cli.CleaningPipelineMain -s en -t ar --output /home/modernmt/Downloads/mmt/runtime/default/tmp/training/clean_tms --input /home/modernmt/Downloads/mmt/examples/data/train
2017-02-17 12:14:23,863 main INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
Exception in thread "main" java.io.IOException: Invalid TMX eu.modernmt.io.FileProxy$1@3da673d1
	at eu.modernmt.model.corpus.impl.tmx.TMXBilingualLineReader.read(TMXBilingualLineReader.java:54)
	at eu.modernmt.cleaning.FilteredBilingualCorpus.initialize(FilteredBilingualCorpus.java:114)
	at eu.modernmt.cleaning.FilteredBilingualCorpus.getContentReader(FilteredBilingualCorpus.java:54)
	at eu.modernmt.training.CleaningTask.call(CleaningTask.java:27)
	at eu.modernmt.training.CleaningTask.call(CleaningTask.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:596)
	at com.sun.xml.internal.stream.XMLEventReaderImpl.nextEvent(XMLEventReaderImpl.java:83)
	at eu.modernmt.model.corpus.impl.tmx.TMXPairReader.read(TMXPairReader.java:43)
	at eu.modernmt.model.corpus.impl.tmx.TMXBilingualLineReader.read(TMXBilingualLineReader.java:52)
	... 10 more
2017-02-17 12:14:26,337 [INFO] - Training step "TMs clean-up" completed in 3s
2017-02-17 12:14:26,338 [ERROR] - Unexpected exception
Traceback (most recent call last):
  File "/home/modernmt/Downloads/mmt/cli/engine.py", line 222, in build
    unprocessed_bicorpora, self._get_tempdir('clean_tms'), log=logger.stream)
  File "/home/modernmt/Downloads/mmt/cli/mt/processing.py", line 99, in clean
    shell.execute(command, stdout=log, stderr=log)
  File "/home/modernmt/Downloads/mmt/cli/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
ShellError: Command 'java -cp /home/modernmt/Downloads/mmt/build/mmt-0.14.1.jar -Dmmt.home=/home/modernmt/Downloads/mmt -Djava.library.path=/home/modernmt/Downloads/mmt/build/lib eu.modernmt.cli.CleaningPipelineMain -s en -t ar --output /home/modernmt/Downloads/mmt/runtime/default/tmp/training/clean_tms --input /home/modernmt/Downloads/mmt/examples/data/train' failed with exit code 1
`

**Comment by memoday** [comment]
If the above is not clear, you may check this on codeshare

https://codeshare.io/5wnvlR

**Comment by davidecaroselli** [comment]
so, it seems that (at least) one of your TMX files is corrupted. Unfortunately from the log is not clear which one is it, can you please run the training on one TMX at time (just create a folder for each TMX) and see which one is causing the problem?

You can ctrl+c the training as soon as it passes the TMX cleanup step, that will ensure the validity of the TMX file.

**Comment by memoday** [comment]
Thanks David for your reply. I tested it with one tmx and it threw the same error. There could be something wrong with the Arabic tmx I am using, but how come it threw the same exact error when I try to create the en>it engine with the supplied files that exist under "examples/data/train".

**Comment by memoday** [comment]
Hi David,

I installed MMT on a new Ubuntu server, not a virtual machine, with 8 GB of Ram and 5 GB hard disk and I copied a totally new tmx that I know it's good, but I am getting the same exact error.

**Comment by davidecaroselli** [comment]
Hi Mohamed,

I suspect the problem could be with the encoding of the TMX. Run this command:
```bash
file --mime your/tmx/file.tmx
```
If the output is not `charset=utf-8`, then convert the file in utf-8 like so:
```bash
iconv -f <charset_from_file_command> -t utf-8 your/tmx/file.tmx > your/tmx/utf8file.tmx
```
For example, `file` return `utf-16` you will run:
```bash
iconv -f utf-16 -t utf-8 example.tmx > utf8example.tmx
```
Then check if the first line of your TMX is:
```xml
<?xml version='1.0' encoding='utf-8'?>
```
**Important**: there must be no leading characters before `<?xml version='1.0' encoding='utf-8'?>`, if there are any, just delete them.

Let me know if this solve the issue!

**Comment by memoday** [comment]
Hi David,

Thanks for your input. I now followed this instruction on a new TM file and the first output I got matches what you mentioned:

`UN_fixed.tmx: application/xml; charset=utf-8` 

I ran the training command and it worked for a while, at least it passed step 1, but it failed again in step 2 "corpora processing....". The fail exit code is not 1 though, but exit code -6. Here is the new output:

`root@ubuntu:~/mmt# ./mmt create en ar examples/data/train

=========== TRAINING STARTED ===========

ENGINE:  default
BILINGUAL CORPORA: 1 documents
MONOLINGUAL CORPORA: 0 documents
LANGS:   en > ar

INFO: (1 of 7) TMs clean-up...                                         DONE (in 4s)
INFO: (2 of 7) Corpora preprocessing...                                DONE (in 1m 56s)
ERROR Unexpected exception:
        Command 'java -cp /root/mmt/build/mmt-0.14.1.jar -Dmmt.home=/root/mmt -Djava.library.path=/root/mmt/build/lib eu.modernmt.cli.TrainingPipelineMain -s en -t ar -v /root/mmt/engines/default/models/vocabulary --output /root/mmt/runtime/default/tmp/training/preprocessed --input /root/mmt/runtime/default/tmp/training/training_corpora --dev /root/mmt/engines/default/data/dev --test /root/mmt/engines/default/data/test' failed with exit code -6
Traceback (most recent call last):
  File "./mmt", line 549, in <module>
    main()
  File "./mmt", line 526, in main
    actions[command](args)
  File "./mmt", line 357, in main_create
    debug=args.debug, steps=args.training_steps, split_trainingset=args.split_corpora)
  File "/root/mmt/cli/engine.py", line 237, in build
    (self._engine.data_path if split_trainingset else None), log=logger.stream)
  File "/root/mmt/cli/mt/processing.py", line 148, in process
    shell.execute(command, stdout=log, stderr=log)
  File "/root/mmt/cli/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
cli.libs.shell.ShellError: Command 'java -cp /root/mmt/build/mmt-0.14.1.jar -Dmmt.home=/root/mmt -Djava.library.path=/root/mmt/build/lib eu.modernmt.cli.TrainingPipelineMain -s en -t ar -v /root/mmt/engines/default/models/vocabulary --output /root/mmt/runtime/default/tmp/training/preprocessed --input /root/mmt/runtime/default/tmp/training/training_corpora --dev /root/mmt/engines/default/data/dev --test /root/mmt/engines/default/data/test' failed with exit code -6`

In case the above is not clear, please see this: https://codeshare.io/G787d1

Hope we find a solution for this. 

Thanks

**Comment by davidecaroselli** [comment]
Ok, first step solved, let's see next: can you please post the file runtime/<engine-name>/logs/training.log? (Just drag and drop it here)

**Comment by memoday** [comment]
Please find it enclosed. I had to add '.txt' to the extension because '.log' it not accepted on gihub. 
Thanks again for your great support and follow-up.

[training.log.txt](https://github.com/ModernMT/MMT/files/800068/training.log.txt)

**Comment by davidecaroselli** [comment]
Hi @memoday 

sorry for the delay but I've been out-of-office. So, looking at the logs it seems that your hitting a problem with the native library.
We already observed that with other users: basically the problem is the different hardware configuration of you machine. Nothing impossible to solve, of course!

What I would suggest is to follow the instruction for [Installing MMT from source](https://github.com/ModernMT/MMT/blob/master/INSTALL.md#option-3---installing-from-source-for-contributors). If you compile the whole MMT on your machine, it will be optimized for your hardware and you should solve the problem.

Please, let me know any updates.

Cheers,
Davide

**Comment by memoday** [comment]
Thanks a million, David and sorry for bothering you during your time-off. 

I will follow the instructions and let you know. I hope this will resolve the issue.

I will report back if this resolves the issue so other users know. 

Thanks again for your great support.

**Comment by davidecaroselli** [comment]
No problem! :)
Thanks.

**Comment by memoday** [comment]
Hi David,

I confirm that installation from source on Ubuntu 16.04 works just fine :-). 

On Ubuntu VirtualBox image, I got a kafaka error, but I believe it's a memory issue with VB image.

Thanks a million David for your support. I appreciate it. 

Any idea when you plan to create interface or a plugin for main translation memory tools like Trados or MemoQ. Also, what about an interface to MateCat?

Thanks again for the all the work you do. You are really reshaping the language technology. 

My best wishes and greetings to your team.

Kind regards,
Mohamed Zeid

**Comment by memoday** [comment]
One last thing: 

This command won't work on Ubuntu 16.04 

`sudo apt-get install libbz2-dev libboost1.55-all-dev libsparsehash-dev cmake openjdk-8-jdk git maven`

The problem lies in 'libboost1.55-all-dev', so I had to replace it with the following and it worked just fine.

`sudo apt-get install libbz2-dev libboost-all-dev libsparsehash-dev cmake openjdk-8-jdk git maven`

**Comment by davidecaroselli** [comment]
Hi @memoday 

thank you very much for the support, it's really appreciated :)
Regarding CAT tools integration, we have good news: MMT is currently integrated into the [MyMemory Plugin for Trados](http://appstore.sdl.com/app/mymemory/337/). If you activate **MyMemory<sup>PRO</sup>**, you will receive MT coming directly from our MMT servers.

We currently support 3 language pairs: EN > FR, EN > ES and DE > EN.

More CAT tool integrations are coming in the next months: MateCat will probably be the next so, stay tuned!

Thanks  again for your support, if you need any other infos please don't hesitate to contact me.
Davide
