### ISSUE TITLE
phrase table dump

### ISSUE THREAD

**Issue by vince62s** [ModernMT/MMT#234]
Is there an easy way to dump the phrase tables as we can do / look at in Moses ?

**Comment by davidecaroselli** [comment]
**Yes, but you won't find what you expect.**

ModernMT uses SuffixArrays-PhraseTable which are a powerful implementation that allow us to build adapted PhraseTable just-in-time.

You can inspect the data structure with the two binaries in `ModernMT/build/bin`: `sapt_dump_index` and `sapt_dump_corpus`.

**Comment by davidecaroselli** [comment]
I close this issue for now, if you have any other questions please feel free to re-open it. Thanks!
