### ISSUE TITLE
Help needed with brower syntax

### ISSUE THREAD

**Issue by letconex** [ModernMT/MMT#235]
I managed to finally install from source, resolve dependencies for libboost.
I created an engine namen Skoda, pair language de-ro.
I can query it în the browser with:
http://192.168.0.104:8045/translate?q=Das Fahrzeug ist schwer
The server response is
{"status":200,"data":{"translation":"Autovehiculul este greu","decodingTime":135,"sourceWordCount":4,"targetWordCount":3}}
because it is a perfect match from the aligned texts.
The query
http://192.168.0.104:8045/domains/
responds
{"status":200,"data":[{"id":1,"name":"Skoda"}]}
I need your help, please, with the syntax for adding other translations to the engine.
I tried:
http://192.168.0.104:8045//domains/:1/Skoda?source=Hallo&target=Salut
and
http://192.168.0.104:8045/domains/:id/corpus/add?source=Hallo&target=Salut
but server response:
{"status":404}
I am sure I got the syntax wrong, please **help me with the right syntax** to add some translations directly from the browser.
It would be much appreciated if you could point me also to the right syntax to add a tmx file from the Windows host system.

**Comment by nicolabertoldi** [comment]
this should be the right call to add one sentence pair.

curl -X PUT http://192.168.0.104:8045/domains/1/corpus -d “source=Hallo" -d “target=Salut”

or alternatively
curl -X PUT http://192.168.0.104:8045/domains/1/corpus?source=Hallo&target=Salut

**Comment by letconex** [comment]
Thank you very much for  the quick answer
The first one works
{"status":200,"data":{"id":"80000001-0000-0001-0000-000000000008","domain":1,"size":1,"begin":8,"end":8,"dataChannel":1,"progress":0.0}}l
The second gets response
{"status":400,"error":{"type":"ParameterParsingException","message":"Missing parameter target"}}
I tried to put
http://192.168.0.104:8045/domains/1/corpus?source=Hallo&target=Salut
directly in the browser, but the answer is
{"status":404}

**Comment by AndRossi** [comment]
Hi @letconex 

I think the main problem is you are trying to add more translations to the engine through a browser. Browsers can only perform GET HTTP requests, whereas if you want to add new translations it is necessary to write a PUT HTTP request.

To send PUT requests you can use your command line as @nicolabertoldi  suggested: curl is a powerful tool that lets you use various web protocols to send messages. including HTTP PUT requests. It is definitely the best option in Unix-based environments, however I don’t think curl is installed by default in Windows systems.

If you are looking for a more user friendly experience, you can try [Postman](https://www.getpostman.com/ ).
It’s a free tool that provides a really intuitive interface.

I also send you the [our collection of MMT APIs for Postman](https://github.com/ModernMT/MMT/files/833575/ModernMT.API.postman_collection.json.zip) .
It’s a collection of mockups for all HTTP requests you can use in MMT; you can import them in Postman so you don’t have to write messages from scratch each time :)  

If you need more information or some examples, you can consult our [Wiki page](https://github.com/ModernMT/MMT/wiki/API-Add-to-Domain) .



To send TMX files to an engine, the HTTP PUT request is exactly the same as for single words, except you don’t need to use the source and target attributes.
Instead you will use the content attribute with your TMX file, and use the content-type attribute as “tmx”.

If you need more help don’t hesitate to write me.

**Comment by cattoni** [comment]
Hi @letconex 

Try to quote the whole string ecoding the URL with parameters:

`curl -X PUT 'http://192.168.0.104:8045/domains/1/corpus?source=Hallo&target=Salut'`

Without quoting the char ampersend '&' is interpreted as background instruction by the shell and can be "lost" ...

**Comment by letconex** [comment]
To AndRossi: thank you very much, I will try using curl or postman. I will post here if any problems appear.
To cattoni: Thank you very much, yes, it worked with the quote signs '
but only for single words, when entering
curl -X PUT 'http://192.168.0.104:8045/domains/1/corpus?source=Hallo Welt&target=Salut lume'
nothing happens, I guess because of the spaces.

**Comment by cattoni** [comment]
Hi @letconex 

Yes, the problem are the spaces.
Not all the characters are allowerd in URL strings.
In the above example you can simply substitute each space with a '+' char, but in general a string should be URL-encoded in order to work inside a curl invocation.

So the example above should work in the following way:
`curl` -X PUT 'http://192.168.0.104:8045/domains/1/corpus?source=Hallo+Welt&target=Salut+lume'

To URL-encode a string there are many tools, depending on the programming language you are using.

**Comment by letconex** [comment]
Thank you both for the great support. If I have further questions about it, I will contact you soon.

I have another questions, should I open another issue for it?
I added the segment "Hallo Frauen" with the translation "Salut femei", which means "Hello women"
Even though I added it, when sending a translate query without context
http://192.168.0.104:8045/translate?q=Hallo Frauen
the answer is "Salut însărcinate", which means "Hello pregnants".
But when providing the context "Skoda" or "Frauen"
http://192.168.0.104:8045/translate?q=Hallo%20Frauen&context=Frauen
the answer is correct, that is "Hello women"
Why does it happen? I thought a directly added segment would take precedence over another "fuzzy" segment from the corpus. Is there any way to prioritize segment translations with no context, in this case to get the right translation without providing context?

**Comment by AndRossi** [comment]
MMT has much better performances when using a context, so it is not surprising that when you submit a context you get a better answer :)

More in detail, when you manually add a new translation source after the initial training, you also specify the domain you want to add it to. 

The importance of manually added sources is currently considered as the same as the rest of the domain it belongs to (so at the moment, from that point of view, it has no higher priority, as you say). 

However, as the context matches that domain, the importance of all that domain is boosted so your added source gets higher priority over the translation data in other domains.

**Comment by letconex** [comment]
_Thank you very much for your answers_, this is a really great support, because the documentation on the website is a little bit scarce.
When adding a translation segment with curl or with the ./mmt add, is there any way to specify appending or overwriting a previous translation unit? That is, you add a a new translation or you already have a translation, then you want to **correct/overwrite** it or **to add** **another different variant** (for instance for multiple translations). Are there any arguments for **overwriting or appending**? If not, how is the current behaviour now, does the software append or overwrite previous translations?

**Comment by AndRossi** [comment]
HI @letconex, you’re welcome :)
At the moment it is only possible to append a new translation (and this is indeed the default behaviour).

**Comment by AndRossi** [comment]
I close this issue for now.
However, if you need some more support or encounter problems, don't hesitate to re-open it! 
Thanks :)
