### ISSUE TITLE
How to extend an already-built engine?

### ISSUE THREAD

**Issue by memoday** [ModernMT/MMT#237]
Hi David,

I am wondering if there is a way to train more tmx or bilingual files and add them to an already trained engine? How can this be achieved?

Thanks,
Mohamed

**Comment by letconex** [comment]
https://github.com/ModernMT/MMT/wiki/API-Add-to-Domain

**Comment by nicolabertoldi** [comment]
The current example refers explain how to add a single sentence pairs.

I would suggest to add more details and an example to clarify how to add an entire file in TMX format.

**Comment by AndRossi** [comment]
Hi @memoday, 

Yes, you can execute the ./mmt import command to upload a TMX to your model under a certain domain. The command syntax is:
**./mmt import -d <domain_name> -x <tmx_file_path> -e <engine_name> -p<api_port>**
(where as usual engine name and api port have default values "default" and 8045 respectively)

However it is also possible to upload a TMX file through the REST APIs, too, i.e. using curl and sending the TMX with form encoding.

@nicolabertoldi 
I think you are right, that wiki page can be expanded with a TMX upload example.
I'll take care of that :)

**Comment by letconex** [comment]
Thank you, AndRossi, can you please also provide the right syntax for doing this with the API?

**Comment by AndRossi** [comment]
Hi @letconex, sure. Here is the syntax:

**curl -X PUT -H "Content-Type: multipart/form-data" 
                    -F "content=@<path_to_your_tmx> 
                    -F "content_type=tmx" http://localhost:8045/domains/<your_domain_id>/corpus 
| python -mjson.tool**

Please note that this command uploads the tmx to an already existing domain.
If you want to upload it on a new domain, first create the new domain with command:

**curl -X POST http://localhost:8045/domains -d "name=<new_domain_name>" | python -mjson.tool**

Then check which ID was assigned to the new domain, and finally use the curl -X PUT command above.

**Comment by AndRossi** [comment]
@nicolabertoldi 
I have just updated the wiki [wiki page] (https://github.com/ModernMT/MMT/wiki/API-Add-to-Domain) with an example of TMX file upload.
I think it is clearer now.
