### ISSUE TITLE
branch "develop" out of order?

### ISSUE THREAD

**Issue by cattoni** [ModernMT/MMT#243]
Hi @AndRossi and @davidecaroselli 

I'm trying to install and use the last commit of branch "develop"(f151a390e2d486d918d6a7d5827e2eef23443d4a) that presents these problems:

1. file vendor/Makefile is missing
2. file setup.py is missing
3. after copying the above two files from "master" branch and successfully compiling, the example command
`./mmt create en it examples/data/train`
fails at LM steps with the error:
```
INFO: (6 of 7) Language Model training...                              DONE (in 0s)
ERROR Unexpected exception:
	Command '/datadrive/data/MMT_v0_15_1/ModernMT/build/bin/create_slm --discount_fallback -o 5 --model /datadrive/data/MMT_v0_15_1/ModernMT/engines/default/models/decoder/lm/background.slm -S 79% -T /datadrive/data/MMT_v0_15_1/ModernMT/runtime/default/tmp/training/lm/slm.temp --prune 0 0 1' failed with exit code 1

```

Which commit of "develop" should I use?

Thanks,

  Roldano

**Comment by AndRossi** [comment]
Hi @cattoni,

In the develop branch we have replaced the makefile and setup.py files with a a single executable file "build" that is located in the "vendor" folder.

I think that if you use that file instead of the old makefile and setup.py everything should work just fine and 3rd issue you mention should disappear as well. 

Let me know! :)

Andrea

**Comment by cattoni** [comment]
Thanks @AndRossi 

Unfortunately the problem 3 persists (same error message)


The new sequence of command I issued was:

```
git clone https://github.com/ModernMT/MMT.git ModernMT
cd ModernMT
git submodule init
git submodule update
cd vendor
build
cd ../src
mvn clean install
cd ..

```

By the way I would suggest to update the INSTALL.md  with the new sequence otherwise contributors can get confused -- I can do this change and commit (after confirmation that the above sequence is correct :-)

Best

  Roldano

**Comment by davidecaroselli** [comment]
Hi @cattoni 

I'm currently working on `develop` branch, it will be ready by the end of the day. I'll keep you updated!

**Comment by cattoni** [comment]
FIne, I wait.
Thanks to both @AndRossi and @davidecaroselli

**Comment by davidecaroselli** [comment]
@cattoni `develop` branch has been fixed, @AndRossi will also update the documentation as soon as we merge it into `master`.

Thanks for your patience! ;)

**Comment by cattoni** [comment]
Thanks, I confirm it works now
:-)
