### ISSUE TITLE
mmt create: missing check of same number of lines of src/tgt in a bilingual corpus

### ISSUE THREAD

**Issue by cattoni** [ModernMT/MMT#245]
By mistake I've created, tuned and evaluated an engine starting from a medium-size bilingual corpus in which the number of src lines were different from the number of tgt lines.

I've detected the mistake only because the engine performance was extremely poor.

I would be helpful and time-saving if "mmt create" could detect such situation and exit reporting an error, without creating the engine.

**Comment by davidecaroselli** [comment]
Working on it! :)

**Comment by davidecaroselli** [comment]
Fix pushed on `develop` branch. It will be merged into `master` as soon as we fix some issues we found in `develop`.

Thanks Roldano!
