### ISSUE TITLE
Documentation images

### ISSUE THREAD

**Issue by AndRossi** [ModernMT/MMT#246]
Hi everyone, 

This is not a real issue. I'm writing some wiki pages and it seems that there is no way to just upload local images from my computer: to add an image to a page, Github markdown editor needs its URL.

It looks like the only way I can get Github to give images an URL without pushing them into our repo is to post them in an issue (when I found out about this I was like "What? Seriously?")

Anyway, here are the images.
Feel free to post here all the images you want to add to our documentation, wiki, etc.

![leader-followers-cluster](https://cloud.githubusercontent.com/assets/6909990/25183771/d2b034fe-2518-11e7-8847-30bdc93a184e.png)
![p2p-cluster](https://cloud.githubusercontent.com/assets/6909990/25183772/d2cb7c6e-2518-11e7-9469-fcb9209af89d.png)
![single-node](https://cloud.githubusercontent.com/assets/6909990/25183773/d2da241c-2518-11e7-9986-bd471bf0b148.png)

**Comment by AndRossi** [comment]
![blank diagram - page 1](https://user-images.githubusercontent.com/6909990/28910648-0adf2ff2-782e-11e7-9203-014d4d0113b3.png)

**Comment by davidecaroselli** [comment]
![modernmt-c-128](https://user-images.githubusercontent.com/1674891/43786026-f2043344-9a67-11e8-8434-27c324c37214.png)
