### ISSUE TITLE
option to skip the MMT default preprocessing step

### ISSUE THREAD

**Issue by cattoni** [ModernMT/MMT#248]
Sometimes users have their own preprocessing chain and prefer to use it instead of the MMT default preprocessing.

In such cases an option to skip the preprocessing step in "mmt create|tune|evaluate|translate" would be very useful: in this case it is up to the user to provide the preprocessed data to mmt.

**Comment by AndRossi** [comment]
Hi @cattoni, 

I think it is already possible.  
`mmt create` supports a --steps option that lets you specify the training steps you'd like to perform, letting you skip the others.

Is this what you meant?

Andrea

**Comment by davidecaroselli** [comment]
Hi @cattoni 

Removing the whole preprocessing is not possible in MMT because lot of steps od preprocessing are necessary in order to translate and post-process (i.e. from words to vocabulary ids and back).

What is however possible is to add a flag in order to "skip" tokenization: if you have an already whitespace-tokenized text, we could skip our custom tokenization step simply by splitting tokens on whitespaces.

Is this something that could work for you?

**Comment by cattoni** [comment]
Hi @davidecaroselli and @AndRossi 

Skipping tokenization appears ok.

The example I have relates to Arabic: the preprocessing tool basically performs tokenization and adds some punctuation (e.g. commas); probabilly it substitutes arabic chars corresponding to puncutations with ASCII punctuation chars but I'm not sure -- I don't know Arabic :-)
Is this ok for mmt?

Another issue concerns the source and target languages: is it possible to skip only a language (e.g. source)?
In the example of Arabic-to-English, I would be nice to skip the tokenization for Arabic only, and keep the mmt default tokenization for English (which is ok).

**Comment by davidecaroselli** [comment]
making normalizations is perfectly ok only if you apply such normalization and tokenization to **all** Arabic text (training, evaluation, tuning ecc...).

For the English tokenization, I suggest to run MMT preprocessing standalone on training corpora like so:
```
cat path/to/file.en | java -cp build/mmt-1.0.jar eu.modernmt.cli.PreprocessorMain --lang en > path/to/tokenized-file.en
```

**Comment by cattoni** [comment]
> making normalizations is perfectly ok only if you apply such normalization and tokenization to all Arabic text (training, evaluation, tuning ecc...).

Sure -- that's the reason why the option to skip preprocessing/tokenization should be present in all mmt sub-commands (create, tune, evaluate, translate).


> For the English tokenization, I suggest to run MMT preprocessing standalone on training corpora like so:
> `cat path/to/file.en | java -cp build/mmt-1.0.jar eu.modernmt.cli.PreprocessorMain --lang en > path/to/tokenized-file.en`
> 

Thanks for the useful command.
Does this mean that the skip-preprocessing/tokenization option will impact both sides (source and target)?

**Comment by davidecaroselli** [comment]
I'm closing this issue for long time inactivity. We won't actively work on it for the moment.
MMT relies on its own processing pipeline and cannot be disabled. However it is still possible:

- Skip preprocessing step during training with the `-s` option.
- Add custom pre/post processor to the pipeline for custom development.

Thanks!
