### ISSUE TITLE
mmt evaluate: reported error difficult to understand

### ISSUE THREAD

**Issue by cattoni** [ModernMT/MMT#250]
This is a minor issue.

By mistake I've tried to evaluate an engine providing a directory containing a non-matching bilingual corpus (i.e. a source file only, without the corresponding target file).

The reported error:

```
Testing on 4971 lines:

Preparing corpora...                                                   DONE (in 0s)
ERROR Unexpected exception:
	TypeError('coercing to Unicode: need string or buffer, NoneType found',)

```
is difficult to understand (it looks like an encoding problem); it took me some time to realize the reason of the problem (i.e. the missing target file).

I would be helpful if "mmt evaluate" could detect and report situations like this.

**Comment by davidecaroselli** [comment]
Hi @cattoni 

we just pushed a fix for both "mmt evaluate" and "mmt tune".

Thanks for your report!
