### ISSUE TITLE
What is the best safe upgrade path to latest release and how to backup built engines?

### ISSUE THREAD

**Issue by mzeidhassan** [ModernMT/MMT#252]
Hello MMT team,

I hope it's all well with you.

I see that you released a new version a week or so ago. What would be the best safe upgrade path? 

Is there also a way to backup the current engine(s) for reuse , in case something wrong happened during update? 

I couldn't find any relevant info in the wiki page, so you may need to update it.

Thanks,
Mohamed

**Comment by AndRossi** [comment]
Hi @mzeidhassan 
The upgrade process mainly depends on your current MMT version.
What is the version of your engines?

As for the upgrade documentation, some info on the backward compatibility can be found in the release page, but apart from that you are right: the wiki pages do not contain any relevant data on the upgrade path yet.
I'll make sure to update the wiki! :)

Thanks,
Andrea

**Comment by mzeidhassan** [comment]
Hi Andrea,

I have version 1.0.1. I installed it from source. I have just used the command "git pull origin master", but for some reason, the engine doesn't start.  It starts with this line 'Starting MMT engine 'default'...' and it takes forever. If i press "CRTL +C" to interrupt the operation, I get this message:
Unexpected exception:
        OSError(2, 'No such file or directory')

So. I am not sure why. Any idea?

Yes, update the wiki page will be a great contribution. 

Thanks Andrea for your support!
Mohamed

**Comment by cattoni** [comment]
Hi @mzeidhassan 

I think Andrea's question concerns the version with which you created the engines -- not the new version you installed.
Not all the engines created with old versions can be ported to the new version 1.0.1.
If I remember correctly, only engines created with version >= 0.15.1 can be ported to the new version 1.0.1 -- but @AndRossi can provide more precise info.

**Comment by AndRossi** [comment]
Hi @mzeidhassan,
Yes, as @cattoni mentioned I meant the MMT version you used to create your engines.

However I have created [a new wiki page](https://github.com/ModernMT/MMT/wiki/Upgrading-MMT) that explains in detail how to upgrade your MMT software and engines.
I hope it is useful!

Let me know if you manage to upgrade those engines, and for any doubt or suggestion don't hesitate to ask.

Thanks, 
Andrea

**Comment by mzeidhassan** [comment]
Thanks cattoni and thanks Andrea!

The new wiki page saved me from doing the whole thing from scratch. My engine is working fine now and it's all set. 

Thanks a million for your great support, Andrea!

Kind regards,
Mohamed

**Comment by AndRossi** [comment]
Hi @mzeidhassan,
I'm so glad the new wiki page was useful!
I'm closing this issue now, but for any problem or question feel free to reopen it.

Have a wonderful day!
Andrea
