### ISSUE TITLE
Early Stopping Criterion for Mert

### ISSUE THREAD

**Issue by cettolo** [ModernMT/MMT#254]
Since often the tuning stage (MERT) is too expensive in terms of time wrt the benefits in terms of final translation quality, it would be worty to investigate on early stopping criteria, for example by checking the trend of the BLEU score on the development set instead of looking only at the changes of weight values or of the BLEU score got by rescoring the n-best lists.

**Comment by cettolo** [comment]
Quick update
I added to mert-moses.perl an early stopping criterion based on the comparison between the BLEU score on the development set at the current iteration and the mean of the scores in a window of previous iterations. By setting properly the score difference threshold and the history window size, on 14 IWSLT 2017 tasks (language pairs) I observed the following behaviour wrt the previous version without the new criterion:
- number of MERT iterations: (mean=6.1, min=3, max=10) vs. (mean=9.9, min=3, max=20)
- average loss in BLEU score on test sets: absolute(0.02, min=-0.20, max=+0.16), percentage(0.10%, min=-1.24%, max=+0.63%)
Of course, it is possible to save even more iterations, at the cost of higher losses.
Likely, this novel additional stopping criterion deserves to be committed. Before doing it, I'm going to further assess it on more problematic IWSLT pairs for MERT (like Japanese-English and Chinese-English) and other benchmarks.

**Comment by cettolo** [comment]
Two setups of the early stopping criterion have been devised, the **default** and the **fast** (more aggressive). The experiments on 26 IWSLT 2017 language pairs say that wrt the MERT without such an additional criterion:

- default setup:
-- average number of MERT iterations: from 9.5 to 5.4 (-43%)
-- range of number of MERT iterations: from [3,25] to [3,10]
-- absolute BLEU score loss: average=0.03, max=0.88 (on one Japanese-English test set)

- fast setup:
-- average number of MERT iterations: from 9.5 to 3.9 (-59%)
-- range of number of MERT iterations: from [3,25] to [3,7]
-- absolute BLEU score loss: average=0.15, max=0.88 (as above)

Note that the most problematic pair is the Japanese-English, for which the saving of 15 MERT iterations (from 22 to 7) in both setups is paid with an absolute BLEU degradation of 0.88 and 0.60 on the two test sets.

**Comment by davidecaroselli** [comment]
Hi @cettolo 

given the fact that the max loss in BLEU is exactly the same in both cases I'm wondering if the best option could be to have a `default` behaviour that acts like your suggested "fast setup", while adding a flag `--best-performance` that completely disable such criterion and give us the old best-quality long-time consuming MERT process.

What do yo think?

**Comment by cettolo** [comment]
Even if the max is the same, the fast setup is definitely less safe; here, the top 10 losses in the two cases:
-- fast: 0.88 0.80 0.71 0.60 0.59 0.55 0.48 0.47 0.46 0.45
-- default:      0.88 0.60 0.60 0.27 0.17 0.15 0.15 0.11 0.10 0.10

If you accept by default a loss of 0.3 BLEU points in half of the cases, go on with the switch between the two setups, otherwise keep the safer setup as the default

**Comment by davidecaroselli** [comment]
@cettolo 
I have just pushed your work on the **master** branch. Now `mmt tune` supports the `--accuracy` option, possible values are:
- `default`: it's your "default" setup, best trade-off
- `best`: old-plain MERT process for best performances but slowest process
- `fast`: it's your "fast" setup, super-fast MERT, not optimized for translation quality

Thanks!
