### ISSUE TITLE
Feature request : predictive translation server

### ISSUE THREAD

**Issue by EtienneAb3d** [ModernMT/MMT#256]
It would be a great evolution if the translation server would accept an extra "begining" parameter for a sentence, to return with one (or N) possible way(s) of ending its translation. If MMT is using a beam search, I think this could be done by forcing the first tokens in the beam search.. right ?

A bit harder would be to get a predictive post-editing server = knowing a sentence to translate, and an already existing translation with a pointed position in it (or a "begining" and an "ending" parameter), in the beam search force all beginning and ending tokens, and let free exploration to fill the pointed position at best. The hard part is certainly to force the ending tokens in the beam search. The above proposition of predictive translation server would be equivalent to set the pointed position at the end of the translation in this predictive post-editing server.

**Comment by EtienneAb3d** [comment]
DeepL did it : its editable target zone (with the keyboard, not only the mouse), is absolutely incredible ! Word completion and sentence auto-rewriting !
Wonderful !

**Comment by davidecaroselli** [comment]
Hi @EtienneAb3d

Sorry for the late reply. Unfortunately all our effort right now is focused on delivering our new *Neural Adaptive and Incremental Machine Translation* (preview is available in our branch **features/neural_decoder**).

Being MMT tailored for professional CAT tools, like Trados or MateCAT, we want to deliver an MT server that has as priorities the context-adaptivity and the ability to quickly include user feedback in the loop, and this is a new challenge with Neural.

Nevertheless I truly understand that there could be different scenarios where what you suggest can be very helpful. If you are interested in the development of such feature, we could discuss the custom development directly by email: feel free to contact me privately.

Thank you and, as always, if you have any other question please don't hesitate to post it here!

**Comment by EtienneAb3d** [comment]
> Nevertheless I truly understand that there could be different scenarios where what you suggest can be very helpful.

Did you try DeepL, with its editable translation zone, as said in my previous post ? All is there, exactly as I expected... nice demonstration !
https://www.deepl.com/translator
;-)

**Comment by davidecaroselli** [comment]
Yes, I tried and I see what you mean.
Just as I said, that is an interesting feature for what their proposing. Our main focus is on professional translators using CAT tools, this means that we are building our engine with a different pattern in mind, different use cases and even different input. It's just a matter of priorities, and resources.

Again, if you had evidence of the quality of an MMT engine adapted to Translator's TMs and corrections, and you are interested into expanding the functionalities of MMT, we will really appreciate pull requests or any other kind of support.

Thanks for your support!
Davide

**Comment by EtienneAb3d** [comment]
Of course, you don't have to justify about your priorities. Since you just closed this request, I understand that it won't ever be in your road-map...
Thanks for your work.

**Comment by davidecaroselli** [comment]
Yes, in the short term we don't expect to have this feature implemented, if it's not an external contribution.
I am not justifying, I'm saying what you can expect from this project, and which are its goals and why, even if you find this feature so interesting, it's not in our roadmap right now.

But roadmaps can change, so, again, if you have any other suggestions, please don't hesitate to add more here and we will re-open the issue.

Thanks!
