### ISSUE TITLE
option '--resume' broken?

### ISSUE THREAD

**Issue by nicolabertoldi** [ModernMT/MMT#259]
it seems that the options '--resume' does not work as expected

even if I use it, the training restart from the first step

**Comment by davidecaroselli** [comment]
Hi @nicolabertoldi 
can you please provide some more info on how to replicate the bug? I tried the resume option and it seems  to work correctly:

```bash
$ ./mmt create en it examples/data/train/

=========== TRAINING STARTED ===========

ENGINE:  default
BILINGUAL CORPORA: 3 documents
MONOLINGUAL CORPORA: 0 documents
LANGS:   en > it

INFO: (1 of 6) TMs clean-up...                                         DONE (in 1s)
INFO: (2 of 6) Corpora pre-processing...                               DONE (in 2s)
INFO: (3 of 6) Context Analyzer training...                           ^C
Traceback (most recent call last):
  File "./mmt", line 730, in <module>
    main()
[...]
KeyboardInterrupt

$ ./mmt create en it examples/data/train/ --resume

=========== TRAINING STARTED ===========

ENGINE:  default
BILINGUAL CORPORA: 3 documents
MONOLINGUAL CORPORA: 0 documents
LANGS:   en > it

INFO: (1 of 6) TMs clean-up...                                         DONE (in 0s)
INFO: (2 of 6) Corpora pre-processing...                               DONE (in 0s)
INFO: (3 of 6) Context Analyzer training...                            DONE (in 1s)
INFO: (4 of 6) Aligner training...                                     DONE (in 6s)
INFO: (5 of 6) Translation Model training...                           DONE (in 3s)
INFO: (6 of 6) Language Model training...                              DONE (in 2s)

=========== TRAINING SUCCESS ===========

You can now start, stop or check the status of the server with command:
	./mmt start|stop|status 
```

**Comment by nicolabertoldi** [comment]
Strange behavior...

The first time I run 
$> ./mmt create en it examples/data/train/ --neural 

=========== TRAINING STARTED ===========

ENGINE:  default
BILINGUAL CORPORA: 3 documents
MONOLINGUAL CORPORA: 0 documents
LANGS:   en > it

INFO: (1 of 7) TMs clean-up...                                         DONE (in 0s)
INFO: (2 of 7) Corpora pre-processing...                               DONE (in 1s)
INFO: (3 of 7) Context Analyzer training...                            DONE (in 1s)
INFO: (4 of 7) Aligner training...                                     DONE (in 2s)
INFO: (5 of 7) Creating translation memory...                          DONE (in 1s)
INFO: (6 of 7) Preparing training data...                              DONE (in 32s)
INFO: (7 of 7) Neural decoder training...                               ^C

and I interrupted during Neural decoder Training.

then I rerun the same command with the additional "--resume" option
$>  ./mmt create en it examples/data/train/ --neural --resume

=========== TRAINING STARTED ===========

ENGINE:  default
BILINGUAL CORPORA: 3 documents
MONOLINGUAL CORPORA: 0 documents
LANGS:   en > it

INFO: (1 of 7) TMs clean-up...                                         DONE (in 0s)
INFO: (2 of 7) Corpora pre-processing...                               DONE (in 1s)
INFO: (3 of 7) Context Analyzer training...                            DONE (in 1s)
INFO: (4 of 7) Aligner training...                                     DONE (in 3s)
INFO: (5 of 7) Creating translation memory...                          DONE (in 1s)
INFO: (6 of 7) Preparing training data...                              DONE (in 32s)
INFO: (7 of 7) Neural decoder training...                             

In this case, the recreation of the engine restart from scratch, without re-using any previous step.


But if I do similarly but interrupting the creation during step 6/7 "Preparing training data"
$> ./mmt create en it examples/data/train/ --neural 


=========== TRAINING STARTED ===========

ENGINE:  default
BILINGUAL CORPORA: 3 documents
MONOLINGUAL CORPORA: 0 documents
LANGS:   en > it

INFO: (1 of 7) TMs clean-up...                                         DONE (in 0s)
INFO: (2 of 7) Corpora pre-processing...                               DONE (in 1s)
INFO: (3 of 7) Context Analyzer training...                            DONE (in 1s)
INFO: (4 of 7) Aligner training...                                     DONE (in 2s)
INFO: (5 of 7) Creating translation memory...                          DONE (in 1s)
INFO: (6 of 7) Preparing training data...                         ^C

and then resume
$> ./mmt create en it examples/data/train/ --neural --resume

=========== TRAINING STARTED ===========

ENGINE:  default
BILINGUAL CORPORA: 3 documents
MONOLINGUAL CORPORA: 0 documents
LANGS:   en > it

INFO: (1 of 7) TMs clean-up...                                         DONE (in 0s)
INFO: (2 of 7) Corpora pre-processing...                               DONE (in 0s)
INFO: (3 of 7) Context Analyzer training...                            DONE (in 0s)
INFO: (4 of 7) Aligner training...                                     DONE (in 0s)
INFO: (5 of 7) Creating translation memory...                          DONE (in 0s)
INFO: (6 of 7) Preparing training data...                              DONE (in 32s)


the first 5 steps are correctly skipped


Hence, I suppose that there is something in step 6/7 which probably breaks the resuming policy.

**Comment by davidecaroselli** [comment]
In the new *neural* training, as we have agreed, you can interrupt the training with Ctrl+C and the engine will be completed with the last available epoch data.

So the training is considered successfully completed and a new training will be always run from the beginning.

**Comment by nicolabertoldi** [comment]
Actually, the step 6 (out of 7) is not the real neural training (step 7/7).

In other words, if you CTRL-C the process during step 6, you do not have any model to use.
so the resuming is still important.

One more point.
Assuming to fix this issue,
what happens if you CTRL-C the process during the first iteration of the training?
the model.pt <http://model.pt/> does not exist because it is is created at the end of each “epoch”

**Comment by davidecaroselli** [comment]
> Actually, the step 6 (out of 7) is not the real neural training (step 7/7).
> 
> In other words, if you CTRL-C the process during step 6, you do not have any model to use.
> so the resuming is still important.

In fact, in the case you reported, when you interrupt the training a step 6 the engine correctly resume from the latest interrupted step: the 6th.

So from your exact output I can say that MMT is working as expected; which is the point where you think the process is not correct?

> what happens if you CTRL-C the process during the first iteration of the training?

If the process stops before being able to write the first epoch, an exception is thrown and the "--resume" flag will work as expected resuming from step 7.

**Comment by nicolabertoldi** [comment]
sorry,   my fault
Actually the behavior is perfect.
