### ISSUE TITLE
Docker version not training

### ISSUE THREAD

**Issue by NickRuiz** [ModernMT/MMT#265]
I set up MMT with Docker, but I can't get the training example working.
```
mmtuser@980810825d90:~/mmt$ ./mmt create en it examples/data/train


=========== TRAINING STARTED ===========

ENGINE:  default
BILINGUAL CORPORA: 3 documents
MONOLINGUAL CORPORA: 0 documents
LANGS:   en > it

INFO: (1 of 7) TMs clean-up...                                         DONE (in 0s)
INFO: (2 of 7) Corpora pre-processing...                               DONE (in 0s)
ERROR Unexpected exception:
        Command 'java -cp /home/mmtuser/mmt/build/mmt-1.0.2.jar -Dmmt.home=/home/mmtuser/mmt -Djava.library.path=/home/mmtuser/mmt/build/lib eu.modernmt.cli.TrainingPipelineMain -s en -t it -v /home/mmtuser/mmt/engines/default/models/vocabulary --output /home/mmtuser/mmt/runtime/default/tmp/training/preprocessed --input /home/mmtuser/mmt/runtime/default/tmp/training/training_corpora --dev /home/mmtuser/mmt/engines/default/data/dev --test /home/mmtuser/mmt/engines/default/data/test' failed with exit code -6
mmtuser@980810825d90:~/mmt$ uname -a

Linux 980810825d90 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Are there any prerequisites that I might be missing? Thanks!

**Comment by AndRossi** [comment]
Hi @NickRuiz, 

I have tried to perform a fresh image pull, and unfortunately I was not able to replicate your issue in our environment.

Did you pull the master image with command `docker pull modernmt/master`, and run it with command `docker run -it --publish 8045:8045 modernmt/master bash`?

You should find a detailed log file in your running image in path `/home/mmtuser/mmt/runtime/default/logs/training.log`.

Could you please send me its content?

Thanks for your patience.

Andrea

**Comment by NickRuiz** [comment]
Here is my log.
[training.log.txt](https://github.com/ModernMT/MMT/files/1232267/training.log.txt)

**Comment by AndRossi** [comment]
Hello @NickRuiz,

This is probably the same issue as #260. 

I believe that the librocksdb module makes hardware assumptions that in some rare cases might raise that problem.

Recompiling the software in your environment should definitely fix it.
To do that, please follow our [install MMT from sources guide](https://github.com/ModernMT/MMT/blob/master/INSTALL.md#option-3---installing-from-source-for-contributors).

You can install MMT from sources either on your docker image or directly your machine, if its OS is Ubuntu 14.04 or 16.04.

Thanks for your patience.

Andrea

To be sure about the nature of your issue, could you please send me your /home/mmtuser/mmt/hs_err_pid867.log file? You can just attach it by dragging and dropping it.

Thanks for your patience!

**Comment by AndRossi** [comment]
Hi @NickRuiz,

In the end, did you manage to run MMT in your environment?

Andrea

**Comment by NickRuiz** [comment]
Yes, thank you. I ended up dropping Docker and compiling the project
directly. Now training is proceeding smoothly.

**Comment by AndRossi** [comment]
Great! I'm glad everything works fine.

Since the situation is ok I'm closing this issue now.
However, for any problem or doubt, don't hesitate to reopen it.

Have a nice day!
Andrea
