### ISSUE TITLE
Cluster issue - Error after stop 2nd node 

### ISSUE THREAD

**Issue by rptl** [ModernMT/MMT#266]
Steps to reproduce

1 - Start 1st node (leader) 
2 - Start 2nd node (--join-leader)
3 - Send few sentences to translation just to validate that both are respoding
4 - Stop slave node
5 - Send sentence to translation

At this point I have to restart Leader node. Any try to translate I got following on node.log:

```
> 2017-08-17 17:52:12,922 ERROR eu.modernmt.rest.actions.translation.Translate [qtp507383828-78] Internal error while executing action Translate
> java.util.concurrent.RejectedExecutionException: ExecutorService[TranslationsExecutor] is shutdown! In order to create a new ExecutorService with name 'TranslationsExecutor', you need to destroy current ExecutorService first!
> 	at com.hazelcast.executor.impl.ExecutorServiceProxy.checkNotShutdown(ExecutorServiceProxy.java:221)
> 	at com.hazelcast.executor.impl.ExecutorServiceProxy.submitToPartitionOwner(ExecutorServiceProxy.java:233)
> 	at com.hazelcast.executor.impl.ExecutorServiceProxy.submit(ExecutorServiceProxy.java:228)
> 	at eu.modernmt.cluster.ClusterNode.submit(ClusterNode.java:474)
> 	at eu.modernmt.facade.TranslationFacade.get(TranslationFacade.java:77)
> 	at eu.modernmt.facade.TranslationFacade.get(TranslationFacade.java:62)
```

**Comment by AndRossi** [comment]
Hi @rptl,

We are going to take care this issue immediately. 

I'll let you know as soon as I have updates on it :)

Thanks again for your patience!

Andrea

**Comment by rptl** [comment]
Thanks, no problem! 

In this meantime, can you tell me if there is a way to check webserver/rest settings? 

I am doing some async calls and blowing up REST WebServer.... Getting error 502 or 504 after too many calls. hehe  

Wanted to check max connections, max simultaneous requests and timeout, to make requests based on those numbers.

**Comment by AndRossi** [comment]
Hi @rptl,

I have solved this issue: now if you stop a follower engine it does not affect the other nodes.
The fixed version is available in our **master** branch with commit 8e483b7

Please note that, on the contrary, **restarting the leader node** will cut the followers communications with the leader DB. As a consequence after restarting the leader you will need to restart the followers too.

However, it is possible to overcome this single point of failure and create a peer-to-peer cluster following [this guide](https://github.com/ModernMT/MMT/wiki/Advanced-Configurations#example-3-peer-to-peer-cluster).

As for the webserver configuration, we use Jetty 9.3.6 default configurations. Connections are handled by a thread pool with size 200, and the HTTP timeout should be 30 seconds. 

Thanks for your support!

Have a nice day

Andrea

**Comment by rptl** [comment]
Thanks again. I will try the fix now. 

Another question or it's more like a request:

Did you consider to process an array of sentences on a single REST requests Something like q=["sentence1",sentence2",...]? It probably will improves response time. bmix use this feature, and it's WAY faster than send a single call for each sentence. Of course, there is limit for each post, I think it's 40kb.

**Comment by AndRossi** [comment]
Hi @rptl 

At the moment we do not plan to open a translation API for arrays of sentences.

In our experience, the time required by the translation process is about one order of magnitude longer than the network time, so our priority at the moment is making the translation itself faster.

However in the future we will certainly consider expanding the REST APIs. 
I will keep you updated on this!

Thanks again for your support.
Have a nice weekend :)

Andrea
