### ISSUE TITLE
Does IMPORT also accept a folder like CREATE ?

### ISSUE THREAD

**Issue by EtienneAb3d** [ModernMT/MMT#268]
I would enjoy to have a homogeneous way to provide my data to MMT. 
But, the help text of the ADD command only explains about sentences, and the help text of the IMPORT command only explains about TMX. 
Is it possible to provide a folder to the IMPORT command, that would do the job exactly like the CREATE command ?

**Comment by davidecaroselli** [comment]
Hi @EtienneAb3d 

not at the moment, but what you're suggesting seems like a good feature to me! I will work on it and get back to you ass soon as it's ready.

**Comment by davidecaroselli** [comment]
Hi @EtienneAb3d 

the new command option is available in the latest commit (https://github.com/ModernMT/MMT/commit/67972e02bebb3efd14362699f4c5cf35f392c745) of **master** branch. You can update your distribution rebuilding it from source, here's the instructions: [Installing from source code](https://github.com/ModernMT/MMT/blob/master/INSTALL.md#option-3---installing-from-source-for-contributors).

You can now use the mmt import command like this:
```bash
./mmt import --path path/to/your/corpora
```
The command will automatically import all your TMX or parallel files inside the path specified.

Thanks for your support, we are closing the issue right now but if you have any other questions please don't hesitate to re-open it!

**Comment by EtienneAb3d** [comment]
Thanks !
I succeeded in installing from sources.
I will test your new feature as soon as a new situation of a model update will come.

**Comment by EtienneAb3d** [comment]
Thanks !
I succeeded in installing from sources.
I will test your new feature as soon as a new situation of a model update will come.
