### ISSUE TITLE
Clustering - How to keep models synchronized among the servers? 

### ISSUE THREAD

**Issue by rptl** [ModernMT/MMT#270]
If some Cluster member be down during add sentence event (single or tmx), the model in this node will not be updated, correct? 

 I see a message in log files showing that replication is not available in this version and that brings me to the following question:

Is there any kind of synchronization or data replication in place for engine models directory, embedded in MMT?

Thanks.

**Comment by rptl** [comment]
Ok, I see that internal sync has been removed some time ago. 

 What are te sync options? 
NFS - since files will be the same, I had some issues with Kafka index files. Also, I believe I can face some issues with file locking. 
Bind mounting  same as NFS.

Dis not try yet:
rsync
Clustering block device (ie. drbd) as  active-active

Any other option?

**Comment by davidecaroselli** [comment]
Hi @rptl 

all the info about setting up the cluster are available here: [MMT Cluster](https://github.com/ModernMT/MMT/wiki/MMT-Cluster).

**Long story short:** once you created an engine from scratch, you have to manually copy the `engines/<engine_name>` folder to all the members of your cluster. But that must be done **only the very first time**.

Once done that, you can start your cluster and, from that point on, all the contributions (import and single source/target contributions) will be **automatically synched** to all nodes of the cluster. Even if a node lost the connection for a while, as soon as it will re-join the cluster it will **receive all the updates**, no one will be lost (thanks to the Kafka queue).

So no need for NFS setup or rsync, **consistent delivery of updates and new domains is handled automatically by the system**.

One last thing: the default MMT Cluster has a [Leader-Followers scheme](https://github.com/ModernMT/MMT/wiki/MMT-Cluster#leader-followers-cluster-architecture) (datastream is Kafka, while database is Cassandra). In this configuration you have a single point of failure: if the _Leader node_ goes down, the Cluster will be in trouble.

However MMT also allows a Peer-to-Peer configuration, which I recommend for production, where any node of the cluster can go down without harming the overall functioning. This configuration is described more in details here: [MMT peer-to-peer cluster](https://github.com/ModernMT/MMT/wiki/MMT-Cluster#mmt-peer-to-peer-cluster), an example configuration is also available [here](https://github.com/ModernMT/MMT/wiki/Advanced-Configurations#example-3-peer-to-peer-cluster).

Hope this helps!
Cheers

**Comment by davidecaroselli** [comment]
I'm closing this issue right now, if you need more help please don't hesitate to re-open it!
