### ISSUE TITLE
Migrating a trained engine to another server without re-training?

### ISSUE THREAD

**Issue by mzeidhassan** [ModernMT/MMT#273]
Hi MMT team,

I am wondering if it's possible to migrate an already trained engine to another server without having to do the training again? I am asking this because the engine I created required a huge amount of RAM which I cannot afford on a cloud server. So, I am thinking of training the engine at home, and then just upload the engine to a new fresh install of MMT on cloud? Would that work? 

The second question:
Presumably, the above method is working. Would I encounter issues during tuning on the cloud server with 4 GB of RAM for example?

One last thing about Neural Machine Translation:

How is it going with your neural MT addition? Is this coming soon? 

Thanks,
Mohamed

**Comment by AndRossi** [comment]
Hello @mzeidhassan,

Yes, it is possible to migrate an already trained engine to another machine.
All you have to do is to copy the `<mmt_root>/engines/<your_engine>` folder from your original machine into your destination machine.    
You can then proceed to run `./mmt start -e <your_engine>` in your destination machine as if you had created the engine there.  
Make sure that both your old machine and your new machine have the same MMT version.

As for the hardware requirements, RAM is very important in tuning, and I think you could have some problems using just 4GB of RAM. If I understand well you plan to deploy engines trained with more than 100M words, so their models will be quite large. 
All in all, if I were you I'd go with at least 8GB RAM.  

Neural Machine Translation is in the final phases of development, so it will be released very soon. Stay tuned! ;) 

Andrea

**Comment by mzeidhassan** [comment]
Thank you so much Andrea for your great answer as usual!

I am very glad to know that NMT will be released soon :-) 👍
