### ISSUE TITLE
Bidirectional engine: Source <>Target?

### ISSUE THREAD

**Issue by mzeidhassan** [ModernMT/MMT#274]
Hello MMT team,

I am wondering if there is a way to create a bi-directional server that can translate both ways; i.e. from source to target and from target to source. 

I came across this issue https://github.com/ModernMT/MMT/issues/3, but it was closed for inactivity. So, I am not sure if this is already implemented or not.

Do we need to create a separate engine for each language pair if we want to have a bidirectional server?

Thanks,
Mohamed

**Comment by davidecaroselli** [comment]
Hi @mzeidhassan 

You guess it right: in order to have bi-directional translations, you have to train two different engines. In fact, this is the easiest and fastest way to do it in any case!

**Comment by mzeidhassan** [comment]
Thanks Davide for your answer! I appreciate it. 

I am closing this issue then.
