### ISSUE TITLE
When do you plan to release SDL Trados Studio plugin?

### ISSUE THREAD

**Issue by mindaugasDEV** [ModernMT/MMT#277]
Hi, Innovators,

I am so excited that you relased 2.0! Will test it shortly.

Matecat folks told that you are redoing API for Matecat and for MMT as they are not stable:
https://github.com/matecat/MateCat/issues/992

My humble questions that are important for many followers:
1) when are you planning to release SDL plugin?
2) is MMT API stable? 
3) If SDL plugin is not coming shortly, what is the application for batch  translating XLIFF files ( not using MMT API for every sentence, but translating the whole file). Shall we use Okapi MMT API integration? Is it stable for production use?

Thanks,
Mindaugas

**Comment by davidecaroselli** [comment]
Hi @mindaugasDEV 

we are still in the process of releasing the new 2.0 version of MMT (it's not currently available in the releases), but we should complete the process by today.

> when are you planning to release SDL plugin?

At the moment there is no deadline for the release of the Trados plugin, but it is definitely something we will work on in the next months.

> is MMT API stable?

MMT v2 API should be considered stable, **but we haven't published them yet**, we are updating the documentation before the official release.

> If SDL plugin is not coming shortly, what is the application for batch translating XLIFF files ( not using MMT API for every sentence, but translating the whole file). Shall we use Okapi MMT API integration? Is it stable for production use?

I am currently not aware of the Okapi MMT API so I can't say if they are reliable or not. Regarding XLIFF bulk translation, it really depends if you want to use hosted MMT or the MMT public service (available by end of October). If you have your own installation you should be able to use the `translate` command like this:
```
./mmt translate --context <your context> --batch --xliff < myfile.xliff
```
If you want to use the online service I suggest to use MateCat for translating your XLIFF.

**Comment by mindaugasDEV** [comment]
Thank you!!!

**Comment by mzeidhassan** [comment]
Sorry to jump in. @mindaugasDEV I just want to say that I used OKAPI MMT and it works just fine, but it's a bit slow. I tested it with the SMT version of MMT though. You can use it to translate SDL Trados Studio SDLXLIFF files. I would test Davide's method first and see. I believe it would be faster.

**Comment by mindaugasDEV** [comment]
Hi, @mzeidhassan 

Thanks for jumping into discussion. What tool from Okapi did you use? Tikal command line or Rainbow?
Can you share the commands you use or screenshot?

I could not understand how to use them :(.

Best,
Mindaugas

**Comment by mzeidhassan** [comment]
@mindaugasDEV  you can find details here 
http://okapiframework.org/wiki/index.php?title=ModernMT_API_Connector

**Comment by lennart-tondeleir** [comment]
Hi,
What is currently the best way to work with a self-hosted MMT engine and self-hosted MateCat? And if this is not possible yet, are there any plans to incorporate this?
