### ISSUE TITLE
GPU model => CPU ?

### ISSUE THREAD

**Issue by EtienneAb3d** [ModernMT/MMT#279]
While my first tuning is running, I see that checkpoints are not with the usual ONMT "t7" extension. 

Will it be possible to convert them, or start them, as CPU models ? I don't see any information about this possibility in the command line helpers.

It's very useful when you want to run a large set of models, without high performance needs.

**Comment by nicolabertoldi** [comment]
No,
MMT cannot be run o a GPU; and consequently, it is not possible to convert checkpoint into a format loadable on CPU.
The rationale for this is that MMT implements an instance-based adaptation procedure, which requires to re-train the original network for each input sentence; this re-training is performed on the GPU in a super-fast way.

**Comment by EtienneAb3d** [comment]
Wahoo ! If I need dozens of neural models, it will cost me a lot for the hardware...

**Comment by nicolabertoldi** [comment]
Actually, from theoretical and implementational point of views MMT could work on CPU as well.

Unfortunately we discovered an issue during loading the model in CPU, but we have not investigated yet.

Consider however that running the decoder on CPU could be definitely slower due to the instance-based adaptation mentioned before.

**Comment by EtienneAb3d** [comment]
I will test it as soon as it will be available !

**Comment by davidecaroselli** [comment]
Hi @EtienneAb3d 

this has been solved in the latest commit https://github.com/ModernMT/MMT/commit/049953fbf8ec959532b7fe040771fc154daed142 of the master branch.

You can now build engines with GPUs/CPUs and run them with GPUs/CPUs, any option is allowed.

Cheers,
Davide

**Comment by EtienneAb3d** [comment]
After having fixed the bug #302, it works nicely.
But... 16G for each loaded model. I will need a laaaarge RAM !
;-)
