### ISSUE TITLE
Auto Tuning, Self Evaluation and Time to complete

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#28]
It would be great if MMT could provide:
1 - Tuning during the training as an optional parameter.
2 - Estimation of the quality of the engine ad the end of training. 
3 - Training progress bar. (time to complete the training)

Assuming a real world scenario where a company will train an engine on their TM to translate similar future content.

@mfederico 
I know how to do a good estimation of 3. 
Do you think that 1 and 2 are feasible?
eg. In this scenario does it make sense to remove 2 blocks of ~1K random sentences to do a MERT and BLUE estimation? Or is there a better way to do it?

**Comment by davidecaroselli** [comment]
I'm closing this discussion because the proposed solution has been already presented on issue #43 as @marcotrombetti suggested. Please refer to that issue for further discussions.
