### ISSUE TITLE
resume does not work in the neural case

### ISSUE THREAD

**Issue by nicolabertoldi** [ModernMT/MMT#282]
resume function does not work as expected in the neural case;
when the system has to reload an existing checkpoint to continue training, it fail because it does not find the BPE model

Actually, the BPE model is not associated with the checkpoint.

I suggest to add the bpe model to the checkpoint state and loading it properly when needed.

**Comment by davidecaroselli** [comment]
I totally agree, bpe should be part of the checkpoint: saved and loaded just like model and metadata.

**Comment by AndRossi** [comment]
Since this issue has been solved by @nicolabertoldi, I am closing this issue now :)
