### ISSUE TITLE
training starting from and existing checkpoint is not effective

### ISSUE THREAD

**Issue by nicolabertoldi** [ModernMT/MMT#283]
the training starting from an existing checkpoint seems not be effective
in the sense that it has very low performance

I simulated the effect of resuming the training  by means of start a new training 
but I got different performance.

What differs between the two procedures.

**Comment by davidecaroselli** [comment]
It should be the same actually, so we should assume to have same issue both in the restart and the train from existing model.

**Comment by AndRossi** [comment]
Since the problem has been solved by @nicolabertoldi, I am closing this issue now :)
