### ISSUE TITLE
Severe system trouble with neural MMT translation server

### ISSUE THREAD

**Issue by EtienneAb3d** [ModernMT/MMT#289]
It completely reproducible on my side:
- fresh boot of the machine : 64G RAM, GTX 1080 Ti 11G
- start neural FR->EN engine. 2.6G loaded on the GTX
- send sentences to translate, one by one, not at a heavy rate (perhaps 2 ou 3 by mn), with a context C1. Translation requests are asynchronous, thus several can be sent together.

After few hundred sentences:
1) the MMT server return with a 500 error when asking a new translation with the context C1. BUT, it still reply normally with an other context C2..(!?)
2) java won't start any more. The simple command "java -version" give this error:
`lm-dev8@dev8:~/MMT2/ModernMT$ java -version`
`#`
`# There is insufficient memory for the Java Runtime Environment to continue.`
`# Cannot create GC thread. Out of system resources.`
`# An error report file with more information is saved as:`
`# /home/lm-dev8/MMT2/ModernMT/hs_err_pid17692.log`
But, the system is still with a very very low RAM charge !
3) in one case, I couldn't even open a new SSH distant access to the machine !?

After a reboot, my next test will be to serialize translation requests, to see if it changes something...

**Comment by AndRossi** [comment]
Hello @EtienneAb3d, 

As far as I know the Java Runtime Environment raises that error when it is asking the OS for more RAM, but the OS refuses saying that it does not have any. So I would say there is something weird in the interaction with the OS.

This error most frequently occurs in two cases:

* Case 1: All of your RAM is actually being used. However, if your system had a low RAM charge (and with 64GB of RAM, that's what I would expect), I guess this is out of discussion.
* Case 2: your Java is in 32 bit mode and you are trying to exceed the max amount of allowed processes. 

Can you please check if your java is 32 bit mode with command `java -d32 -version`?

Thanks for your support,

Andrea

**Comment by EtienneAb3d** [comment]
This has nothing to do with Java itself. It is usually working properly on this machine. 

Doing a new try with serialized sentences, it is once more blocking after 761 sentences:
- the MMT engine return an error with code 500 when called with the same context string
- the MMT engine is still working properly with an other context string

This time Java isn't crashing, afterwards, and I don't see something else wrong for the moment.

After a reboot, I will now do a new try, in exactly same conditions, just to see if the crash is exactly on the same sentence (now they are serialized, thus exactly in the same order).

**Comment by EtienneAb3d** [comment]
Very strange !!
I did a new attempt. In spite of the fact that I serialized the sentences, in order to have only one sentence sent at a time, I have a previous multi-threading process that makes the order not really deterministic. Thus, I not sure all sentences were sent exactly in the same order. But, the problem occurred exactly at the same 761 sentences. 
Thinking this was possibly due to a very particular sentence, after restarting the engine, I built a SH to sent again the last 100 sentences. I got no problem with them.
:(

**Comment by EtienneAb3d** [comment]
I give up on this analyze.
Since I have new data to add in the training set, I will retrain the model... and see if this trouble still occur afterwards.

**Comment by AndRossi** [comment]
Hi @EtienneAb3d,

It seems that your OS is running out of a specific resource. It does make sense that this happens always after the same 761 sentences, disregarding of their order.
 
If you have kept it, can you please send me your `/home/lm-dev8/MMT2/ModernMT/hs_err_pid17692.log` file? 
It might contain some useful information on the usage of your resources.

Andrea

**Comment by EtienneAb3d** [comment]
I just tied to translate with a new created MMT SMT engine.. and got exactly the same problem ! It is thus not simply a problem with the neural part of MMT. It's rather a problem with the new version of MMT. 

According to this latest response, what is saturated seems to be the thread capability:
`$ curl "http://localhost:8045/translate?q=inf%C3%A9rieur&source=fr&target=en&context=embrayage+frein+moteur+pneumatique+airbag+v%C3%83%C2%A9hicule"`
`{"status":500,"error":{"type":"Error","message":"Unexpected exception: unable to create new native thread"}}`

**Comment by AndRossi** [comment]
Hello @EtienneAb3d .

If a resource is over (or the OS believes it is over), it makes perfectly sense that, when you send the MMT server a new request, the JVM fails to spawn a new thread to handle it.

However, to have more certain details on this, and to understand if the resource that is over is actually the process size, I need to check your log files.

Can you please send me your `/home/lm-dev8/MMT2/ModernMT/hs_err_pid17692.log` (or its equivalent from your last attempt)?
Your `node.log` file would be probably useful as well.

Andrea

**Comment by EtienneAb3d** [comment]
The command line `java -d32 -version` returns this:
`Error: This Java instance does not support a 32-bit JVM.`
`Please install the desired version.`

I saw that the main Java process was launched without Xmx parameter. I tried to change the code in `cluster.py` to set it to 4G. Now, it is running with an `-Xmx4046m` option. But, this doesn't solve the problem.  Even, it doesn't change the number of sentences I can send (about 900 in my experiment with the SMT server).

In a second machine (a bit more loaded), the problem is the same with the SMT engine. It thus doesn't depend on the machine.

The `node.log` file shows this error:
`2017-10-23 14:20:06,274 ERROR eu.modernmt.rest.actions.translation.Translate [qtp907721985-106] Internal error while executing action Translate`
`java.lang.Error: Unexpected exception: unable to create new native thread`
`	at eu.modernmt.facade.TranslationFacade.unwrapException(TranslationFacade.java:196)`
`	at eu.modernmt.facade.TranslationFacade.getContextVector(TranslationFacade.java:157)`
`	at eu.modernmt.rest.actions.translation.Translate.execute(Translate.java:36)`
`	at eu.modernmt.rest.actions.translation.Translate.execute(Translate.java:22)`
`	at eu.modernmt.rest.framework.actions.ObjectAction.getResult(ObjectAction.java:13)`
`	at eu.modernmt.rest.framework.actions.ObjectAction.getResult(ObjectAction.java:8)`
`	at eu.modernmt.rest.framework.actions.JSONAction.unsecureExecute(JSONAction.java:48)`
`	at eu.modernmt.rest.framework.actions.JSONAction.execute(JSONAction.java:21)`
`	at eu.modernmt.rest.framework.routing.RouterServlet.service(RouterServlet.java:105)`
`	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)`
`	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)`
`	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)`
`	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:513)`
`	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)`
`	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)`
`	at eu.modernmt.rest.MultipartConfigInjectionHandler.handle(MultipartConfigInjectionHandler.java:49)`
`	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)`
`	at org.eclipse.jetty.server.Server.handle(Server.java:517)`
`	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)`
`	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)`
`	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)`
`	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)`
`	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)`
`	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)`
`	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)`
`	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)`
`	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)`
`	at java.lang.Thread.run(Thread.java:748)`
`Caused by: java.lang.OutOfMemoryError: unable to create new native thread`
`	at java.lang.Thread.start0(Native Method)`
`	at java.lang.Thread.start(Thread.java:717)`
`	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)`
`	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1367)`
`	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)`
`	at eu.modernmt.context.lucene.analysis.rescoring.CosineSimilarityRescorer.rescore(CosineSimilarityRescorer.java:30)`
`	at eu.modernmt.context.lucene.analysis.ContextAnalyzerIndex.getContextVector(ContextAnalyzerIndex.java:170)`
`	at eu.modernmt.context.lucene.analysis.ContextAnalyzerIndex.getContextVector(ContextAnalyzerIndex.java:130)`
`	at eu.modernmt.context.lucene.LuceneAnalyzer.getContextVector(LuceneAnalyzer.java:100)`
`	at eu.modernmt.context.lucene.LuceneAnalyzer.getContextVector(LuceneAnalyzer.java:89)`
`	at eu.modernmt.facade.TranslationFacade$GetContextVectorCallable.call(TranslationFacade.java:247)`
`	at eu.modernmt.facade.TranslationFacade$GetContextVectorCallable.call(TranslationFacade.java:229)`
`	at java.util.concurrent.FutureTask.run(FutureTask.java:266)`
`	at com.hazelcast.executor.impl.DistributedExecutorService$CallableProcessor.run(DistributedExecutorService.java:241)`
`	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:212)`
`	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)`
`	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)`
`	at java.lang.Thread.run(Thread.java:748)`
`	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)`
`	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)`

Here is the `hs_err_pid17692.log` file, obtained in the first post above.
[hs_err_pid17692.log](https://github.com/ModernMT/MMT/files/1407187/hs_err_pid17692.log)

**Comment by EtienneAb3d** [comment]
I launched MMT main Java process in a JProfiler (latest evaluation version). After 500 translation, MMT has already launched 6000 threads:
![image](https://user-images.githubusercontent.com/25932245/31894181-f0625cf6-b80d-11e7-88cd-1bb5827f3031.png)

**Comment by EtienneAb3d** [comment]
When MMT is returning a error code 500, after 900 sentences, it has created 11000 threads:
![image](https://user-images.githubusercontent.com/25932245/31895138-a63addf8-b810-11e7-9138-38d409779551.png)

**Comment by AndRossi** [comment]
Hello @Etienne,

Thank you for these data!  
They are extremely useful, and they are helping us reach the core of the problem.

I am currently investigating on why MMT spawns so many threads. 
It is most probably a bug in MMT thread handling: we suspect that during translation process some threads are not closed properly, and this makes their number explode in time.

I will let you know as soon as I find where the bug is more precisely.

I deeply thank you for your support and patience. We really appreciate it. 

Andrea

**Comment by EtienneAb3d** [comment]
This JProfiler screen copy may help find the place:
![image](https://user-images.githubusercontent.com/25932245/31896016-f9bceece-b812-11e7-881a-654b3e50d370.png)

**Comment by AndRossi** [comment]
Hello @EtienneAb3d ,

I have good news: I have just pushed in `master` branch a fix that should solve the thread spawning problem.

Your help and your feedbacks were vital for finding the bug. Thank you!
Please let me know if the fix solves the problem on your side too.

Have a wonderful day!

Andrea

**Comment by EtienneAb3d** [comment]
Good job !

Thanks !

The number of threads seems now very stable. Here after 500 sentences translated:
![image](https://user-images.githubusercontent.com/25932245/31953124-abaa5c50-b8e2-11e7-9c40-259080f31cd1.png)

**Comment by AndRossi** [comment]
I'm so glad it seems to work well now!

Let's see if it makes it past your original 716 sentences ;)

**Comment by EtienneAb3d** [comment]
The 1500 segments of this test file was translated without trouble.
:D

**Comment by AndRossi** [comment]
Hello @EtienneAb3d, 

Since this issue seems solved, I'm closing it now.
However, for any further doubt or problem please do not hesitate to re-open it.

Thank you again for your support and your patience :) 

Andrea
