### ISSUE TITLE
Tokenizers Speed

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#29]
New parallel tokenization is working great (>4x faster) but it can be up to 12x faster by a better prediction of how many process to spawn.

Today it may be 
processes = num_cores/3\*2 
but the right number could be 
processes = num_core\*2

With a 1B words model it only consumes 30% of CPU with still 0% iowait.

**Comment by marcotrombetti** [comment]
Solution proposed tested with Davide.
No improvments. Redesign required.

**Comment by davidecaroselli** [comment]
I've run some really interesting tests for the new MMT TextProcessing framework. Here I present the result of different versions of tokenizers on a **single english document with 83M words**.
* Standard Moses pipeline: **19m 59s**
* MMT Tokenizer v0.11: **14m 56s**
* MMT Tokenizer v0.12: **13m 25s**

So with the last version of the tokenizer we gain **10% in speed**.
But now things start to become interesting: I've run the same test with MMT Tokenizer switching from standard Moses PERL scripts (default choice right now) to Lucene Implementation:

* MMT Tokenizer with Lucene: **0m 44s**

Ok, we now that the English Tokenizer of Lucene is much simpler than Moses one, but the result it's literally **amazing**. There is so much difference in terms of performance, **20x** that I'm pretty sure we can rewrite the Moses tokenizer to a more optimized version gaining **5~10x**.

**Comment by mfederico** [comment]
Hi Davide, 

what about training and testing MMT with the faster tokenizer? 

Marcello

**Comment by davidecaroselli** [comment]
Hi Marcello,
If you want to test MMT Tokenizer v0.12, I've just created a pre-release here: http://labs.mmt.rocks/builds/mmt-0.12-SNAPSHOT_201601271619-ubuntu14_04.tar.gz

**Comment by marcotrombetti** [comment]
@davidecaroselli does this release include also lucene-based **detokenizer** or still has the Moses perl detokenizers?

**Comment by davidecaroselli** [comment]
New JFlex Tokenizer is now default tokenizer (20x faster than Moses Perl one).
The Detokenizer is still the one from moses.
