### ISSUE TITLE
Adding a single contribution to a memory

### ISSUE THREAD

**Issue by frdg** [ModernMT/MMT#291]
Hello,

First of all, I would like to thank you for the amazing job you've done so far.

Into the issue.

I created a new engine (en-nl) and started it.

I tried to add a single contribution to an existing memory. Following what can be found [here](https://github.com/ModernMT/MMT/wiki/API-Add-to-Memory#adding-a-single-contribution-to-an-already-existing-memory), I used the following query:
`curl -X POST http://localhost:8045/memories/1/corpus -d "source=en" -d "target=nl" -d "sentence=Hello Mike!" -d "translation=Hallo Mike!" | python -mjson.tool`

The problem is that the server's response does not return the proper memory id:
`{
    "data": {
        "begin": 1,
        "dataChannel": 1,
        "end": 1,
        "id": "80000001-0000-0000-0000-000000000001",
        "memory": 0,
        "progress": 0.0,
        "size": 1
    },
    "status": 200
}`

I did check that the provided memory id existed for that engine.

**Comment by davidecaroselli** [comment]
Hi @frdg 

so, regardless the odd output, the addition just completed successfully. Unfortunately we have a limitation with the current version of MMT that cannot return the proper Memory id for a single contribution (only for a corpus import, like a TMX).

This is actually not very well handled (we use a memory of 0 as a null value) and not properly explained in the documentation so your doubts are perfectly reasonable.

We will work in improving the API response and the documentation as well.
Thank you!

**Comment by frdg** [comment]
Thank you for your answer, indeed, I forgot to add that the newly inserted translation was available. I was wondering whether or not it was stored in right place.

**Comment by davidecaroselli** [comment]
Thanks @frdg

I'm keeping this issue open so that it will be used as a reminder, we will close it as soon as we fixed the odd output.
