### ISSUE TITLE
Multiple languages for a given engine, DataManagerException

### ISSUE THREAD

**Issue by frdg** [ModernMT/MMT#292]
Hello,

I am trying to setup a multilingual engine.

I went through the different steps:
- create the engine
- modify the engine.xconf to add the <pair> nodes
- start the engine
- add a new memory

Next, whether I try to add a single contribution or upload parallel files to the new memory using the newly defined language-pair, I systematically get a DataManagerException.

Here is the query:
`curl -X POST http://localhost:8045/memories/2/corpus -d "source=en" -d "target=de" -d "sentence=Good afternoon Mike!" -d "translation=Guten Tag, Mike!" | python -mjson.tool`

And here, the error message:
`{
    "error": {
        "message": "Unexpected exception while data-stream polling",
        "type": "DataManagerException"
    },
    "status": 500
}`

Once this has happened, I cannot start the engine again and have to resort to deleting it and start again from scratch.

I will post more details if you need them.

**Comment by AndRossi** [comment]
Hello @frdg,
 
We are currently facing a bug that is probably related to this :)
Can you please send us your `runtime/<your_engine>/logs/node.log` file? It should contain more detailed information on this problem.

Thank you for your support!

Andrea

**Comment by frdg** [comment]
Hello @AndRossi, attached are the logs.

Thanks for your answer :)

[node.log](https://github.com/ModernMT/MMT/files/1427868/node.log)

**Comment by AndRossi** [comment]
Hello @frdg, 

There may be a problem in your configuration file: your engine does not recognize en -> de as a supported language pair.
Can you please send me your `engine.xconf` file too?

Andrea

**Comment by frdg** [comment]
Hello @AndRossi, here is the file. Just modified the extension to attach it.

Thanks :)

Fred

[engine.txt](https://github.com/ModernMT/MMT/files/1429847/engine.txt)

**Comment by AndRossi** [comment]
Hello @frdg, 

I am not sure what is going wrong there: I have copy-pasted your `engine.xconf` file in a new engine of mine, restarted it, and the en -> de import worked smoothly.

These are the steps I have followed more in detail:

- I have created a new en-nl engine with a command like: `./mmt create en nl /path/to/your/en_nl/files`. A new folder named "default" was successfully generated.
- In the `engines/default` folder, I have erased the previous `engine.xconf` file and copy-pasted your `engine.txt` instead
- I have renamed this file as `engine.xconf`
- I have  tried your `curl -X POST http://localhost:8045/memories/2/corpus -d "source=en" -d "target=de" -d "sentence=Good afternoon Mike!" -d "translation=Guten Tag, Mike!" | python -mjson.tool` and it worked.

Did you follow exactly these steps?

Andrea

**Comment by frdg** [comment]
I followed your steps (just one was missing, adding a new memory).

The server did return status code 200 when performing `curl -X POST http://localhost:8045/memories/2/corpus -d "source=en" -d "target=de" -d "sentence=Good afternoon Mike!" -d "translation=Guten Tag, Mike!" | python -mjson.tool`. 

Then, when testing `curl -X GET http://localhost:8045/translate -d "source=en" -d "target=de" -d "q=Good afternoon Mike!" | python -mjson.tool` I was returned an `UnsupportedLanguageException, Language pair not supported: en > de`.

Double checked the engine.xconf, same as the one I sent you.

en > nl works fine.

@AndRossi after you imported a segment pair, have you tried to get the translation?

**Comment by frdg** [comment]
I'll try this.

Thank you for your answer and updating the wiki :)

**Comment by AndRossi** [comment]
You're welcome! 

Please let me know if the multilingual cluster launch goes smoothly, or if you need support with it :)

Andrea

**Comment by frdg** [comment]
> Neural engines, on the contrary, are "fully" multilingual, meaning that a single engine can actually execute jobs for any enabled translation language.

Mmh, I tried it and still had `UnsupportedLanguageException`. Getting a little confused here.

That leads me ask what happens when you add new material once you added a new language pair to the `engine.xconf` and started the engine.

Lets assume that you upload a TMX to a new memory with a different language pair than the one used at creation of the engine. When is the new model trained?

Also, after adding material to an existing neural engine in a different language pair than the one I used to create the engine, no new resources were created in the engine's folder apart from a file in `/models/context/storage/`.

(Slightly drifting away from the original goal of this ticket, sorry.)

**Comment by AndRossi** [comment]
Hello @frdg,

Sorry for the delayed answer.

As you pointed out, in order to start a new multilingual neural engine it is not enough to just update the engine.xconf file: the engine also needs aligner and decoder models for all the language pairs to support.
On a second thought, in fact, deploying a neural multilingual engine is not a trivial process; I apologize for my previous answers not being detailed enough. I have now written a new wiki page with a more detailed, step-by-step guide. You can find it [here](https://github.com/ModernMT/MMT/wiki/Multilingual-Engines). 

I hope it helps!

As for your questions: 
The new material you add is processed and sent to the corresponding alignment and decoder models. If there are no models for that language pair, even if the language pair is enabled in the engine.xconf file, an unsupportedLanguageException is thrown (this is what happened in your engine). The model for a new language pair, thus, must be created beforehand and separately (e.g. using a separate engine). 

By the way, we have also just released MMT 2.0.1. 
It includes several bugfixes, including the fix for the bug that prevented your engine from correctly restarting.

Please let me know if you encounter further issues!

Thank your for your patience and support :)

Andrea

**Comment by frdg** [comment]
Hello @AndRossi,

Thanks for your hard work and the release of the new version, working perfectly now.

Just took the liberty to add the --neural argument to the `create `commands in the [Multilingual Engines page](https://github.com/ModernMT/MMT/wiki/Multilingual-Engines).

Thanks again :)

Fred

**Comment by davidecaroselli** [comment]
Hi @frdg , thanks for the contribution!
We are closing the issue now but, as always, feel free to re-open it if you need to!

Cheers,
Davide
