### ISSUE TITLE
Unexpected Error in Aligner Training step - aligner/en__ar.mdl -I 4' failed with exit code -9

### ISSUE THREAD

**Issue by mzeidhassan** [ModernMT/MMT#296]
Hi MMT team,

Finally, I got a machine with a GPU "Nvidia GTX 1080 TI". I installed MMT from source successfully.

Started the training, but got an exception error in step (Aligner Training 4 of 7). 

Here is the error log from "/runtime/default/logs"

Thanks in advance for your support!

Mohamed

> 2017-11-07 14:37:06,026 [INFO] - Training step "preprocess" completed in 184 s
2017-11-07 14:37:06,026 [INFO] - Training step "train_context" (4/9) started
2017-11-07 14:37:06,026 [DEBUG] - Shell exec: java -cp /home/mlearner/ModernMT/build/mmt-2.0.1.jar -Dmmt.home=/home/mlearner/ModernMT -Djava.library.path=/home/mlearner/ModernMT/build/lib eu.modernmt.cli.ContextAnalyzerMain -s en -t ar -i /home/mlearner/ModernMT/engines/default/models/context -c /home/mlearner/ModernMT/runtime/default/tmp/training/training_corpora
2017-11-07 14:37:06,662 main INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
2017-11-07 14:37:31,849 INFO  eu.modernmt.context.lucene.storage.CorporaStorage [main] Bulk insert of memory 1
2017-11-07 14:37:31,849 INFO  eu.modernmt.context.lucene.storage.CorporaStorage [main] Flushing index to disk. Pending updates: 1
2017-11-07 14:37:31,850 INFO  eu.modernmt.context.lucene.storage.AnalysisTask [pool-2-thread-1] Indexing bucket CorpusBucket{memory=1, direction=en → ar}
2017-11-07 14:37:56,649 [INFO] - Training step "train_context" completed in 50 s
2017-11-07 14:37:56,650 [INFO] - Training step "train_aligner" (5/9) started
2017-11-07 14:38:10,849 [DEBUG] - Shell exec: /home/mlearner/ModernMT/build/bin/fa_build -s /home/mlearner/ModernMT/runtime/default/tmp/training/aligner/merge.en -t /home/mlearner/ModernMT/runtime/default/tmp/training/aligner/merge.ar -m /home/mlearner/ModernMT/engines/default/models/aligner/en__ar.mdl -I 4
Creating vocabulary... DONE in 41.0318s
== Forward model training ==
Initial setup... 2017-11-07 15:36:28,815 [ERROR] - Unexpected exception
Traceback (most recent call last):
  File "/home/mlearner/ModernMT/cli/mmt/engine.py", line 480, in _build
    method(self, args, skip=skip, log=log_stream, delete_on_exit=self._delete_on_exit)
  File "/home/mlearner/ModernMT/cli/mmt/engine.py", line 293, in __call__
    self._f(*args, **kwargs)
  File "/home/mlearner/ModernMT/cli/mmt/engine.py", line 581, in _train_aligner
    self._engine.aligner.build(corpora, working_dir, log=log)
  File "/home/mlearner/ModernMT/cli/mmt/engine.py", line 78, in build
    shell.execute(command, stdout=log, stderr=log)
  File "/home/mlearner/ModernMT/cli/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
ShellError: Command '/home/mlearner/ModernMT/build/bin/fa_build -s /home/mlearner/ModernMT/runtime/default/tmp/training/aligner/merge.en -t /home/mlearner/ModernMT/runtime/default/tmp/training/aligner/merge.ar -m /home/mlearner/ModernMT/engines/default/models/aligner/en__ar.mdl -I 4' failed with exit code -9

**Comment by davidecaroselli** [comment]
Hi @mzeidhassan 

I suspect it is a RAM problem, good news is that with the latest commit of MMT **master**, you don't need Aligner anymore for your **neural** engine (it is still needed for phrase-based ones).
So, we will skip the Aligner training, resuming your interrupted training in order to avoid wasting time.

So, assuming you are in your `ModernMT home` and you're creating the `default` engine, first run:
```
echo '["clean_tms", "create_db", "preprocess", "train_context", "train_aligner"]' > runtime/default/tmp/training/checkpoint.json
```
Then resume your interrupted training adding the flag `--resume` to the exact same command you used for starting the process in the first place:
```
./mmt create [... same args as before ...] --resume
```
Now you should be able to complete the training. Once the engine has been creating edit the `engine.xconf` file in your `default` engine folder specifying that it should not try to load the aligner:
```xml
<node xsi:schemaLocation="http://www.modernmt.eu/schema/config mmt-config-1.0.xsd"
      xmlns="http://www.modernmt.eu/schema/config"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

   <engine source-language="..." target-language="..." type="neural">
      <aligner enabled="false" />
   </engine>

</node
```

You should be now able to start your engine. Let me know if the process worked as expected!

Cheers,
Davide

**Comment by mzeidhassan** [comment]
Hi @davidecaroselli ,

Thanks for your reply. I also doubted it was a RAM issue. I have just 16 GB right now on this new machine. Following the advice on this issue https://github.com/ModernMT/MMT/issues/255 by creating a SWAP space, I see that the aligner is still working since yesterday and it didn't crash which explains that it's a RAM issue indeed. 

It's really good news to know that we can skip alignment phase with the new neural decoder. I will follow your instructions and report back here.

Thanks again for your support!

Mohamed

**Comment by mfederico** [comment]
Would be cool if you could support MMT by sharing/tagging this:

https://www.linkedin.com/feed/update/urn:li:activity:6334036436743974912 <https://www.linkedin.com/feed/update/urn:li:activity:6334036436743974912>

Thanks!
Marcello

**Comment by mzeidhassan** [comment]
With pleasure, @mfederico! Done on LinkedIn!

**Comment by davidecaroselli** [comment]
Thank you @mzeidhassan !
Let me know if the training proceeded smoothly.

**Comment by mzeidhassan** [comment]
Hi @davidecaroselli ,

So, I followed your instructions and the training is running now. 

I am getting this message, but I believe this is normal.

`rner/ModernMT/build/lib/pynmt/nmmt/NMTEngineTrainer.py:186: UserWarning: self and other not broadcastable, but have the same number of elements.  Falling back to deprecated pointwise behavior.
  num_correct_t = pred_t.data.eq(targ_t.data).masked_select(targ_t.ne(Constants.PAD).data).sum()
/home/mlearner/ModernMT/build/lib/pynmt/nmmt/NMTEngineTrainer.py:186: UserWarning: self and mask not broadcastable, but have the same number of elements.  Falling back to deprecated pointwise behavior.
  num_correct_t = pred_t.data.eq(targ_t.data).masked_select(targ_t.ne(Constants.PAD).data).sum()
`

I have a couple of questions though:
1) Is there any idea to know when the training will end? or how long is it going to take? It doesn't say for example: "1st epoch completed" or any indicative message that shows the progress. 

2) How can I know for sure that MMT is using my GPU, not the CPU? I assume it would fail if GPU is not used when you use this command, right? `./mmt create en ar examples/data/train --neural --resume`. Am I right?

3) According to the [wiki page](https://github.com/ModernMT/MMT/wiki/Neural-Network-Configurations) , we can tweak the neural decoder's parameters by using 'config_file'. Does MMT ship with this config file? I couldn't locate it. Where can I find it so I can tweak it if needed?

4) Related the previous point, from your experience, do the default values set on that page give you the best translation quality? Or does it differ from a language to another? 

5) In the code of your file 'NMTEngineTrainer.py', the system should save a checkpoint after every 10000 steps? Can you add this as a parameter to the command line and change it for example to make it save a check point after every 5000 steps instead?


Thanks again for your support!

Mohamed

**Comment by mzeidhassan** [comment]
As for the second point above, when I run 'nvidia-smi' command, I see this, so I assume my GPU is working. 

![screenshot from 2017-11-10 13-35-00](https://user-images.githubusercontent.com/7589948/32677529-06f4825c-c61c-11e7-8772-ab5984da2bc9.png)

**Comment by AndRossi** [comment]
Hello @mzeidhassan,

I'm answering your questions one by one :)

1) Unfortunately, there is no easy way to estimate the training time. Our termination conditions depend on the performance of the engine on the validation set, which is not predictable.  
However, you can check the progress of your training in file `<your_mmt_home>/runtime/<your_engine_name>/logs/training.log`

2) I was going to suggest you to use  the `nvidia-smi` command. I'm glad you found it!  

3) MMT does not ship with any neural network configuration file: by default, it just uses the default value for each property. To tweak the network parameters, you need to create the configuration file from scratch.  On a second thought, maybe that part was not clear enough in the [wiki page](https://github.com/ModernMT/MMT/wiki/Neural-Network-Configurations), so I have edited it to make it more detailed. I have also added an example of valid configuration file that you can copy-paste and change to suit your needs. I hope this helps!

4) The 10000 value you have encountered is just a a cap value. The actual amount of steps after which a checkpoint is stored is the smaller between 10000 and the number of steps per epoch (which is generally much smaller).  You can check that in your `<your_mmt_home>/runtime/<your_engine_name>/logs/training.log` as well.

I hope this was useful :) 

Have a nice day!

Andrea

**Comment by davidecaroselli** [comment]
Hi @mzeidhassan 

so @AndRossi already has answered most most of your questions :)
Anyway I would like to be more precise on question (4). The cap Andrea was referring is true, but on the contrary is it common to have training set that exceed the cap, that is only a "safe" check, not intended to be a default value.

However you can choose the number of steps between checkpoints with the option `--checkpoint-steps`, and you can even change more parameters if you want: whenever you're not sure of all the available options, just type `./mmt create --help` and you will prompted with all the available options.

Have a nice weekend!

**Comment by mzeidhassan** [comment]
Thank you so much @AndRossi and @davidecaroselli  for your great and detailed answers. Good news is that the training has completed already :-) GPU makes a whole difference, really.

Here are the last lines of the training log:

`2017-11-12 06:37:25,340 [INFO] - Step 710000 (epoch: 4.17): [num_correct: 88397.00; 137920 src tok; 133002 tgt tok; acc:  66.46; ppl:   5.19; 6488 src tok/s; 6257 tgt tok/s] 
2017-11-12 06:37:26,569 [INFO] - Validation at step 710000: loss = 1.75164, perplexity = 5.76405, accuracy = 65.8908
2017-11-12 06:37:26,569 [INFO] - Validation perplexity at step 710000 (epoch 4.17): 5.764045; current best: 5.731336; stalled 10 times
2017-11-12 06:37:26,569 [INFO] - Optimizer learning rate after step 710000 (epoch 4.17) set to lr = 0.0119725
2017-11-12 06:37:26,569 [INFO] - Checkpoint at step 710000 (epoch 4.17): [num_correct: 8353549.00; 12827203 src tok; 12488244 tgt tok; acc:  66.89; ppl:   5.06; 6398 src tok/s; 6229 tgt tok/s]
2017-11-12 06:37:27,917 [INFO] - Checkpoint saved: path = /home/mlearner/ModernMT/runtime/default/tmp/training/onmt_model/checkpoint_710000 ppl = 5.76
2017-11-12 06:37:27,920 [INFO] - Train model END 189635.83s
2017-11-12 06:37:27,920 [INFO] - Copying checkpoint at /home/mlearner/ModernMT/runtime/default/tmp/training/onmt_model/checkpoint_610000
2017-11-12 06:37:27,920 [INFO] - Storing model... START
2017-11-12 06:37:50,225 [INFO] - Storing model END 22.30s
2017-11-12 06:37:50,746 [INFO] - Training step "train_decoder" completed in 189671 s`

It seems that MMT stops after "epoch 4.17". As far as I can remember, the default number of epochs is more than this, right? Why does it stop after epoch 4.17? Maybe, this is something that I don't understand yet, but I would appreciate your explanation of the numbers above.  Do you see any issues in the training phase?

I have just started loading the engine, but it's taking time now. I will keep you posted of my finding or any problems I may have. 

Thanks again for your support!

Best regards,
Mohamed

**Comment by mzeidhassan** [comment]
Just to confirm that the model has been loaded successfully after updating engine.xconf file. I hope you will have the time to answer my last question above and then we can close this.

Thanks a million Davide and Andrea for being always supportive!

Wish you a wonderful week ahead!

Best,
Mohamed

**Comment by AndRossi** [comment]
Hello @mzeidhassan, 

I'm glad that your neural training was successul!
As for the termination criterion, I refer you to issue #287, where this topic is being currently debated.

In particular, I think [Davide's comment](https://github.com/ModernMT/MMT/issues/287#issuecomment-343669078) explains pretty well what the current termination criterion works like :)

As you suggested I'm closing this issue now; of course if you need more information on this topic don't hesitate to reopen it.

Have a nice day!

Andrea
