### ISSUE TITLE
Compatibility with AWS P3 Instances (Nvidia Volta)

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#301]
I did not manage to install MMT on a AWS P3.

I used the Ubuntu CUDA 9 Deep Learning Amazon AMI.
It looks like MMT only support CUDA 8.
CUDA 9 is required for volta architectures.

It would be great to have a workaround

**Comment by davidecaroselli** [comment]
Good news: we tried MMT with CUDA 9 on AWS P3 instances and it works as expected. We also gained 2x during training. You don't have to perform any specific command, just follow the guide in [INSTALL.md](https://github.com/ModernMT/MMT/blob/master/INSTALL.md).

However, there are some minor issues: the startup for both training and runtime are oddly slow (11 minutes!). We spot the problem and it is an issue with pytorch-0.2.

It seems that building pytorch from source (latest commit in master branch) has solved the problem, but we are still investigating. We are confident that the next release of pytorch will finally solve these minor issues.

We'll keep you updated!

**Comment by davidecaroselli** [comment]
Good news (again): we just released new [MMT v2.1](https://github.com/ModernMT/MMT/releases/tag/v2.1) that uses **PyTorch 0.3.0** and **CUDA 9.1**.
We measured a boost in training speed of **more than 2x** on AWS P3 instances.

Updated instructions are available in our [INSTALL.md](https://github.com/ModernMT/MMT/blob/master/INSTALL.md).

Cheers
