### ISSUE TITLE
NMT and Context Vector

### ISSUE THREAD

**Issue by frdg** [ModernMT/MMT#306]
Hello!

I trained an NMT engine using different TMX sources (around 500 different) and translate sentences using the context vector returned by MMT.

I noticed that for a given sentence in my test data (medical type document) some banking vocabulary was used to translate certain words/expressions (from EN to FR, "lose interest" > "perdre des intérêts" instead of "se désintéresser", and "bond" > "obligation" instead of "lien"). Indeed, in the context vector returned by MMT a banking domain can be found. I tried removing irrelevant domains but keep having exactly the same translation.

A remark, it is true that the number of occurrences for these two expressions are greater in the banking material than it is in the medical material, but present nonetheless. 

Therefore, is the context vector still relevant for an NMT engine?

**Comment by EtienneAb3d** [comment]
Neural MMT is using only one sentence for the on-the-fly context adaptation. Looking at the new log that can now outputs these sentences, I often see 3 bad cases:
- no adaptation sentence found, the network works as a commonly trained network.. already good !
- when found, this sentence is not really appropriated, thus it's influence, if there is one, could produce a wrong effect
- if appropriated, it can be not sufficient to force the network to use the right words

As discussed in #287, I think there is many progress that can be done...

The principles are good, and Neural MMT is globally producing very good translations. I'm sure the MMT team will find wonderful algos to improve the on-the-fly retraining !
;-)

**Comment by davidecaroselli** [comment]
Hi @frdg 

as @EtienneAb3d described, our current implementation selects the best matching suggestion from the TranslationMemory and adapts the network on it. The Context Vector is used during the first phase of this process:

- We select N best-matching suggestions from the TM
- We sort them by matching score (50%) and context score (50%)
- We get only the first

The final result is that the Context Vector is fundamental to distinguish between 2 good suggestions that come from different domains. This implementation however does not filter-out not-in-context suggestions.

as @EtienneAb3d suggested, we are currently working on different implementations and trying to tune this process, but if you would like to play around a little bit it would be great to also have your feedback!

Let me know if there are some other issue I can help you with.

Have a nice weekend,
Davide

**Comment by frdg** [comment]
Hello @davidecaroselli,

Thank you for the answer, makes perfect sense.

@EtienneAb3d:
> The principles are good, and Neural MMT is globally producing very good translations.

I completely agree.

Thank you :)
