### ISSUE TITLE
Draft release crashes

### ISSUE THREAD

**Issue by mfederico** [ModernMT/MMT#31]
It took me some time to update the release of java to version 8 and to tell my computer to actually use it with 
> sudo update-alternatives --config java 
maybe some further instructions would be helpful. 

Then, while running 
> ./mmt create en it examples/data/train
the command crashes with the following message: 

=========== TRAINING STARTED ===========

ENGINE:  default
CORPORA: /home/marcello/Progetti/mmt/examples/data/train (3 documents)
LANGS:   en > it

INFO: (1 of 6) Corpora tokenization...                                 DONE (in 22s)
INFO: (2 of 6) Corpora cleaning...                                     DONE (in 0s)
INFO: (3 of 6) Context Analyzer training...                            DONE (in 2s)
INFO: (4 of 6) Language Model training...                              DONE (in 0s)
2016-01-08 00:52:19,721 [ERROR] - [Errno 8] Exec format error
Traceback (most recent call last):
  File "/home/marcello/Progetti/mmt/scripts/engine.py", line 286, in build
    self._lm.train(tokenized_corpora, self.target_lang, working_dir, log_file)
  File "/home/marcello/Progetti/mmt/scripts/mt/lm.py", line 117, in train
    self._train_lm(file, os.path.join(models_folder, lm), working_dir, log)
  File "/home/marcello/Progetti/mmt/scripts/mt/lm.py", line 144, in _train_lm
    shell.execute(command, stderr=log)
  File "/home/marcello/Progetti/mmt/scripts/libs/shell.py", line 42, in execute
    process = subprocess.Popen(cmd, stdin=stdin, stdout=stdout, stderr=stderr, shell=(True if isinstance(cmd, basestring) else False))
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
Traceback (most recent call last):
  File "./mmt", line 370, in <module>
    main()
  File "./mmt", line 346, in main
    main_create(argv[1:])
  File "./mmt", line 329, in main_create
    engine.build(corpora, debug=args.debug, steps=args.training_steps)
  File "/home/marcello/Progetti/mmt/scripts/engine.py", line 286, in build
    self._lm.train(tokenized_corpora, self.target_lang, working_dir, log_file)
  File "/home/marcello/Progetti/mmt/scripts/mt/lm.py", line 117, in train
    self._train_lm(file, os.path.join(models_folder, lm), working_dir, log)
  File "/home/marcello/Progetti/mmt/scripts/mt/lm.py", line 144, in _train_lm
    shell.execute(command, stderr=log)
  File "/home/marcello/Progetti/mmt/scripts/libs/shell.py", line 42, in execute
    process = subprocess.Popen(cmd, stdin=stdin, stdout=stdout, stderr=stderr, shell=(True if isinstance(cmd, basestring) else False))
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

**Comment by marcotrombetti** [comment]
@davidecaroselli 

Ti allego qui il contenuto del file di Marcello:

```
engines/default/logs/0000755000175000017530000000000012643667014014753 5ustar  marcellofamilyengines/default/logs/build.lm.log0000644000175000017530000000017312643667015017166 0ustar  marcellofamilyls: impossibile accedere a /home/marcello/Progetti/mmt/engines/default/temp/lm/temp/dict.*: File o directory non esistente
engines/default/logs/build.context.log0000644000175000017530000000137612643667014020247 0ustar  marcellofamily[main] INFO eu.modernmt.context.ContextAnalyzer - Rebuild ContextAnalyzer index...
[main] INFO eu.modernmt.context.lucene.ContextAnalyzerIndex - Adding to index document ibm.en
[main] INFO eu.modernmt.context.lucene.ContextAnalyzerIndex - Adding to index document europarl.it
[main] INFO eu.modernmt.context.lucene.ContextAnalyzerIndex - Adding to index document ibm.it
[main] INFO eu.modernmt.context.lucene.ContextAnalyzerIndex - Adding to index document microsoft.it
[main] INFO eu.modernmt.context.lucene.ContextAnalyzerIndex - Adding to index document microsoft.en
[main] INFO eu.modernmt.context.lucene.ContextAnalyzerIndex - Adding to index document europarl.en
[main] INFO eu.modernmt.context.ContextAnalyzer - ContextAnalyzer index rebuild completed in 2s.
```

**Comment by marcotrombetti** [comment]
Comunque mi sembra che non possiamo assumere che Ubuntu 14.04 funzioni in tutti i casi.

Vedi ad esempio #39

**Comment by davidecaroselli** [comment]
@mfederico  could you please send me a zip file with the entire engines folder, and the exact sequence of commands you run?

Can you also send me the version of your python? Just run 'python --version' in a terminal. Thanks!

**Comment by marcotrombetti** [comment]
Can we close this? 

@davidecaroselli has it been solved?

**Comment by davidecaroselli** [comment]
I close it for now because the bug is still not replicable. If you have more information about this problem, please reopen it.
