### ISSUE TITLE
Question: Matecat Post-Editing  score vs. TER?

### ISSUE THREAD

**Issue by mzeidhassan** [ModernMT/MMT#313]
Hello MMT team,

I am a bit confused about the output I get from './mmt evaluate" command.

Here is one I got from an engine I created.

`Matecat Post-Editing Score:
  MMT                        : 67.88 (Winner)
  Google Translate     : 27.98

BLEU Score:
  MMT                        : 79.47 (Winner)
  Google Translate     : 40.97

Translation Speed:
  MMT                         : 0.31s per sentence (parallelism 1.0x)
  Google Translate      : 0.50s per sentence (parallelism 10.0x)`

I believe the Post-Editing score is more or less like TER "Translation Error Rate score", right?

The confusion comes from the fact that - contrary to BLEU score -  a high TER score is actually bad because it means more post-editing is needed to make the translation close to the reference translation. 

Does Matecat Post-Editing Score" is simply the TER score? If yes, do you find the scores above strange? 

If it's different than TER, can you please explain the logic and how it's calculated? Is there a way to measure TER in case it's different from Matecat Post-Editing score?

Thanks,
Mohamed Zeid

**Comment by mfederico** [comment]
Hi,
the two scores work in the same direction (just see assigned winners).
Matecat score is a similarity score btw MT output and reference, thus the higher it is the less one needs to post-edit.


-------
Short from my mobile phone

**Comment by mzeidhassan** [comment]
Thanks @mfederico for your answer. I think this cloud be added to the FAQ in case others have the same question. Please feel free to close the issue.

Thanks again for your support!

**Comment by mfederico** [comment]
Sure we will add this to the FAQ.
