### ISSUE TITLE
Wrong word alignment model

### ISSUE THREAD

**Issue by nicolabertoldi** [ModernMT/MMT#317]
When training  word alignment model on huge training data, the alignment model is corrupted, contains NotANumber values, and has a huge dimension.
Unfortunately the training procedure does not thrown any exception.
The usage itself seems definitely correct, but the results could be inconsistent since the model is inconsistent.

**Comment by davidecaroselli** [comment]
Fixed with the latest master commit https://github.com/ModernMT/MMT/commit/09981f7d35c366d5446e50a65d23c157ad90fabc
