### ISSUE TITLE
REST API has no feature for ADD

### ISSUE THREAD

**Issue by LoekvanKooten** [ModernMT/MMT#325]
It would be great to be able to add new translations via the REST API instead of via the command line. This way translators can add new translations via the web interface on their client, instead of running all the way to the system admin.

**Comment by letconex** [comment]
Is this what you are looking for?
https://github.com/ModernMT/MMT/wiki/API-Add-to-Memory

**Comment by LoekvanKooten** [comment]
Aha, yes, that's it. For some reason I only noticed the part about TMX files, not the part about single entries. Thank you!
