### ISSUE TITLE
Improving Neural Machine Translation Models with Monolingual Data - Paper

### ISSUE THREAD

**Issue by mzeidhassan** [ModernMT/MMT#331]
Hello MMT team,

First, wish you all a wonderful and great New Year and more success in 2018.

I came across [this paper](http://www.aclweb.org/anthology/P16-1009) and I thought I should share it  with you.

Quoted from the paper:

> "In contrast to previous work, which combines NMT models with separately trained language models, we note that encoder-decoder NMT architectures already have the capacity to learn the same information as a language model, and we explore strategies to train with monolingual data without changing the neural network architecture. By pairing monolingual training data with an automatic backtranslation, we can treat it as additional parallel training data, and we obtain substantial improvements on the WMT 15 task English↔German (+2.8–3.7 BLEU), and for the low-resourced IWSLT 14 task Turkish→English (+2.1–3.4 BLEU), obtaining new state-of-the-art results. We also show that fine-tuning on in-domain
> monolingual and parallel data gives substantial improvements for the IWSLT 15 task English→German."

Thanks,
Mohamed

**Comment by mzeidhassan** [comment]
Thanks @mfederico for your kind reply and follow-up on my question. 
Glad to know that you are aware of it. Do you plan to add such feature in the future?

Kind regards,
Mohamed

**Comment by mfederico** [comment]
Hi,
tt looks to me like something advanced users can do by themselves. 
You train a system in the reverse direction, then you use it to translate monolingual data
and then you train your real system with all the available data. 
Best, 
Marcello
