### ISSUE TITLE
Wrong segmentation of Chinese text

### ISSUE THREAD

**Issue by cettolo** [ModernMT/MMT#336]
MMT should split Chinese texts at char level for internal processing. Instead, when a dot occurs in between Chinese chars, they are not separated. For example:

echo "保罗德朗" | java -Dmmt.home=/hardmnt/hltmt2/data/cettolo/ModernMT_v2.3 -Djava.library.path=/hardmnt/hltmt2/data/cettolo/ModernMT_v2.3/build/lib -cp /hardmnt/hltmt2/data/cettolo/ModernMT_v2.3/build/mmt-2.3.jar  eu.modernmt.cli.PreprocessorMain -s zh -t zh

properly generates: "保 罗 德 朗"

while:

echo "保罗.德朗" | java -Dmmt.home=/hardmnt/hltmt2/data/cettolo/ModernMT_v2.3 -Djava.library.path=/hardmnt/hltmt2/data/cettolo/ModernMT_v2.3/build/lib -cp /hardmnt/hltmt2/data/cettolo/ModernMT_v2.3/build/mmt-2.3.jar eu.modernmt.cli.PreprocessorMain -s zh -t zh

leaves the input as it is: "保罗.德朗"

**Comment by nicolabertoldi** [comment]
the reason of this issue is the following:
- any sequence of character including one dot is recognized as URL and is not splitted at all;
- this occurs if the characters are Chinese characters; and this should not  

a possible fix is under testing

**Comment by davidecaroselli** [comment]
This bug has been fixed in latest master branch (MMT v2.4).

Thanks for the report!
Davide
