### ISSUE TITLE
Exception: no model specified in /home/rdelafuente/mmt/engines/default/models/decoder/model.conf

### ISSUE THREAD

**Issue by menpente** [ModernMT/MMT#344]
I have trained a neural engine when trying to start the engine I get this error
 
**Exception: no model specified in /home/rdelafuente/mmt/engines/default/models/decoder/model.conf
2018-02-05 02:17:46,794 FATAL eu.modernmt.facade.ModernMT [main] Unexpected exception thrown by thread [main]
java.lang.NullPointerException**
 
I took a look at the model.conf file and content is:
 
**[models]
en__it**

I tried running the below as suggested offline by Davide, but it didn't work.

./mmt create en it examples/data/train/ --neural
./mmt start

 
 
I am attaching training and node logs. Thanks in advance for your help.

[node.log](https://github.com/ModernMT/MMT/files/1699418/node.log)
[training.log](https://github.com/ModernMT/MMT/files/1699419/training.log)

**Comment by davidecaroselli** [comment]
Hi @menpente 

that is really weird: from the logs I can say that the training just completed successfully, even more unexpected is the model.conf file. This is the bit of code that writes the file:
```python
with open(os.path.join(model_folder, 'model.conf'), 'w') as model_map:
            filename = os.path.basename(self.model)
            model_map.write('[models]\n')
            model_map.write('%s__%s = %s\n' % (self._source_lang, self._target_lang, filename))
```

So even if, let's say, there is a problem with the variable `filename`, the script should have printed at least the `=` char; something like this:
```
[models]
en__it = 
```

Anyways, let's try to fix the engine and let's check if it works. If you `ls` the decoder folder you should have something like this:
```bash
ls
model.conf  model.en__it.bpe  model.en__it.dat  model.en__it.meta  model.en__it.vcb memory
```
Change the `model.conf` file like so:
```
[models]
en__it = model.en__it
```

And try to run MMT again.

Cheers,
Davide

**Comment by menpente** [comment]
Hi Davide,

model.conf already looks like that...

**Comment by menpente** [comment]
I just tried running ./mmt start (on a fresh training) and now it starts ok... So maybe there was something corrupt with the previous training?

**Comment by davidecaroselli** [comment]
That's great! 

But I am confused. In the first post you said that the `model.conf` looked like this:
```
[models]
en__it
```
And that can definitely be the reason for the `NullPointerException`, but now you're saying that the `model.conf` looks like:
```
[models]
en__it = model.en__it
```
Which one is correct?

And you also said that:
> I tried running the below as suggested offline by Davide, but it didn't work.
> `./mmt create en it examples/data/train/ --neural`
> `./mmt start`

but now, if I understand correctly, it seems to work:

> I just tried running ./mmt start (on a fresh training) and now it starts ok... 

Davide

**Comment by menpente** [comment]
Hi Davide,

Sorry for the confusion. The model.conf for the first training was:

[models]
en__it

And produced the error reported initially. I took it from the top and did a fresh training, where model.conf looks like:

[models]
en__it = model.en__it

And the engine starts correctly. So I guess there was something wrong with the first training, but probably not worth investigating now?

**Comment by davidecaroselli** [comment]
Hi @menpente 

Yes, there was something very strange in the first training as I described in the first post. If it is no longer affecting the training I believe it could have been a temporary issue due to some misconfigurations.

I'm closing the issue for now, but if you experience this problem again please re-open it and attach the training.log and the exact error.

Thank you!
Davide
