### ISSUE TITLE
Neural engine won't work

### ISSUE THREAD

**Issue by MK-01** [ModernMT/MMT#345]
I tried all modes of installing ModernMT on a fresh installed Ubuntu 16.04 Ubuntu and on a Lubuntu system - the phrase based engine works fine, but the neural engine alway exits during training in phase 6 saying "invalid machine command (written memory dump)" (in German), even with the few en-it example files.  The machine is an AMD Phenom II X2 with 12 GB of memory and a Chinese variant of Geforce 960 with 4 GB of video memory. There is no difference if CUDA is recognized or not. Hard drive is a nearly empty 500 GB HD. Can someone give me a hint? I would really appreciate.

**Comment by davidecaroselli** [comment]
Hi @MK-01 

that seems to be an issue with something low-level like pytorch. If you could attach the training.log file I would be able to confirm that. In this case I can only suggest to:
1. Completely remove CUDA drivers and any pytorch version installed.
2. Install the latest CUDA 9 drivers from: [CUDA Toolkit 9.1 Download](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1604)
3. Install the latest PyTorch version from [pytorch.org](http://pytorch.org/): select Linux - pip - Python 2.7 - CUDA 9

Davide

**Comment by MK-01** [comment]
Hi Davide,

thank you for this. I just tried again on a Lubuntu installation, CUDA GPU not recognized (as I wrote that doesn't make any difference, and it didn't work. So here is the training.log:

[training.log](https://github.com/ModernMT/MMT/files/1703079/training.log)

Best regards 
Martin

**Comment by davidecaroselli** [comment]
As I suspected, the log just crashed unexpectedly: my guess is, as I suggested in my first post, there must be a hardware/driver/pytorch problem at very low-level code (C++ connector of the python code).

I am truly sorry, but I don't have any solution or hints on how to solve the problem. If you could somehow test the installation on a different GPU model, even for a short time, just for testing, you could at least verify that is related with that exact hardware.

Davide

**Comment by davidecaroselli** [comment]
Hi @MK-01 

I'm sorry we wasn't able to help you. I'm closing the issue for inactivity: if you have any update or you need support, please don't hesitate to re-open it.

Thank you,
Davide
