### ISSUE TITLE
Exposing REST API via Docker image

### ISSUE THREAD

**Issue by robertBrnnn** [ModernMT/MMT#346]
Hi folks,

I've been trying to run an engine via the rest API but within Docker, and can't find a way to make it stay up.

Run command:
`docker run -dt -v $(pwd)/data:/home/mmt/mmt/data -v $(pwd)/engines:/home/mmt/mmt/engines -p 8045:8045 modernmt/master ./mmt start -e en_de`

The mmt script starts the process separately and exits, and thus the container exits. 

Do you've any suggestions of how to run an engine within a detached Docker container, and expose it?

Thanks,
R.

**Comment by davidecaroselli** [comment]
I'm not an expert of docker actually, but my suggestion would be to configure ModernMT as a service so that it automatically start at container boot. This way you will be able to launch the container without specifying a command ad it should run indefinitely.

**Comment by robertBrnnn** [comment]
Hi @davidecaroselli 

Thanks for your reply.
Unfortunately, Docker containers can't handle systemd services. When you create Docker containers with a startup service, you specify it as the default runtime command. In the case of ModernMT the Dockerfile would be something like:

```
From modernmt/master

ADD engines /home/mmt/mmt/engines

CMD ["/home/mmt/mmt/mmt", "start", "-e", "ENGINE_NAME"]
```
This has the same limitation in that, the container will exit once that command completes. 
What I've done as a work around for now is:
`docker run -dt -v $(pwd)/data:/home/mmt/mmt/data -v $(pwd)/engines:/home/mmt/mmt/engines -p 8045:8045 modernmt/master bash -c "./mmt start -e en_de  && tail -f /dev/null"`

It's a dirty hack but it works, but if for some reason the engine dies the container will stay running, and there's no access to logs by running `docker logs`.

Ideally when running a service in a docker container you expect to get logs from the service by running `docker logs`, and furthermore you expect if the service dies the container will also terminate, that way you can set restart or recreation policies for the container.

Would it be possible to add a follow parameter to the `mmt start` command that follows the output from the engine startup process? That way if the process dies, the process would exit in error, thus killing the container.

Thanks for your support,
R.

**Comment by davidecaroselli** [comment]
Hi @robertBrnnn 

I see the point. I suggest to create a start script that acts more or less like an ubuntu service. MMT helps you in doing that by publishing its pid in the file `ModernMT/runtime/<engine_name>/node.pid` (in fact, this is how I configured my mmt service). The script should do something like this:
```bash
MMT_HOME=....

$MMT_HOME/mmt start

PID=`cat $MMT_HOME/runtime/default/node.pid`
while ps -p $PID &> /dev/null; do
   sleep 5
done
```

(I didn't test it so please double-check it before using it!)

**Comment by robertBrnnn** [comment]
Hi @davidecaroselli 

That works. I made a couple of changes to it so that we can have a single Dockerfile regardless of language pair, that uses an environment variable with the engine name. 

Thanks for you support, I'll close this issue so.
R.

**Comment by davidecaroselli** [comment]
I am glad to have been of some help!
