### ISSUE TITLE
translate_xliff script

### ISSUE THREAD

**Issue by michaelstolzenberg** [ModernMT/MMT#349]
Hi,
after the latest fix the translate_xliff script now works well, thanks for that, but I'm having another problem:
I would like to run the script on different engines but it seems that it only ever selects the default engine. Is there a way to select which engine to use?
Selecting the engine is possible when translating a single document using
`translate --batch --xliff`
so I guess the engine argument would just need to be accepted and passed through.

**Comment by nicolabertoldi** [comment]
you can specify the engine by specifying this parameter
"--engine ENGINE_NAME"

**Comment by michaelstolzenberg** [comment]
thanks, I must've missed that.

**Comment by davidecaroselli** [comment]
Hi @michaelstolzenberg 

you're right! I have just pushed a commit in master branch with the "-e" option for `translate_xliff`. Could you confirm it works as it should?

Davide

**Comment by davidecaroselli** [comment]
@nicolabertoldi we are talking about script `extras/translate_xliff`, not `mmt translate --xliff`, @michaelstolzenberg  is right about the missing option. Anyways, as I just wrote, it should be there now! :)

**Comment by michaelstolzenberg** [comment]
Wait, I'm trying to use this script to translate multiple files:
extras/translate_xliff
It doesnt take the arguments "-e" or "--engine".

**Comment by davidecaroselli** [comment]
@michaelstolzenberg you're right, the fix is now in the master branch, just run `git pull origin master` in ModernMT home and try again.

**Comment by michaelstolzenberg** [comment]
It works, thank you.

**Comment by mindaugasDEV** [comment]
Hi, @davidecaroselli 

I don`t succeed translating folder of files with the script.

After running commands `$ extras/translate_xliff /path/to/your/xliff/folder -e engine` or with default engine `$ extras/translate_xliff /path/to/your/xliff/folder` I get the following error message:

```
Traceback (most recent call last):
  File "extras/translate_xliff", line 8, in <module>
    from cli.libs import shell
ImportError: cannot import name shell
```
I am using latest 3.2 release. Translating one-file-at-the-time via `mmt translate --xliff` works fine, though.
