### ISSUE TITLE
Monolingual LM training data

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#35]
@mfederico 
What is the priority of supporting monolingual data for LM training.
MMT uses today only the target translation as LM.

**Comment by davidecaroselli** [comment]
This feature has been introduced with this commit: https://github.com/ModernMT/MMT/commit/d0478428c8234acbe75f545bcf08ef1f691f5bec

You can find it in the develop branch right now, it will be released with version 0.12 as expected.
