### ISSUE TITLE
Problem with segmentation in xliff translation

### ISSUE THREAD

**Issue by michaelstolzenberg** [ModernMT/MMT#350]
Hi,
there seems to be an issue with segmentation when translating sdlxliff files.
For example if I have a text file containing a list like this:
1. line one
2. line two
3. line three
4. line four
5. line five
6. line six

it could look like this in a sdlxliff file:
```
<source>
	<g id="31">
		1. line one2. line two3. line three4. line four5. line five6. line six	
	</g>
</source>
<seg-source>
	<g id="31">
		<mrk mtype="seg" mid="10">1.</mrk> 
		<mrk mtype="seg" mid="11">line one2.</mrk> 
		<mrk mtype="seg" mid="12">line two3.</mrk> 
		<mrk mtype="seg" mid="13">line three4.</mrk> 
		<mrk mtype="seg" mid="14">line four5.</mrk> 
		<mrk mtype="seg" mid="15">line five6.</mrk> 
		<mrk mtype="seg" mid="16">line six</mrk>
	</g>
</seg-source>
<target>
	<g id="31">
		<mrk mtype="seg" mid="10"/> 
		<mrk mtype="seg" mid="11"/> 
		<mrk mtype="seg" mid="12"/> 
		<mrk mtype="seg" mid="13"/> 
		<mrk mtype="seg" mid="14"/> 
		<mrk mtype="seg" mid="15"/> 
		<mrk mtype="seg" mid="16"/> 
	</g>
</target>
```
note that in `<source>` is the text as it is and in `<seg-source>` is the segmented text (the segmentation is bad but that's not important).

After translating the `<target>` looks like this:

```
<target>
	<g id="31">
		<mrk mid="10" mtype="seg">1.</mrk> 
		<mrk mid="11" mtype="seg">trans line one2.</mrk> 
		<mrk mid="12" mtype="seg">trans line two3.<mrk mid="13" mtype="seg">trans line three</mrk> 4.</mrk> 
		<mrk mid="14" mtype="seg">5.<mrk mid="15" mtype="seg">trans line five</mrk>6.</mrk> 
		<mrk mid="16" mtype="seg">trans line six</mrk>
	</g>
</target>
```

These nested tags are problematic. The segments in `<target>` should be identical to those in `<seg-source>`.
After looking at the node.log I noticed that the `<source>` part is passed to the translator without using the segmentation information in `<seg-source>` this might be the cause for the difference.

from the node.log:
`"GET /translate?q=%3Cg+id%3D%2231%22%3E1.+line+one2.+line+two3.+line+three4.+line+four5.+line+five6.+line+six%3C%2Fg%3E&source=de&target=en&priority=background"`

**Comment by davidecaroselli** [comment]
Hi @michaelstolzenberg 

I found the problem and I'm working on it. I'll let you know as soon as the bugfix will be available.

Thanks for your report!
Davide

**Comment by davidecaroselli** [comment]
Hi @michaelstolzenberg 

just pushed a fix for the issue, please try it and let me know if it works for you.

Cheers,
Davide
