### ISSUE TITLE
Question - MemoQ mqxliff support

### ISSUE THREAD

**Issue by mzeidhassan** [ModernMT/MMT#352]
Hi @davidecaroselli ,

I see that MemoQ is mentioned in 'translation.py' file. 

https://github.com/ModernMT/MMT/blob/3efd590ad85e1dbf5840a44c52dba9a5d5e9bb4f/cli/translation.py#L139

but it seems that the extras/translate_xliff script doesn't support translation of MemoQ files. 

Is there a way to translate MemoQ files using MMT?

Thanks,
Mohamed Zeid

**Comment by davidecaroselli** [comment]
Hi @mzeidhassan 

I think it was just a problem of file extension search. I just added `.mqxliff` together with `.xliff` and `.sdlxliff`. It should work now on `master` branch.

However please keep in mind that we do support only basic features of xliff and its "dialects", we do not support advanced, custom MemoQ file format features.

Let me know if you need further help.
Cheers,
Davide
