### ISSUE TITLE
Flexibility of language codes

### ISSUE THREAD

**Issue by michaelstolzenberg** [ModernMT/MMT#354]
When training an engine using TMX files the acceptance of language codes is very strict. Depending on the source of the corpus or the tool that generates it, it happens that sometimes the language codes, for example for english, would slightly differ.

For example it could be: "en-GB" "EN-GB" or just "en" or "EN"

It would be great if all of these were accepted.

Another thing is the "direction" of the translation. It would be helpful if an engine created to translate from source "en" to target "it" would also accept TMX files with source "it" and target "en".

**Comment by davidecaroselli** [comment]
Hi @michaelstolzenberg 

> For example it could be: "en-GB" "EN-GB" or just "en" or "EN"
> It would be great if all of these were accepted.

I see the point and I agree: you are not the first person that highlight this problem and I think that for TMXes we can work on a "normalization" of the language tag that accepts all mentioned forms.

> It would be helpful if an engine created to translate from source "en" to target "it" would also accept TMX files with source "it" and target "en".

This is already supported by MMT. Both during training and Memory import you can provide reversed TMs, these will be automatically "reversed" to the right direction.

Thanks for the report!
I'll let you know as soon as we will publish the improvement.

Cheers,
Davide

**Comment by davidecaroselli** [comment]
Hi @michaelstolzenberg 

This enhancement has been published in the latest `master` branch commit.

Thanks!
