### ISSUE TITLE
Issue with omitted spaces when translating sdlxliff files

### ISSUE THREAD

**Issue by michaelstolzenberg** [ModernMT/MMT#355]
I came across an issue when translating sdlxliff files.
When there are multiple segments in one trans-unit, sometimes there is a space between the segment tags that is omitted after the translation.

Like in this example between the first `</mrk>` and `<mrk mtype="seg" mid="2">`:

```
<source>Sentence one. Sentence two.</source>
<seg-source><mrk mtype="seg" mid="1">Sentence one.</mrk> <mrk mtype="seg" mid="2">Sentence two.</mrk></seg-source>
<target><mrk mtype="seg" mid="1">Translated sentence one.</mrk><mrk mtype="seg" mid="2">Translated sentence two.</mrk></target>
```

This is not noticable at first, but when you convert the sdlxliff back into its original file format it will result in a missing space there.

docx file (before translation):
Sentence one. Sentence two.

docx file (after translation):
Translated sentence one.Translated sentence two.

**Comment by davidecaroselli** [comment]
I'll work on that, thanks for the report: very clear and detailed!

Cheers,
Davide
