### ISSUE TITLE
Integration with self-hosted MateCat

### ISSUE THREAD

**Issue by Heeyoung-Ahn** [ModernMT/MMT#361]
Hi,
We hope to get some innovation in translation through CAT tool and NMT.
We are testing the MateCat as installation on our own server.
And we want to test MMT also.
Can I integrate a self-hosted MMT engine with self-hosted MateCat?

Thanks.

**Comment by davidecaroselli** [comment]
Hi @Heeyoung-Ahn 

Matecat is currently integrated with our Enterprise Edition only; you can use it both in cloud-based Matecat and self-hosted Matecat.
There is no connector for self-hosted MMT engine at the moment.

Thanks,
Davide
