### ISSUE TITLE
Protecting Substrings During Translation

### ISSUE THREAD

**Issue by robertBrnnn** [ModernMT/MMT#362]
Hi MMT team,

In issue https://github.com/ModernMT/MMT/issues/286 regarding protecting substrings that are part of the sentence i.e. using `<dnt>` tags alone won't work, the solution suggested is to use a single placeholder, with a tag.

I've trained an en-es engine using content with a placeholder for protected strings say XXXX. When translating the string: 
`A window that displays metrics for the entire XXXX<dnt 3 /> is available to XXXX<dnt 2 /> administrators with the XXXX<dnt 1 /> permission.`
The translated text is:
`Una ventana que muestra métricas para todo el XXXX<dnt 3 /> está disponible para<dnt 2 /> los administradores XXXX con<dnt 1 /> el permiso XXXX.`

As you can see this method doesn't work, and performs even worse when the source string contains other XML elements. 

The solution I have been working involves a fixed set of placeholders to represent a piece of non translatable text i.e. XXXA, XXXB, XXXC etc.
So the source string:
`A window that displays metrics for the entire XXXXA is available to XXXXB administrators with the XXXXC permission.`
gets correctly translated to:
`Una ventana que muestra métricas para toda XXXXA está disponible para los administradores XXXXB con el permiso XXXXC.`

This method however, doesn't work with en-zh or en-ja as the placeholders get translated, tokenized, or their case is changed i.e 
`XXXXA` becomes `XXXxa` or `XXX Xa` or `Xxxxa` and sometimes `XXXXC`  etc. 

This make it's quite difficult/impossible to replace the placeholders. I should add however, the translated sentence is linguistically correct, the only problem is the modification of the placeholders.

For reference I tested this same approach against a MMT 2.3 engine, which was trained without these placeholders, and it handled them correctly, there was a negligible amount of placeholders that were modified. 

Do you have any ideas why the issue is worse with MMT 2.4? 

Thanks,
R.

**Comment by davidecaroselli** [comment]
Hi @robertBrnnn 

let's make a test. Engines EN <> ES are backward compatible from 2.4 and 2.3. Can you please run the following test: translate the **exact source** file with the **exact same** engine (don't perform any re-training of any sort, use exactly the same engine folder not only the decoder).

Do the 2 files differ? If yes, can you please provide me the output of the two system on a single line with parameter `verbose=1`? I would like to inspect if the alignment information is the same.

**Comment by robertBrnnn** [comment]
Hi @davidecaroselli 

I assume you mean for my first method i.e.
`A window that displays metrics for the entire XXXX<dnt 3 /> is available to XXXX<dnt 2 /> administrators with the XXXX<dnt 1 /> permission.`?

So the translations are the same. 

On MMT 2.3 I get
`
{
    "status": 200,
    "data": {
        "decodingTime": 1916,
        "translation": "Ventana que muestra las métricas para toda la XXXX<dnt 3 /> disponible para<dnt 2 /> los administradores de XXXX con<dnt 1 /> el permiso XXXX.",
        "sourceWordCount": 19,
        "targetWordCount": 20,
        "translationTokens": [
            [
                "Ventana",
                " "
            ],
            [
                "que",
                " "
            ],
            [
                "muestra",
                " "
            ],
            [
                "las",
                " "
            ],
            [
                "métricas",
                " "
            ],
            [
                "para",
                " "
            ],
            [
                "toda",
                " "
            ],
            [
                "la",
                " "
            ],
            [
                "XXXX",
                ""
            ],
            [
                "<dnt 3 />",
                " "
            ],
            [
                "disponible",
                " "
            ],
            [
                "para",
                ""
            ],
            [
                "<dnt 2 />",
                " "
            ],
            [
                "los",
                " "
            ],
            [
                "administradores",
                " "
            ],
            [
                "de",
                " "
            ],
            [
                "XXXX",
                " "
            ],
            [
                "con",
                ""
            ],
            [
                "<dnt 1 />",
                " "
            ],
            [
                "el",
                " "
            ],
            [
                "permiso",
                " "
            ],
            [
                "XXXX",
                ""
            ],
            [
                ".",
                ""
            ]
        ],
        "sentenceTokens": [
            [
                "A",
                " "
            ],
            [
                "window",
                " "
            ],
            [
                "that",
                " "
            ],
            [
                "displays",
                " "
            ],
            [
                "metrics",
                " "
            ],
            [
                "for",
                " "
            ],
            [
                "the",
                " "
            ],
            [
                "entire",
                " "
            ],
            [
                "XXXX",
                ""
            ],
            [
                "<dnt 3 />",
                " "
            ],
            [
                "is",
                " "
            ],
            [
                "available",
                " "
            ],
            [
                "to",
                " "
            ],
            [
                "XXXX",
                ""
            ],
            [
                "<dnt 2 />",
                " "
            ],
            [
                "administrators",
                " "
            ],
            [
                "with",
                " "
            ],
            [
                "the",
                " "
            ],
            [
                "XXXX",
                ""
            ],
            [
                "<dnt 1 />",
                " "
            ],
            [
                "permission",
                ""
            ],
            [
                ".",
                ""
            ]
        ],
        "alignment": [
            [
                1,
                0
            ],
            [
                2,
                1
            ],
            [
                3,
                2
            ],
            [
                4,
                3
            ],
            [
                4,
                4
            ],
            [
                5,
                5
            ],
            [
                7,
                6
            ],
            [
                8,
                7
            ],
            [
                8,
                8
            ],
            [
                11,
                10
            ],
            [
                12,
                11
            ],
            [
                13,
                15
            ],
            [
                13,
                16
            ],
            [
                15,
                13
            ],
            [
                15,
                14
            ],
            [
                16,
                17
            ],
            [
                18,
                21
            ],
            [
                20,
                19
            ],
            [
                20,
                20
            ],
            [
                21,
                22
            ]
        ]
    }
}
`

On MMT 2.4 I get:
`
{
    "status": 200,
    "data": {
        "decodingTime": 1850,
        "translation": "Ventana que muestra las métricas para toda la XXXX<dnt 3 /> disponible para<dnt 2 /> los administradores de XXXX con<dnt 1 /> el permiso XXXX.",
        "sourceWordCount": 19,
        "targetWordCount": 20,
        "translationTokens": [
            "Ventana",
            "que",
            "muestra",
            "las",
            "métricas",
            "para",
            "toda",
            "la",
            "XXXX",
            "<dnt 3 />",
            "disponible",
            "para",
            "<dnt 2 />",
            "los",
            "administradores",
            "de",
            "XXXX",
            "con",
            "<dnt 1 />",
            "el",
            "permiso",
            "XXXX",
            "."
        ],
        "sentenceTokens": [
            "A",
            "window",
            "that",
            "displays",
            "metrics",
            "for",
            "the",
            "entire",
            "XXXX",
            "<dnt 3 />",
            "is",
            "available",
            "to",
            "XXXX",
            "<dnt 2 />",
            "administrators",
            "with",
            "the",
            "XXXX",
            "<dnt 1 />",
            "permission",
            "."
        ],
        "alignment": [
            [
                1,
                0
            ],
            [
                2,
                1
            ],
            [
                3,
                2
            ],
            [
                4,
                3
            ],
            [
                4,
                4
            ],
            [
                5,
                5
            ],
            [
                7,
                6
            ],
            [
                8,
                7
            ],
            [
                8,
                8
            ],
            [
                11,
                10
            ],
            [
                12,
                11
            ],
            [
                13,
                15
            ],
            [
                13,
                16
            ],
            [
                15,
                13
            ],
            [
                15,
                14
            ],
            [
                16,
                17
            ],
            [
                18,
                21
            ],
            [
                20,
                19
            ],
            [
                20,
                20
            ],
            [
                21,
                22
            ]
        ]
    }
}
`

Also FYI, I had to build a new Docker image to run the new 2.4 version of MMT and the `compile` script for vendor directory failed when downloading Kafka with this error:

```
Installing Kafka 0.10.2.1...

Traceback (most recent call last):
  File "./compile", line 350, in <module>
    run_all()
  File "./compile", line 315, in run_all
    install_kafka()
  File "./compile", line 300, in install_kafka
    install_apache_lib(kafka_apache_path, kafka_home)
  File "./compile", line 177, in install_apache_lib
    folder = untar(tar_destination, work_directory)
  File "./compile", line 61, in untar
    tar = tarfile.open(filename, 'r:gz')
  File "/usr/lib/python2.7/tarfile.py", line 1691, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python2.7/tarfile.py", line 1749, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file
```

I fixed it by downloading Kafka myself, and running `compile` script again, and it worked. So I think your compile script is broken, perhaps the URL is dead? It worked once Kafka was archive was there, so I assume it's an issue with downloading Kafka.

Thanks,
R

**Comment by davidecaroselli** [comment]
Hi @robertBrnnn 

so looking at the two translations, they look exactly the same (including tokenization and alignments). Let me try to explain what I'm trying to achieve. You said:

> Do you have any ideas why the issue is worse with MMT 2.4?

In order to answer your question I need to start from an example where **with the same model** the two systems behave differently (if you change the model doing a re-train, than it is possible that the new content made the translation worse and not MMT version). 

So to answer you question I need you to:
1. Setup the old MMT 2.3.
2. Setup the latest version in `master` branch freshly pulled.
3. Load the same exact engine with the two versions.
4. Find an example of translation where the two versions output is different.

From there, we can start debugging and see why the two versions have different behaviour.

Thanks,
Davide

**Comment by davidecaroselli** [comment]
"do-not-translate" feature has been finally introduced, please have a look at issue #385 for more details.

Thanks for the support @robertBrnnn ! I'm closing this issue in order to not create duplicates of the same problem. For further discussion please refer to issue #385
