### ISSUE TITLE
Training step #6 (Language Model Training) fails with code -11

### ISSUE THREAD

**Issue by mehtadhaval** [ModernMT/MMT#367]
When running `./mmt create` command, it fails with following error : 

```
2018-04-29 17:12:41,141 [DEBUG] - Shell exec: /data/mt/ModernMT/build/bin/vb_encode -v /data/mt/ModernMT/engines/en_es/models/decoder/vocab.vb -i /data/mt/ModernMT/runtime/en_es/tmp/training/lm/slm.temp/corpora | /data/mt/ModernMT/build/bin/create_slm --discount-fallback -o 5 -a 32 -q 8 --type trie --model /data/mt/ModernMT/engines/en_es/models/decoder/lm/background.slm -T /data/mt/ModernMT/runtime/en_es/tmp/training/lm/slm.temp --prune 0 1 2
temporary_directory:/data/mt/ModernMT/runtime/en_es/tmp/training/lm/slm.temp
temporary_arpa:/data/mt/ModernMT/runtime/en_es/tmp/training/lm/slm.temp/lm.arpa
=== 1/5 Counting and sorting n-grams ===
File stdin isn't normal.  Using slower read() instead of mmap().  No progress bar.
2018-04-29 17:28:33,227 [ERROR] - Unexpected exception
Traceback (most recent call last):
  File "/data/mt/ModernMT/cli/mmt/engine.py", line 482, in _build
    method(self, args, skip=skip, log=log_stream, delete_on_exit=self._delete_on_exit)
  File "/data/mt/ModernMT/cli/mmt/engine.py", line 294, in __call__
    self._f(*args, **kwargs)
  File "/data/mt/ModernMT/cli/mmt/phrasebased.py", line 334, in _train_lm
    self._engine.moses.lm.train(bicorpora + monocorpora, self._engine.target_lang, working_dir, log=log)
  File "/data/mt/ModernMT/cli/mmt/phrasebased.py", line 90, in train
    shell.execute_pipe([merge_command, slm_command], stdout=log, stderr=log)
  File "/data/mt/ModernMT/cli/libs/shell.py", line 101, in execute_pipe
    raise ShellError(str_cmd, returncode, stderr_dump)
ShellError: Command '/data/mt/ModernMT/build/bin/vb_encode -v /data/mt/ModernMT/engines/en_es/models/decoder/vocab.vb -i /data/mt/ModernMT/runtime/en_es/tmp/training/lm/slm.temp/corpora | /data/mt/ModernMT/build/bin/create_slm --discount-fallback -o 5 -a 32 -q 8 --type trie --model /data/mt/ModernMT/engines/en_es/models/decoder/lm/background.slm -T /data/mt/ModernMT/runtime/en_es/tmp/training/lm/slm.temp --prune 0 1 2' failed with exit code -11
```

OS : Ubuntu 16.04
24 CPUs, 96 GB Memory, MMT compiled from source
Phrase based engine. Training data size : ~19 GB

**Comment by mehtadhaval** [comment]
When I run the same again manually, it fails with 
```Segmentation fault (core dumped)```

**Comment by davidecaroselli** [comment]
Hi @mehtadhaval 

sorry for the late response. So you should try re-build from sources on your machine, just follow these instructions: [Installing from source](https://github.com/ModernMT/MMT/blob/master/INSTALL.md#option-3---installing-from-source).

Sometimes the binaries created for phrase-based make assumption on the hardware they're built on, so they can be hard to port on different HW. By compiling from scratch you will end up with bins 100% compatible with your system.

Let me know if this solves your issue.

Best,
Davide

**Comment by davidecaroselli** [comment]
Unfortunately seg-faults are the worse bugs to debug.
Another idea: while you are making the training, can you monitor your memory usage with `free`? I wonder if this could be a memory problem.

**Comment by mehtadhaval** [comment]
I am monitoring the memory but couldn't monitor it continuously. I'm right now trying a smaller dataset (~8GB compared to original 19GB) to see whether it works or not. If it works, I'll try to setup some tool to monitor the memory continuously. I'll be posting the results here tomorrow. Thanks for your quick reply.

**Comment by davidecaroselli** [comment]
That sounds great.
I suggest, before trying the 8G, try with `examples/data/train`: it will took few seconds and we will discover if it's a data problem or not.

**Comment by mehtadhaval** [comment]
Training completes successfully with `examples/data/train`.

**Comment by mehtadhaval** [comment]
Update : So it worked with 8GB data. Now I'm trying to import remaining data using `./mmt import`. 

Shouldn't 90GB of memory be enough to train a model on 19GB of data (i'd read that it needs around 1GB memory for 300MB of parallel data) ?

**Comment by davidecaroselli** [comment]
Hi @mehtadhaval 

from the log you shared, it seems that the system is still importing the content:
```
2018-05-11 01:42:56,537 INFO  native.sapt.SuffixArray [Thread-6236] Importing batch of 4184 sentence pairs.
2018-05-11 01:42:56,916 INFO  native.ilm.NGramStorage [Thread-6237] Importing batch of 1000 sentences.
2018-05-11 01:43:01,741 INFO  native.sapt.SuffixArray [Thread-6240] Importing batch of 1500 sentence pairs.
[...]
```

Are you sure you didn't attempt a (large) import before that? It seems that there are a large amount of sentences in the internal queue waiting to be imported.

**Comment by mehtadhaval** [comment]
@davidecaroselli  : 

I think so too, as earlier I had tried to import all the remaining data (~10 GB), so that is what might be taking time. Do you think if I let it run, it will complete successfully ? Also, given that I have 92GB memory and same amount of swap space, what is the approx size of data that I can train/import in an engine ?

**Comment by mehtadhaval** [comment]
Sorry for the late reply @davidecaroselli . 

I'm getting the following behavior : 
When I start the engine by `./mmt start`, it starts printing statements like following in the node logs : 

```
2018-05-21 22:27:17,025 INFO  native.ilm.NGramStorage [Thread-61] Importing batch of 1500 sentences.
2018-05-21 22:27:17,657 INFO  eu.modernmt.context.lucene.storage.CorporaStorage [Thread-3] Flushing index to disk. Pending updates: 2
2018-05-21 22:27:17,658 INFO  eu.modernmt.context.lucene.storage.AnalysisTask [pool-5-thread-4] Indexing bucket CorpusBucket{memory=6, direction=en → es}
2018-05-21 22:27:17,658 INFO  eu.modernmt.context.lucene.storage.AnalysisTask [pool-5-thread-3] Indexing bucket CorpusBucket{memory=7, direction=en → es}
2018-05-21 22:27:18,083 INFO  native.sapt.SuffixArray [Thread-62] Importing batch of 9146 sentence pairs.
2018-05-21 22:27:19,481 INFO  native.ilm.NGramStorage [Thread-63] Importing batch of 1000 sentences.
```

No matter how long do I let it run, it keeps printing likes like above in the logs. After sometime, it stops abruptly and when started, I see the same pattern.

**Comment by davidecaroselli** [comment]
Hi @mehtadhaval ,

do you have a backup of the just-created engine? I will suggest to restore the initial model and try first with a small import. If you succeed in importing it and, even after reboot, everything works as expected than you can proceed adding the rest of the data (maybe in smaller chunks for the larger ones).

Probably going a bit off-topic: why don't you try the Neural Engine? The phrase-based engine in ModernMT is no longer supported and all our effort goes toward neural engine, so you will probably obtain better results with the new version.

Davide

**Comment by mehtadhaval** [comment]
@davidecaroselli 
Updates on the issue I was facing : 

So if I start import for large dataset (~10 GB), the MMT engine shuts down without any logs in the `node.log` file. However, if I import smaller dataset (~3 GB), it is able to do import it (I have to let it complete the training for a few hours after the import process exits - till the time I stop getting `Importing batch of ...` line in the node.log file). I was wondering what could be the reason it is failing for large dataset.

re: Neural engine : I'd tried setting it up earlier, but was stuck with some error. I don't recollect what was the issue I was facing, so I'll try setting it up and train it with same amount of data.

**Comment by mehtadhaval** [comment]
@davidecaroselli  : 

I had following questions : 
1). I see that when the above mentioned engine is running (trained with ~19GB of dataset), it is taking up around 43 GB of RAM. My end goal is to ultimately run a multi language translator (from English to around 10 languages - all having approx same size of dataset). How would I calculate size for such a machine (or a cluster of machine) ?
2). I'm also looking into creating a neural engine too, are there any hardware requirements for the same ? And will it give me any benefit over the Phrase-based engine I currently have (in terms of memory usage, etc) ?

Thanks for the support. If you feel these questions doesn't belong to this forum, can you point me to the right forum ?

**Comment by davidecaroselli** [comment]
Hi @mehtadhaval 

> So if I start import for large dataset (~10 GB), the MMT engine shuts down without any logs in the node.log file. However, if I import smaller dataset (~3 GB), it is able to do import it [...]

I have an answer for that: MMT performs data-cleaning for imported TMs, and it uses RAM depending on the size of the TM. Because real customer TMXes are usually 100.000-1.000.000 lines, this is not a problem. For a TMX of 19G (or even 19 TMs of 1G in the same moment) there is the chance that the JVM goes out of RAM and the process is killed.

> 1). I see that when the above mentioned engine is running (trained with ~19GB of dataset), it is taking up around 43 GB of RAM. My end goal is to ultimately run a multi language translator (from English to around 10 languages - all having approx same size of dataset). How would I calculate size for such a machine (or a cluster of machine) ?

If you're planning to use a phrase-based engine, you will need 10 machines each one with an engine for one language direction. If the training data size is similar, then expect to have roughly the same RAM requirements.

> 2). I'm also looking into creating a neural engine too, are there any hardware requirements for the same ? And will it give me any benefit over the Phrase-based engine I currently have (in terms of memory usage, etc) ?

I recommend to switch to Neural Engine simply because their translation quality is much better than phrase-based.

In terms of hardware requirements you will need less RAM (and more important it will not grow linearly with the data imported), you will be able to have a single engine with multiple language support (so no more 10 machines for 10 languages).

**But** you will need to install a GPU on your server. I recommend a nVIDIA GTX1080Ti, it is the best compromise between cost and performance.
If you have no experience in Neural Nets, I suggest to "play" a little bit before going in production and experimenting yourself the boost in quality you can get - sometimes it can be tricky to obtain the best performances, and you will need a number of attempts searching for the best Network paramenters and data-cleaning strategies.

Good luck ;)

**Comment by davidecaroselli** [comment]
Hi @mehtadhaval 

I'm closing this issue for now because I think the issue has been answered and we were going a bit off-topic. If you have any other info about this topic, please feel free to re-open it. If you want more info on the Neural engine please open a different issue with a better explaining name.

Thanks for your contribution,
Davide

**Comment by mehtadhaval** [comment]
Sure. Thanks for the help.
