### ISSUE TITLE
Start new engine

### ISSUE THREAD

**Issue by sdlmw** [ModernMT/MMT#371]
Hi @davidecaroselli,

I recently completed the EN->FR engine. Engine position in:/MT-work/Corpus/en-US_fr-FR/Output,
I use the command: **./mmt start -e /MT-work/Corpus/en-US_fr-FR/Output**. The order will be stuck in 
“Starting MMT engine '/MT-work/Corpus/en-US_fr-FR/Output'...”. 
But，i moved the engine to the MODERNMMT default directory. This command can be executed successfully.
So have you ever met a problem like this? Or is there a suggestion for me to try.

Thanks

**Comment by davidecaroselli** [comment]
@sdlmw thanks for having spotted this bug!
