### ISSUE TITLE
Incremental training

### ISSUE THREAD

**Issue by sdlmw** [ModernMT/MMT#372]
Hello！

I've finished an engine， en->fr.  I try to translate some sentences，and use the “ ./MMT add ”command to modify the translation results. When I translate this sentence again。I did get the result of the modification.
But，I try to translate a similar sentence, or a word，I did not get the ideal result, the translation of some words is still the original translation results。

So I want to know, every time I via “./mmt add“  command to modify results, how to make changes to the engine。 Does the engine go back to train，Or is it just like a dictionary that stores the translation results of this sentence?

Also, if I need to do an incremental update on my previous engine, is there an introduction?

Thanks

**Comment by davidecaroselli** [comment]
Hi @sdlmw ,

the steps you followed are 100% correct. To add new data to the engine you can use:
- `mmt add` to add a single contribution
- `mmt import` to import an entire TMX file

The way however the adaptation works is searching for sentences similar to the one you submitted. So there is the chance that if you ask for a translation of a sentence that is not that similar to the one you have added (but has only very few words in common), MMT won't pick it up for adaptation. This is done to avoid few de-contextualized samples make the engine unstable. You should provide more samples from a context (i.e. a TMX with many samples of the words you are focusing on) to start see a more robust adaptation.

I hope this helps, if you have any other questions don't hesitate to write them here!

Davide

**Comment by sdlmw** [comment]
Thank you for your reply, I think I have understood, thank you！@davidecaroselli
