### ISSUE TITLE
fa_build crashes during aligner phase

### ISSUE THREAD

**Issue by mzeidhassan** [ModernMT/MMT#374]
Hi @davidecaroselli ,

Hope it's all well with you.

I was trying to train an EN-AR engine and it keeps failing during aligner phase. See screen shot below.
![fa_build](https://user-images.githubusercontent.com/7589948/40338303-93afb430-5d31-11e8-8254-f4a3e15ebe52.png)

Please note that I managed to train the same exact data with OpenNMT without any problems. So, I am not sure why it's failing. This machine has 47G RAM, and 8 cores. 

This is what I see in the training.log. 

> 2018-05-21 16:48:46,126 [INFO] - Training step "train_context" completed in 0 s
2018-05-21 16:48:46,126 [INFO] - Training step "train_aligner" (5/10) started
2018-05-21 16:52:28,466 [DEBUG] - Shell exec: /opt/Arabic_MMT/MMT/build/bin/fa_build -s /opt/Arabic_MMT/MMT/runtime/default/tmp/training/aligner/merge.en -t /opt/Arabic_MMT/MMT/runtime/default/tmp/training/aligner/merge.ar -m /opt/Arabic_MMT/MMT/engines/default/models/aligner/en__ar.mdl -I 4
Creating vocabulary... DONE in 132.457s
== Forward model training ==
Initial setup... DONE in 746.647s
Iteration 1:
	Computing alignments... DONE in 744.379s
	Optimizing diagonal tension... DONE in 0.125398s
	Normalizing translation table... DONE in 64.2402s
Iteration 2:
	Computing alignments... 2018-05-21 18:05:02,712 [ERROR] - Unexpected exception
Traceback (most recent call last):
  File "/opt/Arabic_MMT/MMT/cli/mmt/engine.py", line 482, in _build
    method(self, args, skip=skip, log=log_stream, delete_on_exit=self._delete_on_exit)
  File "/opt/Arabic_MMT/MMT/cli/mmt/engine.py", line 294, in __call__
    self._f(*args, **kwargs)
  File "/opt/Arabic_MMT/MMT/cli/mmt/engine.py", line 588, in _train_aligner
    self._engine.aligner.build(corpora, working_dir, log=log)
  File "/opt/Arabic_MMT/MMT/cli/mmt/engine.py", line 79, in build
    shell.execute(command, stdout=log, stderr=log)
  File "/opt/Arabic_MMT/MMT/cli/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
ShellError: Command '/opt/Arabic_MMT/MMT/build/bin/fa_build -s /opt/Arabic_MMT/MMT/runtime/default/tmp/training/aligner/merge.en -t /opt/Arabic_MMT/MMT/runtime/default/tmp/training/aligner/merge.ar -m /opt/Arabic_MMT/MMT/engines/default/models/aligner/en__ar.mdl -I 4' failed with exit code -11

**Comment by nicolabertoldi** [comment]
hi @mzeidhassan 
as you probably know fa_build is very RAM-consuming. Maybe the 47Gb are not enough for your corpus, or maybe another process consume portion of the RAM.
Just to ensure that this is the issue could you please try with a sub-portion of the merge files, so we can exclude other possible problems?

How big are your merge.x files? how many tokens? how many types?

**Comment by mzeidhassan** [comment]
Adding Swap space fixed it for now. I believe the Aligner step takes up so much memory. Hope there is a way to tweak it. Please feel free to close this issue. Thanks!
