### ISSUE TITLE
Is there a remanence effect in the NMT translation process ?

### ISSUE THREAD

**Issue by EtienneAb3d** [ModernMT/MMT#378]
I sent 3 times exactly the same sentence. The first "boucle surmoulée" wasn't properly translated by "overcast loop", while the 2 others was well translated by "ready-made loop".

Remark: in the experiment, I changed the used context, but the first and the third was obtained exactly in the same condition. As you can see, all are using the same exact example retrieved from the memory, with exactly the same score. 

Is this a simple kind of random effect, or did you already see such a remanent effect in your own experiments ?

An other question : how to understand the score of 0.46, with this exact example ?

```
Translation received from neural decoder:
   sentence = la boucle surmoulée doit , là encore , se situer sous les lames .
   translation = The overcast loop must , again , be beneath the slats .
   suggestions = [
      ScoreEntry{memory=17, sentence=La boucle surmoulée doit , là encore , se situer sous les lames ., translation=Again , the ready-made loop must be located under the slats ., score=0.459987}
   ]
Translation received from neural decoder:
   sentence = la boucle surmoulée doit , là encore , se situer sous les lames .
   translation = Again , the ready-made loop must be located under the slats .
   suggestions = [
      ScoreEntry{memory=17, sentence=La boucle surmoulée doit , là encore , se situer sous les lames ., translation=Again , the ready-made loop must be located under the slats ., score=0.459987}
   ]
Translation received from neural decoder:
   sentence = la boucle surmoulée doit , là encore , se situer sous les lames .
   translation = Again , the ready-made loop must be located under the slats .
   suggestions = [
      ScoreEntry{memory=17, sentence=La boucle surmoulée doit , là encore , se situer sous les lames ., translation=Again , the ready-made loop must be located under the slats ., score=0.459987}
   ]
```

**Comment by davidecaroselli** [comment]
It should not :) so if it's there it's definitely a bug.

Can you please try to request the same translation, same context 3 times right after the engine starts?

**Comment by davidecaroselli** [comment]
An outcome similar to the other issue you posted: we have completely re-written the neural network bit, and this problem seems to be solved now.

Thanks for the report, and please feel free to re-open the issue if you find a similar bug in this new version.
