### ISSUE TITLE
UNK token training in neural engine

### ISSUE THREAD

**Issue by patelrajnath** [ModernMT/MMT#379]
I was looking into the vocab creation code. I think it would be better to prune the vocabulary (also enabling to add unk tokens in the training corpora) of nmt-model either based on max-vocab-size or word-frequency. I can see there are options to provide "--max-vocabulary-size" and "--vocabulary-prune" but I don't see if they are being used. Please correct if I got it wrong.

**Comment by patelrajnath** [comment]
My mistake. They are being used during BPE creation (usually I guess we use them while creating vocab). I was looking at the code (in neural.py module) where it is creating dictionaries and converting word-to-index for neural training.

**Comment by davidecaroselli** [comment]
Hi @patelrajnath and sorry for the very late reply :)
As you already found out, yes: we do pruning during BPE creation.

If you need any other clarification, don't hesitate to ask!

**Comment by patelrajnath** [comment]
Any suggestion for the value of --vocabulary-prune?

**Comment by davidecaroselli** [comment]
Yep, in our training we usually use 0.9999.
However it of course really depends on the training data size. For medium-small sets I suggest not to use it. If your data set is several houndred of thousands of source words than that threshold will help for sure.
