### ISSUE TITLE
Model Creation Crash - 2B words corpus (17GB)

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#38]
tail -n 10000 -f build.tm.log
```
INITIAL PASS 
.................................................. [50000]
.................................................. [100000]
.................................................. [150000]
--- continue
.................................................. [16750000]
.................................................. [16800000]
.................................................. [16850000]
.................................................. [16900000]
..................................Error in line 16934554
The third objective is urban and rural development, within the scope of a balanced territorial policy.
```

Data available on Amazon (MMT High Performance instance, requires Translated pem)

**Comment by cettolo** [comment]
Marco

l'errore pare verificarsi durante la prima lettura da parte di fast_align dei dati paralleli preparati durante il pre-processing.

Se il problema è ancora irrisolto, puoi darmi il link ai dati e alla macchina che lo hanno causato?

Mauro

**Comment by marcotrombetti** [comment]
@cettolo questo we ho fatto train dei corpus singoli e nessuno ha dato problema.

Ora sto rifacendo il corpus (17GB) facendo il log esteso.
Se persiste ti mando link.

**Comment by davidecaroselli** [comment]
Thanks Mauro, changed assignee to you.

**Comment by marcotrombetti** [comment]
Quick update:
The model run of space and I restarted it with more storage.
It used 5x the corpus size, docs where saying 4x. Doc updated.

Result expected tomorrow at 4pm.

**Comment by marcotrombetti** [comment]
Trained completed in 15 hours.
I think it was just a disk space problem not notified. I updated The docs.

**Comment by cettolo** [comment]
bene (a parte la discrepanza sulla dimensione attesa)
