### ISSUE TITLE
Determine sizing of a neural and phrase based engine

### ISSUE THREAD

**Issue by mehtadhaval** [ModernMT/MMT#380]
I have following questions re: determining sizing of neural and phrase based engine : 

1. How do I determine the size of a neural engine (RAM, GPU specs and Disk space), given "x" GBs of parallel training corpus. - My use case is to train an engine with source as English and Target as multiple languages.

2. I already have a phrase based engine created for 19GB of data. I see that when I start an engine, it's occupying ~40 GB of memory. However, it needs ~200GB of disk space (under `mmt/engines/<engine_name>/models`). Is all of it required, or can I delete some of it without affecting the performance of the engine ?

**Comment by nicolabertoldi** [comment]
1. ModernMT neural model has always the same size independently from the size of the training corpus. If you use the defaults, the model approximately requires during translation:
- ~700M of disk space (per each language)
- ~2Gb of GPU RAM
- ~4Gb of RAM (resident)

During training:
- there is an additional usage of disk space, which is proportional to the training size. It is easy for you measuring the proportionality rate, which is (very) roughly 5 times the size of the training corpus.
- all available GPU RAM is used. 

2. we do not support anymore the phrase-based engine; however, all files are needed, and you cannot delete anything.

Please feel free to close the issue, if you do not have further questions.

**Comment by nicolabertoldi** [comment]
I close the issue,
but  do not hesitate to re-open if needed.
