### ISSUE TITLE
Tag Projection

### ISSUE THREAD

**Issue by nonsequitir** [ModernMT/MMT#383]
Hi there - I'm working with complex documents feature densely tagged sentences (sometimes up to 4-40+ tags) and was wondering if the tags-projection method is 1. Language specific or 2. whether it can be tuned/trained somehow.  Is there any information about this feature before I dive in and study the code?  Many thanks!

**Comment by davidecaroselli** [comment]
Hi @nonsequitir 

the tag projection feature is a 2-steps process:
1. First the system computes the **alignment** between the source and the target sentence with FastAlign model.
2. Then the tags are **projected** with some hard-coded heuristics using the computed alignment.

The first step uses the aligner model, so this step is a classic machine-learning task. The second part is hard-coded into this class: [XMLTagProjector.java](https://github.com/ModernMT/MMT/blob/master/src/textprocessing/src/main/java/eu/modernmt/processing/xml/XMLTagProjector.java)

**Comment by nonsequitir** [comment]
Awsome, I see that now.  Thanks @davidecaroselli !

**Comment by davidecaroselli** [comment]
I'm closing this issue for now.
If you have any other question or something you want to discuss, please don't hesitate to re-open it!
