### ISSUE TITLE
Failed to create engine using tmx files

### ISSUE THREAD

**Issue by Sinantra** [ModernMT/MMT#384]
Hi,
I am a beginner to your program, and I am trying to create an engine using tmx files. When I type:

./mmt create en tr examples/data/train/en_TR

I get an error message saying:

ENGINE:  default
BILINGUAL CORPORA: 2 documents
MONOLINGUAL CORPORA: 0 documents
LANGS:   en > tr

INFO: (1 of 6) Corpora cleaning...                                    
ERROR Unexpected exception:
	Command 'java -Xmx3550m -cp /home/sinan/Downloads/mmt/build/mmt-2.4.jar -Dmmt.home=/home/sinan/Downloads/mmt -Djava.library.path=/home/sinan/Downloads/mmt/build/lib eu.modernmt.cli.CleaningPipelineMain -s en -t tr --output /home/sinan/Downloads/mmt/runtime/default/tmp/training/clean_corpora --input /home/sinan/Downloads/mmt/examples/data/train/en_TR' failed with exit code 1

Traceback (most recent call last):
  File "./mmt", line 846, in <module>
    main()
  File "./mmt", line 792, in main
    actions[command](args)
  File "./mmt", line 186, in main_create
    training.start()
  File "/home/sinan/Downloads/mmt/cli/training.py", line 63, in start
    self._builder.build(self)
  File "/home/sinan/Downloads/mmt/cli/mmt/engine.py", line 402, in build
    self._build(resume=False, listener=listener)
  File "/home/sinan/Downloads/mmt/cli/mmt/engine.py", line 482, in _build
    method(self, args, skip=skip, log=log_stream, delete_on_exit=self._delete_on_exit)
  File "/home/sinan/Downloads/mmt/cli/mmt/engine.py", line 294, in __call__
    self._f(*args, **kwargs)
  File "/home/sinan/Downloads/mmt/cli/mmt/engine.py", line 526, in _clean_tms
    args.bilingual_corpora = self._engine.cleaner.clean(args.bilingual_corpora, folder, log=log)
  File "/home/sinan/Downloads/mmt/cli/mmt/processing.py", line 80, in clean
    shell.execute(command, stdout=log, stderr=log)
  File "/home/sinan/Downloads/mmt/cli/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
cli.libs.shell.ShellError: Command 'java -Xmx3550m -cp /home/sinan/Downloads/mmt/build/mmt-2.4.jar -Dmmt.home=/home/sinan/Downloads/mmt -Djava.library.path=/home/sinan/Downloads/mmt/build/lib eu.modernmt.cli.CleaningPipelineMain -s en -t tr --output /home/sinan/Downloads/mmt/runtime/default/tmp/training/clean_corpora --input /home/sinan/Downloads/mmt/examples/data/train/en_TR' failed with exit code 1

My tmx files contain both english and turkish texts with some tags and I am sure that they are encoded in UTF-8 format. I've read another issue about a similar problem and in that case you said the date and time format in the tmx file was wrong. So, checked date and time in my tmx files they looked OK.

By the way, I can create engines using monolingual parallel text files without any errors.

Can you please help me solve this problem?

Thank you.

**Comment by davidecaroselli** [comment]
Hi @Sinantra , and welcome to ModernMT! :)

can you please upload here the log file in `/home/sinan/Downloads/mmt/runtime/default/logs/training.log`?

**Comment by Sinantra** [comment]
Thanks for the quick response:)

Log file:
[training.log](https://github.com/ModernMT/MMT/files/2127684/training.log)

**Comment by davidecaroselli** [comment]
Here's the problem (from training.log):
```
Exception in thread "main" java.lang.IllegalArgumentException: EN-US
```

Right now ModernMT applies a strict check on languages (we plan to be more "elastic" in the future), and a language must match this format:
```regex
[a-z]{2}(-[A-Z]{2})?
```

So.. basically, you have to transform "EN-US" in "en-US".

**Comment by davidecaroselli** [comment]
Actually, I'm planning to work on this asap. Meanwhile, if you can, just replace the language tag as I mentioned: it should be much faster than waiting for me :)

**Comment by Sinantra** [comment]
Ok then, I will replace the language tag as you mentioned :)
Thank you.

**Comment by Sinantra** [comment]
I changed the language tags and it worked. I also had to change TR to tr-TR.
Thanks again for your help.

**Comment by davidecaroselli** [comment]
Hi @Sinantra ,

this has been solved in the new MMT master branch.
Thanks for your support and patience.
