### ISSUE TITLE
Best way to feed tags

### ISSUE THREAD

**Issue by LoekvanKooten** [ModernMT/MMT#389]
What's the best way to feed tags to ModernMT when adding translations? Currently they are "hard-fed" as <someinfo>, ＜someinfo＞ or ≪someinfo≫, but this is probably not a good idea?

**Comment by davidecaroselli** [comment]
Hi @LoekvanKooten 

if you mean XML tags, than it is very simple: just embed them in text as the already are. For example this is a valid query for ModernMT:
```bash
./mmt translate "This is an <b>example</b>"
```

**Comment by LoekvanKooten** [comment]
Thank you! What would you advise for other tags like {}? Leave them as is, leave them out or convert them to <>?

**Comment by davidecaroselli** [comment]
It really depends on what you want to achieve.

Technically speaking, the only valid XML tags are surrounded by "<" and ">", and no other symbol is accepted.

If you intend "tags" on a more broad definition, like `[this]` and `{this}` or even `${this}`, than my advice is still to keep them as they are then if you are experiencing some problems, try to find out a better solution (like transforming all of them in XML for example)

**Comment by LoekvanKooten** [comment]
Thank you very much for the advice!

**Comment by LoekvanKooten** [comment]
@davidecaroselli  What if I have two kinds of tags and want ModernMT to distinguish them? I can feed one pair as <>. How should I feed the other pair (for example: [])? Or is this not yet possible? When will it be possible?

**Comment by davidecaroselli** [comment]
It depends on what you mean by "distinguish". Do the only _tags_ that ModernMT recognize and handle differently are XML tags, and XML tags are well defined (basically like `<this>`, `</this>` or `<this />`).

These tags are (1) **removed** from the text, that is then (2) **translated** without these tags and finally the tags are (3) **projected** back from the source text to the translation.

If you have different "tags" (more broadly definition) that you wish to be handled like this, I suggest to encode somehow these tags with XML and then, decode back when you obtain the translation.
For example, let's say that you have this text:
```
This is [tag1] an {tag2} example <tag3>
```
You can transform this text to:
```
This is <tag type="square" text="tag1" /> an <tag type="curly" text="tag2" /> example <tag type="xml" text="tag3" />
```

Then let MMT translate it (please note: `<tag type="square" text="tag1" />` is a **single** XML tag, and won't be broken by ModernMT in any way) and then re-process the result to reconstruct the original tags.

Hope this helps!

**Comment by LoekvanKooten** [comment]
@davidecaroselli This works perfectly! Thank you so much!
