### ISSUE TITLE
Non-Amazon Ubuntu 14.04.2 LTS - Java Error 

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#39]
I got the original ISO of Ubuntu 14.04 LTS.
I installed in on a VirtualBox VM
I followed the instructions on INSTALL.md (no errors)

It trains the model, **but it crashes on translation.**

See screenshot:
<img width="1034" alt="schermata 2016-01-10 alle 00 04 24" src="https://cloud.githubusercontent.com/assets/9898003/12218903/15ab51a8-b72e-11e5-8b9c-5d23f55345ea.png">

**Comment by alessandrocattelan** [comment]
Confirm issue on Ubuntu (VBox)

    "error": {
        "message": "Could not initialize class eu.modernmt.network.uuid.UUIDSequence",
        "type": "NoClassDefFoundError"
    }

![screenshot from 2016-01-10 17 09 29](https://cloud.githubusercontent.com/assets/13222990/12222444/23ea946a-b7bd-11e5-9430-6e5a1604a9cf.png)
