### ISSUE TITLE
Obnoxious terms

### ISSUE THREAD

**Issue by LoekvanKooten** [ModernMT/MMT#395]
Wrong translations of some terms, especially the ones written with a starting capital in English, can be very obnoxious and are very difficult to get rid of even when correcting them dozens of times. Is there a way to tell ModernMT that for the time being, it should really adhere to the term as it is being translated now?

**Comment by nicolabertoldi** [comment]
Surely some term can be wrongly translated,
but if the corrected term is imported in the memory, the system usually learns the correct translation very quickly.

Could you please provide some more details about your engine (language direction, training size, etc), about you run training and translation commands, and some examples worrying you.

We could try to replicate and investigate this issue.

**Comment by LoekvanKooten** [comment]
It's basically caused by legacy translations... once I retrained the entire model, the problem no longer occurred. I.e. if a word has been translated as A a very long time, and the translation suddenly changes to B, while said word is Written With Capitals In English (i.e. considered as a proprietary name by ModernMT), the old translation becomes very obnoxious and is very hard to get rid of, even after using translation B for dozens of times and adding these to the memory.

**Comment by LoekvanKooten** [comment]
The first letter is capitalized.

The neural network trains on old translations and learns that Paper is Foglio.

The network is trained. I now use it for suggestions. Every time the network suggests Paper = Foglio, I tell it that Paper = Articolo (using addToMemory).

This hardly gets picked up, not even after teaching the network Paper = Articolo dozens of times. What is inserted are mostly entire sentences, but also word pairs.

**Comment by nicolabertoldi** [comment]
when you say "after teaching the network Paper = Articolo" do you mean you add a sentence pair into your memory through this [API](https://modernmt.github.io/enterprise-api/apis/api-update-memory-content.html)?

could you provide us a real example?

could you please provide us the log of your actions?
basically you could upload the file runtime/default/logs/node.log

**Comment by LoekvanKooten** [comment]
Dear Nicola,

Yes, that is correct! I don't have a log right now, as I just retrained a new engine and will need to wait until this happens again.

**Comment by nicolabertoldi** [comment]
in order to have an informative log during translation,
please start the engine with option "-v 2"

**Comment by nicolabertoldi** [comment]
@LoekvanKooten 
have you already solved the issue?

If yes, I would kindly ask you to close the issue,
otherwise we are glad to help you further.

**Comment by LoekvanKooten** [comment]
I haven't encountered this problem anymore. I'll re-open if it pops up again!
