### ISSUE TITLE
Where are added entries saved?

### ISSUE THREAD

**Issue by LoekvanKooten** [ModernMT/MMT#397]
When an entry is added with addToMemory (REST), where in the directory tree is it saved?

**Comment by nicolabertoldi** [comment]
the entry added by a user is inserted in the portion of the database reserved to that user,
and cannot be directly accessed by anyone.

**Comment by LoekvanKooten** [comment]
The reason I ask is for back-up purposes. I'm not intending to edit anything. Thanks in advance!

**Comment by nicolabertoldi** [comment]
To be more precise, all entries added are stored in the memory inside the database specified through the REST API. These entries live in the memory until the memory lives the database.
Hence, the only way to remove these data is the deletion of the entire memory; for details see https://modernmt.github.io/enterprise-api/apis/api-delete-memory-content.html. Please note that the operation is un-recoverable.

**Comment by nicolabertoldi** [comment]
the issue has been closed by mistake

**Comment by davidecaroselli** [comment]
Long story short:

if you need to backup you engine (supposing it's the `default` one), you can do as following:
```bash
./mmt stop
cp -rp engines/default /your/backup/folder/
./mmt start
```

Simple as that :)

**Comment by mzeidhassan** [comment]
Hi @davidecaroselli and @nicolabertoldi , 

Sorry for re-opening the issue. I hope it's all well with you. 

Say, I have one engine that I use myself and I keep adding single translations to memory 1 for example. Is there a way I can export the parallel text out of this memory to a text file? My goal is to keep track of what I have added and maybe use this data later when I need to train a new engine. Is this possible?

Thanks,
Mohamed

**Comment by LoekvanKooten** [comment]
Everything I add to ModernMT, I also add to a MySQL database. Still, I'm curious too.

**Comment by mzeidhassan** [comment]
Thanks @davidecaroselli ! It's very useful to learn about both ways. 

One last question:
Your command above to back up the engine `cp -rp engines/default /your/backup/folder/`, won't include the data that is being added to the engine through import, right? 

I am asking because I am afraid if something goes wrong with the engine for some reason, I would basically lose all this manually added data. A backup in this case would be the plain base model. 

Another scenario is for example connecting to MMT through a tool like MateCat or maybe a Trados plugin that will send all new translations to MMT through a PUT call for example after saving each segment. Using that command won't back up these segments, right? If this is the case, then it won't be possible to migrate a particular engine with all its data "initial training model +  added memories".  Am I right about this or am I missing something here?

Thanks again!

**Comment by nicolabertoldi** [comment]
MMT system stores not only the original model an data, but also the new data imported in it, although the data are processed and filtered as remarked by Davide in his final note.

Hence, the "hacky" way suggested by Davide provides a backup of the last "status" of the engine,
but it does not allow to reconstruct the very original text imported.

Regarding the "migration" of a **particular engine with all its data "initial training model + added memories"**, the hacky way allows exactly what you intend to do.

**Comment by davidecaroselli** [comment]
Hi @mzeidhassan

By copying the engine folder, you copy everything: both baseline models and data added.

In fact the engine folder holds also the Kafka queue, so that is the right way to backup entirely your data!

**Comment by mzeidhassan** [comment]
Thanks @davidecaroselli  and @nicolabertoldi. Glad that everything will be backed up. Thanks again for your amazing support. You may close the issue.

**Comment by mzeidhassan** [comment]
Hi @davidecaroselli ,

I looked at the files under models/context/storage and as far as I can tell, it contains English strings only. I don't see any target strings. Any idea where I can find the target strings? 

Thanks!

**Comment by nicolabertoldi** [comment]
Hi @mzeidhassan 
In theory, you should find pairs of files   NAME_SL_TL and     NAME_TL_SL
There are the "parallel" files   for the memory NAME; the first contains the text in language SL, the second the text in TL.

For instance, I have in my engine these two files "10940_en_de" and "10940_de_en", with English and German, respectively.

**Comment by davidecaroselli** [comment]
Hi!
What Nicola said is correct, but only if your engine supports German > English too. This is because the Context Analyzer works only with the source part of a document. If you support also DE > EN then it will store also the target side that can be used for the reversed language pair.

**Comment by mzeidhassan** [comment]
Thanks @nicolabertoldi and @davidecaroselli !
Unfortunately, my engine was EN>AR only. So, I am only seeing English files, no Arabic files.

**Comment by nicolabertoldi** [comment]
I will try to re-create your conditions,
and report asap

Could just confirm that you train the system using  a command like
```
mmt create en ar training_dir
```

or even better could you provide  the exact command you run for training your system?

**Comment by davidecaroselli** [comment]
@mzeidhassan this is totally  expected: context analyzer only create index and store the source part of your content, that is English.

**Comment by mzeidhassan** [comment]
Thanks @davidecaroselli ! Good to know and I will keep backups of the data I keep adding from now on until I figure out a way to retrieve the data from Kafka. You may close this issue if you wish.
