### ISSUE TITLE
Manually Changing Parameters

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#40]
in 0.11 I cannot longer find where to change the moses.ini parameters.

This files do not included the weights.

```
# find engines/|grep ini
engines/default/runtime/moses.ini
engines/default/engine.ini
engines/default/data/moses.ini
```

@davidecaroselli where is now the file?

If the file was removed on purpose, I think we should put back the opportunity to change them manually.

**Comment by davidecaroselli** [comment]
If you need to change the moses.ini parameters, **except for weights**, you can modify the template file *engines/default/data/moses.ini*.
If you want to change the decoder weights, you find them in file *engines/default/engine.ini*.
The file *engines/default/runtime/moses.ini* is dynamically generated so its changes won't be loaded or stored anywhere.

To apply your changes please remember to restart all your MMT nodes.

I close this issue, if you any further questions please re-open it.
