### ISSUE TITLE
Advanced Configuration for old versions on Wiki page missing?!

### ISSUE THREAD

**Issue by mzeidhassan** [ModernMT/MMT#401]
Hi MMT team,

I am really puzzled. As far as I remember, there was somewhere on the wiki page instructions on how to change number of layers (2,3,...), the optimizer (Adam, SGD, etc) by passing such parameters in a file. I believe this was for MMT version 2.3 and 2.4. For some reason, I cannot locate it anywhere.

Any idea? or Am I hallucinating?

Thanks,
Mohamed

**Comment by nicolabertoldi** [comment]
Actually, on the web we have documentation for the latest version.

I recovered he documentation of the old version, and print for you the page describing how to change any parameters of the neural network.
[Neural-Network-Configurations.pdf](https://github.com/ModernMT/MMT/files/2382108/Neural-Network-Configurations.pdf)

Please, keep in mind that the attached instructions are valid for the old version only.

**Comment by mzeidhassan** [comment]
Thanks a million, @nicolabertoldi ! I am grateful to you for taking the time to print it out.

Have a wonderful weekend ahead and thanks again!

**Comment by nicolabertoldi** [comment]
@mzeidhassan,
very glad to have helped you.

I'm closing this issue, if there are any other related problem, please feel free to re-open it!
