### ISSUE TITLE
MMT 3.1 works like a charm!

### ISSUE THREAD

**Issue by LoekvanKooten** [ModernMT/MMT#405]
Not an issue, but I wanted to let you know nonetheless. Thank you very much!

**Comment by LoekvanKooten** [comment]
Could you tell us a bit more about the new Context Analyzer Model? How has it become more reliable?

**Comment by davidecaroselli** [comment]
Hi @LoekvanKooten ,

sure. We run some stress testing on the old Context Analyzer model and we just realized that there were race-conditions that could lead to data loss, limited to the context analyzer.

The new model has a built-in gzip strategy that drastically reduce the disk space required for execution and, more important, passed all stress tests.

**Comment by LoekvanKooten** [comment]
Thank you for that!
