### ISSUE TITLE
Improved post-processor pipeline in 3.2?

### ISSUE THREAD

**Issue by mzeidhassan** [ModernMT/MMT#406]
Hi MMT team,

Can you please shed some light on what has been changed in the post-processor pipeline in MMT 3.2?

Thanks,
Mohamed

**Comment by davidecaroselli** [comment]
Hi @mzeidhassan !

Basically ModernMT now handles correctly all Android variable such as: $1%d or %s

**Comment by mzeidhassan** [comment]
Hi @davidecaroselli ,

Sorry for my belated reply. This is really great news. This was a recurring issue in previous versions and a space was added before $ and %. Thanks again and have a wonderful weekend ahead! I am closing the issue.
