### ISSUE TITLE
tensor2tensor version?

### ISSUE THREAD

**Issue by mzeidhassan** [ModernMT/MMT#407]
Hi MMT team,

Right now, MMT is using tensor2tensor version 1.6.3. The latest release for T2T is [1.9.0](https://github.com/tensorflow/tensor2tensor/releases). Do you foresee a problem if I used this command in my installation?

`pip install tensor2tensor==1.9.0`

Thanks,
Mohamed

**Comment by davidecaroselli** [comment]
Hi @mzeidhassan 

I had the chance to test ModernMT with the new `tensor2tensor v1.9`; while it has some minor issues at runtime, the training process is no longer compatible so, unfortunately, at the moment we cannot consider ModernMT compatible with that version.

Best,
Davide

**Comment by mzeidhassan** [comment]
Thanks @davidecaroselli for letting me know. I appreciate it. I am closing this issue.

Best,
Mohamed
