### ISSUE TITLE
Ubuntu 15.10 - Python Import Error

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#41]
I created a new Ubuntu 15.10 using VirtualBox.

I was able to install Java 8 using the instructions provided.

```
# ./mmt create en it examples/data/train
```

Will say there is an error in met line 9.

```
ImportError: No module named requests.
```

**Comment by marcotrombetti** [comment]
Installed the 15.10 Official from Ubuntu. Same problem.

**Comment by marcotrombetti** [comment]
Request module is not installed on Ubuntu 15.10, Updated INSTALL documentation with instructions.

Now training works but engine does not start:
```
./mmt start

Starting MMT engine 'default'... FAIL
ERROR: failed to start master instance, check log file for more details: /home/marco/Downloads/mmt/engines/default/logs/mmtmaster.log
```

The mentioned log does not exists.

**Comment by marcotrombetti** [comment]
I tried different ports also.

**Comment by davidecaroselli** [comment]
Currently not tested on Ubuntu 15.10. We will provide more instructions in INSTALL.md in the future.
