### ISSUE TITLE
'Access-Control-Allow-Origin' header 

### ISSUE THREAD

**Issue by philippehenri** [ModernMT/MMT#410]
Hello

Can you please let me know where it is possible to change the  'Access-Control-Allow-Origin' header 
to allow remote calls from another server/domain?
thanks

**Comment by davidecaroselli** [comment]
Hi @philippehenri 

I have just pushed to **master** branch the commit https://github.com/ModernMT/MMT/commit/f8285bc2e48f597c562506412f9e854ab8eff4e1 that adds `"Access-Control-Allow-Origin: *"` header to every ModernMT responses.

Best,
Davide

**Comment by philippehenri** [comment]
wow fantastic Davide, thanks for the fast update. Works perfectly ! :)
