### ISSUE TITLE
Help with Delete Memories

### ISSUE THREAD

**Issue by LoekvanKooten** [ModernMT/MMT#412]
Something went wrong in my code. getAllMemories gives:

`array(29) { [0]=> array(2) { ["id"]=> int(19) ["name"]=> string(7) "procdut" } [1]=> array(2) { ["id"]=> int(24) ["name"]=> string(7) "procdut" } [2]=> array(2) { ["id"]=> int(3) ["name"]=> string(7) "procdut" } [3]=> array(2) { ["id"]=> int(30) ["name"]=> string(7) "procdut" } [4]=> array(2) { ["id"]=> int(16) ["name"]=> string(7) "procdut" } [5]=> array(2) { ["id"]=> int(25) ["name"]=> string(7) "procdut" } [6]=> array(2) { ["id"]=> int(12) ["name"]=> string(7) "procdut" } [7]=> array(2) { ["id"]=> int(20) ["name"]=> string(7) "procdut" } [8]=> array(2) { ["id"]=> int(13) ["name"]=> string(7) "procdut" } [9]=> array(2) { ["id"]=> int(7) ["name"]=> string(7) "procdut" } [10]=> array(2) { ["id"]=> int(26) ["name"]=> string(7) "procdut" } [11]=> array(2) { ["id"]=> int(15) ["name"]=> string(7) "procdut" } [12]=> array(2) { ["id"]=> int(23) ["name"]=> string(7) "procdut" } [13]=> array(2) { ["id"]=> int(9) ["name"]=> string(7) "procdut" } [14]=> array(2) { ["id"]=> int(27) ["name"]=> string(7) "procdut" } [15]=> array(2) { ["id"]=> int(21) ["name"]=> string(7) "procdut" } [16]=> array(2) { ["id"]=> int(4) ["name"]=> string(7) "procdut" } [17]=> array(2) { ["id"]=> int(10) ["name"]=> string(7) "procdut" } [18]=> array(2) { ["id"]=> int(28) ["name"]=> string(7) "procdut" } [19]=> array(2) { ["id"]=> int(11) ["name"]=> string(7) "procdut" } [20]=> array(2) { ["id"]=> int(14) ["name"]=> string(7) "procdut" } [21]=> array(2) { ["id"]=> int(8) ["name"]=> string(7) "procdut" } [22]=> array(2) { ["id"]=> int(5) ["name"]=> string(7) "procdut" } [23]=> array(2) { ["id"]=> int(22) ["name"]=> string(7) "procdut" } [24]=> array(2) { ["id"]=> int(6) ["name"]=> string(7) "procdut" } [25]=> array(2) { ["id"]=> int(1) ["name"]=> string(7) "procdut" } [26]=> array(2) { ["id"]=> int(18) ["name"]=> string(7) "procdut" } [27]=> array(2) { ["id"]=> int(17) ["name"]=> string(7) "procdut" } [28]=> array(2) { ["id"]=> int(29) ["name"]=> string(7) "procdut" } }`

So clearly I want to get rid of all ID's above 1.

I do:

`    /**
    Delete all memories with id > 2
     */
    public function deleteMemories() {
        for ($externalId = 2; $externalId < 1000; $externalId++) {
            echo "$this->baseUrl/memories/$externalId" . PHP_EOL;
            return $this->send('DELETE', "$this->baseUrl/memories/$externalId");
        }
    }`

This gives:

`Fatal error: Uncaught MMT\MMTServiceApiException: Requested resource not found in D:\Xampp\htdocs\ModernMT\MMTServiceApiException.php:18 Stack trace: #0 D:\Xampp\htdocs\ModernMT\MMTServiceApi.php(405): MMT\MMTServiceApiException::fromJSONResponse(Array) #1 D:\Xampp\htdocs\ModernMT\MMTServiceApi.php(387): MMT\MMTServiceApi->parse('{"status":404,"...') #2 D:\Xampp\htdocs\ModernMT\MMTServiceApi.php(127): MMT\MMTServiceApi->send('DELETE', 'http://192.168....') #3 D:\Xampp\htdocs\ModernMT\getmemories.php(33): MMT\MMTServiceApi->deleteMemories() #4 {main} thrown in D:\Xampp\htdocs\ModernMT\MMTServiceApiException.php on line 18`

Where do I go wrong?

**Comment by davidecaroselli** [comment]
Hi @LoekvanKooten 

the API error `Requested resource not found` means that the memory you want to delete does not exist in the system.

In your example you don't have memory 100 or 976 (and many others actually) so with the for loop you are using, ModernMT correctly raises the error "Resource not found" because you are requesting the deletion of a memory that does not exist.

**Comment by LoekvanKooten** [comment]
The thing is, it doesn't delete the existing memories either.

**Comment by davidecaroselli** [comment]
Please, run this test:
```bash
curl -X GET http://localhost:8045/memories/19 | python -mjson.tool  # get memory 19 metadata (should succeed)
curl -X DELETE http://localhost:8045/memories/19 | python -mjson.tool  # delete memory 19 (should succeed)
curl -X GET http://localhost:8045/memories/19 | python -mjson.tool  # verify memory 19 does not exists (should fail)
```

**Comment by LoekvanKooten** [comment]
Ah, once it gives that error, it just stops doing anything. Solved! Thank you very much!
