### ISSUE TITLE
No memories found, but engine works ok

### ISSUE THREAD

**Issue by gdaine** [ModernMT/MMT#413]
I think I have messed up the memory metadata store.
I inadvertently used PUT instead of POST to try to add translated segments to a memory, and now http://localhost:8045/memories returns Status: 200, Data: []
The only thing I can do is add new memories - I can't find the memory id, so I can't use most of the API.
However, I can start, stop and translate as usual so the actual engines are OK.
Is there a solution?

PS - There is an error in the API main page of the wiki: it says "PUT /memories/:id/corpus - Add parallel text to memory corpus" where is should be POST, not PUT. I think this is where my problem may have started, although it was my fault because the actual examples given do use POST.

**Comment by nicolabertoldi** [comment]
Which is the exact sequence of your API calls?


We fixed the wiki page.

**Comment by nicolabertoldi** [comment]
@gdaine 
if you have solved the issue, please close it.
Otherwise we are glad to support you further.
