### ISSUE TITLE
Truncated translation - max length?

### ISSUE THREAD

**Issue by philippehenri** [ModernMT/MMT#416]
Hi Guys, 

I need some help or advice here , i have an example showing that translation is truncated ?

I try to translate this sentence (ps: this is not related to thread #411 where the problem was due to multiple sentences):

“Volgens het arbeidsauditoraat en de advocaat van het Thaise koppel waren de twee mensen na de tsunami die Thailand eind 2004 trof, naar België gelokt met een rooskleurig voorgesteld job aanbod.”

it gets translated as: “Selon l'auditorat du travail et l'avocat du couple thaïlandais, après le tsunami qui a frappé la Thaïlande à la fin de l'année 2004, les deux personnes étaient attirées vers la Belgique avec une offre d'emploi très”

1/ problem : the proper translated sentence should end with “très prometteuse."  (note the END DOT) …

Now, if i shorten the source text and replace for example “arbeitsauditoraat” with auditoraat, i get the full sentence ending with “très prometteuse ” but still no END DOT…

2/ i shorten a bit more and change “auditoraat” with “audit”, then i finally get the full sentence with end dot !!

“Selon l'audit et l'avocat du couple thaïlandais, après le tsunami qui a frappé la Thaïlande à la fin de l'année 2004, les deux personnes étaient attirées vers la Belgique avec une offre de travail très prometteuse.”

Is there a sentence length limit? What is the problem?

Note: I made other tests with similar results:

1/ "Volgens Bill Clinton en de advocaat van het Thaise koppel waren de twee mensen na de tsunami die Thailand eind 2004 trof, naar België gelokt met een rooskleurig voorgesteld job aanbod."

translation is ok : it ends with "avec une offre d'emploi prometteuse."

2/ now if i add 4 chars ('abcd') to translate "Volgens Bill Clintonabcd en de advocaat van het Thaise koppel waren de twee mensen na de tsunami die Thailand eind 2004 trof, naar België gelokt met een rooskleurig voorgesteld job aanbod."

the translation ends with "avec une offre d'emploi"

(missing "très prometteuse.")

...sic

thanks
philippe

**Comment by nicolabertoldi** [comment]
In our system there is a maximum length of the produced translation, which depends on the input source length.

Basically, we guess the expected target length of the target according to the length of the source, in this way:
target_length = source_length * language_multiplier + language_intercept
where language_multiplier and language_intercept are parameters can be set in the configuration file "engines/default/models/decoder/model.conf"
By default these parameters are 1.0 and 0, respectively.

For instance, if you add this
[decode_lengths]
nl__fr = 1.2 2
the French target output can be up to 1.2 times longer than the Dutch source (plus 2).

For the sake of optimization, the expected target length is then extended to 3 predefined levels.

Note that all lengths refer to the amount of bpe-subtokens, and not to the word tokens.

Please try to set the above-mentioned parameters in the configuration file and check whether the outcome differs.

**Comment by philippehenri** [comment]
Excellent Nicola, that fixed the problem ! thanks for a quick reply :)

Are these default the same for all language pairs? example,  english-french should also be adapted then i guess (as french sentences are much longer than english equivalent)?

**Comment by nicolabertoldi** [comment]
The default ``language_multiplier`` and ``language_intercept`` equal to 1.0 and 0 are the same for all languages.

We let the user set up them in the configuration file according to the "differences" between languages.

**Comment by EtienneAb3d** [comment]
Is this a strong limitation on the output length ? Setting it to 1.0 and 0 seems a bit hard. There could be a lot of reasons why the output is a bit longer than the input, whatever the languages.

**Comment by nicolabertoldi** [comment]
I mentioned that the expected length is then extend to 3 predefined levels. 

To be more clear:
if the expected length computed as explained above is lower than 50, then the actual target length can contain up to 50 bpe subtokens
else if the expected length computed as explained above is lower than 100, then the actual target length can contain up to 100 bpe subtokens
else if the expected length computed as explained above is lower than 260, then the actual target length can contain up to 260 bpe subtokens

We do not admit longer outputs, but please consider that we split long input into smaller segments, which are translated independently and then re-attached.
So it is very rare that the system actually translates segments which are longer than 260 bpe subtokens.

**Comment by EtienneAb3d** [comment]
If an input length is 49, then the output is less than 50, by default ?

**Comment by nicolabertoldi** [comment]
@philippehenri,

usually, the length ratio in terms of subtokens is much closer to 1.0 than the ration in terms of tokens or characters.

Hence, I guess that 1.2 is good for most languages.

**Comment by nicolabertoldi** [comment]
@philippehenri, @EtienneAb3d 

Thanks to this interesting discussion, we have just decided to modify the policy related to the admissible output length, and make it much simpler.

Basically, the maximum input length will be computed something similar to:
```
maximum_output_length = 1.5 * ( source_length * language_multiplier + language_intercept )
```
Again, these length are computed in terms of subtokens.

We will implement this policy very soon.


Please stay tuned!

**Comment by philippehenri** [comment]
Excellent, thank *you* for the quick feedback and solution !
