### ISSUE TITLE
type="phrase_based" still present in the documentation

### ISSUE THREAD

**Issue by EtienneAb3d** [ModernMT/MMT#417]
MMT3 is pure neural, isn't it ?
https://github.com/ModernMT/MMT/wiki/Advanced-Configurations

**Comment by nicolabertoldi** [comment]
yes, it is.

We will update the documentation asap.
Thank you for spotting this.

**Comment by MT-Group** [comment]
Hi all,
We didn't know that the new version was neural by default. Is there still a way to create phrase-based engines? With certain documents and controlled language, they work very well.
Thanks,
Lucía

**Comment by nicolabertoldi** [comment]
New ModernMT releases (from 3.x) support neural framework only.

If you are interested in phrase-based decoder, you have to checkout release 2.5.
In that version, phrase-based  framework is the default.

Nicola

**Comment by davidecaroselli** [comment]
Hi @MT-Group ,

just like Nicola said, you can download [ModernMT v2.5 here](https://github.com/ModernMT/MMT/releases/tag/v2.5).

**Comment by davidecaroselli** [comment]
Just updated the documentation for MMT v3.x. Thanks to all for pointing that out!
