### ISSUE TITLE
extras/translate_xliff script error “ImportError: cannot import name shell“

### ISSUE THREAD

**Issue by mindaugasDEV** [ModernMT/MMT#425]
Hi, @davidecaroselli 

I don`t succeed translating folder of files with the script.

After running commands `$ extras/translate_xliff /path/to/your/xliff/folder -e engine` or with default engine `$ extras/translate_xliff /path/to/your/xliff/folder` I get the following error message:

```
Traceback (most recent call last):
  File "extras/translate_xliff", line 8, in <module>
    from cli.libs import shell
ImportError: cannot import name shell
```
I am using latest 3.2 release and Ubuntu 16.04. Translating one-file-at-the-time via mmt translate --xliff works fine, though.

Thanks for checking on that.

**Comment by mindaugasDEV** [comment]
Hi, @davidecaroselli, 

Can you give help?  Can you give a hint why we get this message? Single SDLXLIFF file is being translated fine via 
`mmt translate --xliff` , but the script `$ extras/translate_xliff /INPUT` (real folder with SDLXLIFF files) gives an error as described above.

I have compiled MMT from source, used  “Option 3 - Installing from source“ , release 3.2,  cloned repository 15 days ago.


Thanks! :)

**Comment by davidecaroselli** [comment]
@mindaugasDEV nevermind, I have just pushed the fix in `master` branch, can you see if it solved the problem? Thanks!

**Comment by mindaugasDEV** [comment]
@davidecaroselli Thanks for trying :)


The former error message is gone, but I got the new one. 
I run `extras/translate_xliff ~/mmt/BATCH` and I got the following message

`Translating /home/user/mmt/BATCH/file.sdlxliff into /home/user/mmt/BATCH/xliff_out/out_file.sdlxliff...
Traceback (most recent call last):
  File "extras/translate_xliff", line 88, in <module>
    main()
  File "extras/translate_xliff", line 59, in main
    args.context, args.context_file, args.context_vector, args.engine)
  File "extras/translate_xliff", line 83, in translate_xliff_file
    osutils.shell_exec(command)
  File "/home/user/mmt/cli/libs/osutils.py", line 57, in shell_exec
    raise ShellError(str_cmd, return_code, stderr_dump)
cli.libs.osutils.ShellError: Command '/home/user/mmt/mmt translate --batch --xliff < "/home/user/mmt/BATCH/file.sdlxliff" > "/home/user/mmt/BATCH/xliff_out/out_file.sdlxliff"' failed with exit code 2: 'usage: mmt [-h] [-s SOURCE_LANGUAGE] [-t TARGET_LANGUAGE] [--context CONTEXT]\n           [--context-file CONTEXT_FILE] [--context-vector CONTEXT_VECTOR]\n           [-e ENGINE] [--batch] [--xliff]\n           [TEXT]\nmmt: error: unrecognized arguments: "/home/user/mmt/BATCH/file.sdlxliff" > "/home/user/mmt/BATCH/xliff_out/out_file.sdlxliff"\n'
`
Folder xliff_out is created, but file is not being translated and not being transferred to output folder.

**Comment by mindaugasDEV** [comment]
Thanks a million, the last correction of the code worked! I tried with 1 file and it got translated! You can close the issue. 

Thanks for prompt support, appreciated! :)

**Comment by davidecaroselli** [comment]
Awesome! :)
