### ISSUE TITLE
How to export runnable jar of MMT

### ISSUE THREAD

**Issue by carman1** [ModernMT/MMT#427]
We have changed a little bit in the function of MMT,however we can not export the right mmt.jar to be used in the python project.We need to know how to build the /MMT/build/mmt-2.4.jar file by ourself.

**Comment by davidecaroselli** [comment]
Hi @carman1 

JAR creation is configured in the [Command Line pom.xml](https://github.com/ModernMT/MMT/blob/master/src/command-line/pom.xml) where basically the maven compiler is instructed to create a fat-JAR and place it in `build` folder.

If you created your own Main class, you can lunch it just like any other class with:
`java -cp path/to/mmt-2.4.jar -Dmmt.home=/path/to/MMT complete.package.name.YourMainClass [args]`

**Comment by davidecaroselli** [comment]
I'm closing this issue due inactivity but please feel free to re-open it if you need further help.
