### ISSUE TITLE
Incorrect tag projection returned from /translate, /tags-projection returns correct projection

### ISSUE THREAD

**Issue by robertBrnnn** [modernmt/MMT#428]
Hi @davidecaroselli @nicolabertoldi 

I've stumbled across an odd issue with 3.0 release of MMT. When translating tagged content, the tag projection is incorrect using /translate endpoint, however when using /tags-projection endpoint the translation is correct.

Take for example:
`<a href="#">Skip to main content</a><nav class="navbar">` 

The translation returned from our engine for ZH_CN is:
`<a href="#">跳到主内</a>容<nav class="navbar">`

Similarly, the translation returned from your public ZH_CN engine is:
`<a href="#">跳转到主要内</a>容<nav class="navbar">`

_The same can be observed for ZH_TW also._

However, if I use tags-projection endpoint for our engine, given the translated text:
`跳到主内容`
The tag projection is now correct:
`<a href="#">跳到主内容</a><nav class="navbar">`

I may be wrong in the following assertion but from scanning your source code, it seems you are using an alignment returned from the T2T engine when using the translate endpoint but, you use the fast align model for the tags-projection endpoint, which in turn produces a correct translation? 

Thanks,
Rob.

**Comment by davidecaroselli** [comment]
Hi @robertBrnnn 

In the master branch there is an improved version of tag projection that solves the issue you are reporting.

Thanks for your support!
