### ISSUE TITLE
"./mmt evaluate" and "./mmt tune" enhancement

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#43]
Open for discussion:

As by discussion we are missing the model evaluation functionality.

Here is the proposal:
- When training, up to 1000 sentences will be removed from the corpus for creating the dev set (500) and test set (500) in the folder 'engines/youmodel/data/[dev | test]'. Min (1000, 1% of the corpus sentences)
- Sentences should be extracted so that there is not an extra rewrite of the file
- Position of extraction should be spread across the corpus and fixed position based given the corpus. Short: 2 training on the same data will provide the same output.
- Duplication management: by default we don't dedup test|dev and corpus. If there are 2 equal sentences in the corpus the test|dev may contain a sentence that is also in the corpus. There should be an option to avoid duplicates.
- One data is in the engines dir this can be substituted by data provided by the user.

For the user, at this point it should be as easy as:
Tuning
`
./mmt tune
`
Evaluating
`
./mmt evaluate
`

**Comment by mfederico** [comment]
Hi 

my idea is that tuning should be replaced with something 
more computation and more data efficient.  But we have to 
work a bit on this.  In the current scenario with K domains, I 
discussed with Nicola and Roldano about either mapping the 
weights to those of the “closest” domain. They are now running 
these experiments.

We also carried out experiments to improve the domain distribution
of the CA by using source LMs. It seems that this approach provides 
systematically better results than with the weights returned by the CA.  
Practically we should be able to integrate the two things: fast matching
with CA that return K best domains (with high recall)  and then run 
expectation maximisation with the corresponding K source LMs to get 
the weights. 



Marcello

**Comment by marcotrombetti** [comment]
@mfederico Tuning is clear to me as expressed also in #28 
We will discuss it a little more and implement that solution.

For quality CA/LM, yes this make sense, but please consider also that the weights of the CA are not optimized since we may go with Suffix Array Ranked Sampling so that weights are important only to rank domains. They don't really provide sampling weights. Let's discuss this more on the Co-Dev in Feb.

My point was more on Evaluation.
We need one simple way to help people estimate the quality of the engine before doing field test or real tests.

Customer X train a model with their TMs. We need to provide an number that estimate how much that engine will help your pro translators or in general how good the quality i expected to be assuming that your TM also represent the average content you do translate (reasonable assumptions for the customers I know). 
The customer should have the BLUE score of Google Translate  vs It's own engine and decide by consequence. We will implement this and review together. I think it is faster to do and fix it than describing it.

**Comment by mfederico** [comment]
I like the idea of proving self assessment of the created MT. 
Marcello

**Comment by davidecaroselli** [comment]
Fully implemented. The code is currently in develop as well as master branch
