### ISSUE TITLE
python download_dependencies.py ==> ValueError: can't have unbuffered text I/O

### ISSUE THREAD

**Issue by chiapas** [ModernMT/MMT#430]
I got the following error message. I don't know why we need # reopen stdout in unbuffered mode, but it cause ValueError: can't have unbuffered text I/O. I changed the line to sys.stdout = os.fdopen(sys.stdout.fileno(), 'w'), i.e. without the 0 at the end, and it works.

Traceback (most recent call last):
  File "download_dependencies.py", line 216, in <module>
    sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', 0)  # reopen stdout in unbuffered mode
  File "/usr/lib/python3.5/os.py", line 1072, in fdopen
    return io.open(fd, *args, **kwargs)
ValueError: can't have unbuffered text I/O

**Comment by nicolabertoldi** [comment]
@chiapas 

we will dig into.

But it would be help us a lot to know which version of software are you using:
- linux
- python
- tensorflow
- tensot2tensor
- ModernMT

**Comment by chiapas** [comment]
I am going to try with Docker. The env on the machine I worked is a bit messy. When I have time, I will try on a clean machine to see if the same issue exists.

**Comment by davidecaroselli** [comment]
I'm closing this issue, the problem cause is having used **python3** instead of **python**.
Please feel free to re-open the discussion if there are any updates!

Thanks
