### ISSUE TITLE
pack_model without deleting training data

### ISSUE THREAD

**Issue by EtienneAb3d** [ModernMT/MMT#440]
I see in the code that the training data deletion is optional with a "debug" flag. I don't know how to set this "debug" flag, nor what are the consequences.

It would be nice to be able to set this deletion option through the command line. It would enable to build a model, copy this model in an independent engine folder to be able to use it immediately, and then, resume the training for a better result later.

For the moment, I've edited the code to set it to "do not delete". Thus, I will be able to resume all my trainings, when a graphic card is available. I can delete myself if I need disk space...

**Comment by davidecaroselli** [comment]
Hi @EtienneAb3d 

You can enable debug by simply adding `--debug` to the command line. When debug is specified, the training won't delete any file even after completion.

**Comment by EtienneAb3d** [comment]
OK. I should have had a better look at the command line help. 

This said, it's not evident that the debug mode will prevent from deleting the training data, so that it will be possible to resume the training after having pack the model. 

It would be nice to add this "do not delete" option, to make this possibility more evident.

**Comment by EtienneAb3d** [comment]
It seems that I can't pack a model twice. 
The second pack command runs in 0s without error.
What should be done to enable this ?
A can resume, but not pack a second time.

**Comment by EtienneAb3d** [comment]
It's not exactly that.
1) I did a training
2) stopped it without deleting training data
3) packed it.. ok
4) resumed the training.. it worked
5) packed it again.. it failed

How may I pack a second time, with the training data not deleted the first time ?

**Comment by davidecaroselli** [comment]
Ok, what error was prompted?

**Comment by EtienneAb3d** [comment]
No error. The packing is just done in 0s. I think it detects something and skip the process, doing only the final parameter file building.

**Comment by EtienneAb3d** [comment]
Yes ! It's seems to work.
I still have a doubt, because the packing was a bit fast (41s). But, perhaps it's just because I didn't remember for the past already done.
Thanks !
