### ISSUE TITLE
Transformer-XL: Unleashing the Potential of Attention Models

### ISSUE THREAD

**Issue by mzeidhassan** [modernmt/MMT#441]
Hi @davidecaroselli and @nicolabertoldi ,

I hope all well with you and you are doing great.

I thought I should draw your attention to this. It was released yesterday by Google

[Transformer-XL](https://ai.googleblog.com/2019/01/transformer-xl-unleashing-potential-of.html)

I asked one of the authors yesterday if this will replace the current Transformer model, and his reply was 'yes, it's likely'. So, maybe MMT can be the first solution that implements this new model  :-) 

Here are some highlights that could be very beneficial to MMT.

“
1.	Transformer-XL learns dependency that is about 80% longer than RNNs and 450% longer than vanilla Transformers, which generally have better performance than RNNs, but are not the best for long-range dependency modeling due to fixed-length contexts (please see our paper for details).
2.	Transformer-XL is up to 1,800+ times faster than a vanilla Transformer during evaluation on language modeling tasks, because no re-computation is needed (see figures above).
3.	Transformer-XL has better performance in perplexity (more accurate at predicting a sample) on long sequences because of long-term dependency modeling, and also on short sequences by resolving the context fragmentation problem.”

Thanks,
Mohamed

**Comment by davidecaroselli** [comment]
That's super interesting, thanks @mzeidhassan for having shared this with us. We will definitely look into it.

**Comment by davidecaroselli** [comment]
Thanks again for the suggestion @mzeidhassan 
Just like @EtienneAb3d said, it seems that this model is the optimum for a slightly different ìuse case than ours. So we do not plan to add this model for the moment.

Thanks for the continuous support @mzeidhassan !
