### ISSUE TITLE
Option request : do not train word vectors

### ISSUE THREAD

**Issue by EtienneAb3d** [modernmt/MMT#446]
I would enjoy to experiment with an option that would do the following:
- randomize the network, especially the word vector layers.
- train the network WITHOUT updating the word vector layers.

Would it be hard to code ?

**Comment by davidecaroselli** [comment]
Hi @EtienneAb3d 

this is an issue more related to the low-level tensor2tensor framework that we use as our core model. For this reason it is probably best to ask directly to the t2t community that could definitely be more helpful!

If you succeed into train an engine, regardless on how you did it, you can "plug" it into ModernMT without any problem. In fact, this is what we actually do: our training pipeline at the end encapsulates the t2t-train call.

Feel free to re-open the issue if you think there can be something we can do on ModernMT side!

Thanks,
Davide
