### ISSUE TITLE
ModernMT 3.3 does not load or serve models at all

### ISSUE THREAD

**Issue by LoekvanKooten** [modernmt/MMT#455]
I've somehow managed to train two engines in ModernMT 3.3. I got some Java errors in the beginning, that disappeared after a restart. Now I get "Loading models." The log says "Loading FastAlign models." Then absolutely nothing happens. The GPU fans are not spinning, there are no errors... just absolutely nothing, and nothing in the logs either.

This applies to both engines trained in 3.3 as in engines trained in 3.0 that are (still) working in 3.0.

How come?

**Comment by nicolabertoldi** [comment]
@LoekvanKooten 
the step "Loading FastAlign models" (as well as few others) does not use GPU, but only CPU.

**Comment by LoekvanKooten** [comment]
Okay, but that still does not explain why modernMT does not move on. After 10 minutes it still says Loading models, while in the mmt7 directory, exactly the same model starts up straight away.

**Comment by davidecaroselli** [comment]
Hi Loek!
A quick note: as stated in the release info, v3.3 aligner models are not compatible with previous versions. So if you are trying to use old models with new code, Aligner models won't load.

Good news: Aligner models are not required for translation! So you can edit the engine.conf file and disable the Aligner (more info in our wiki)

**Comment by LoekvanKooten** [comment]
I should add that 3.0 does not load models trained in 3.3, but then again, neither does 3.3 itself. What I'm trying to say is that the eligner models created by 3.3 itself cannot be loaded by 3.3. 

As an intermediary solution I'll try to turn them off using the above instructions, but it's still strange this happens, I think?

**Comment by LoekvanKooten** [comment]
Mmmmh... with <aligned enabled="false"> it does indeed run. Maybe I didn't start with an empty directory during training, so that there are still old aligner remnants in it?

<aligned enabled="false"> has no influence on the translation quality or whatsoever? It's only used during training? Please forgive me for not being aware of the inner workings of the software.

**Comment by LoekvanKooten** [comment]
Correction: one of the engines does load, but the other one does not and gets stuck at the very same step. I double-checked: it gets stuck as Loading FastAlign, no error is generated and the config explicitly mentions aligned enabled="false"

**Comment by LoekvanKooten** [comment]
LOL, and now it does start. I changed absolutely nothing. The behavior is inconsistent and apparently not related to memory issues. I think we need a more verbose log, but I already use -v2

**Comment by LoekvanKooten** [comment]
There's another issue. Even when the models, trained in 3.3, are loaded correctly, the ports are closed immediately. Using netstat -tuplen | grep java I can see that java is listening when the engines are being started, but as soon as they have been started, java stops listening and all I get is connection refused.

The only engine that is working in 3.3 is the one that was not trained in 3.3 but in 3.0: this one keeps listening. When I then use *exactly* the same port settings for an engine trained in 3.3, the ports lock down immediately after start.

Conclusion: java does not like the engines trained in 3.3 and refuses to serve them.

These are absolute showstoppers at the moment. I have no choice but to move back to 3.0.

**Comment by davidecaroselli** [comment]
Hi @LoekvanKooten 

Thanks for the report, I was able to replicate the bug. I'm investigating right now!

**Comment by davidecaroselli** [comment]
Hi @LoekvanKooten 

thanks again for your help, we have just published a new release (v3.3.1) that fixes both problems: FastAlign models and neural networks models.

Let us know if this solves your issue.

**Comment by LoekvanKooten** [comment]
I just trained my first engine in 3.3. It now loads and serves (without needing to use aligner = false or anything else for that matter). Thank you for the quick fix!

**Comment by davidecaroselli** [comment]
Great! Thanks again for your report!
