### ISSUE TITLE
API merge - translate and nbest

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#48]
Enhancement: nbest should be part of the "translate" endpoint.
Bug: nbest currently crashes when context is passed

How is it now
```
http://localhost:8045/translation/nbest?q=I+like+it&nbest=10
```

How it should be
```
http://localhost:8045/translate?q=+I+like+it+&context=president&context=computer&n=10
```

the nbest list should be added as an extra array in the results. Not change the the standard structure.

The motivations:
- We want to keep the num of end-points small to make it easy for developers to join.
- nbest is just a specific case of translate, it not a different 
- Less maintenance and bugs (intact best API was already disalligned with translate)

**Comment by marcotrombetti** [comment]
Please also note that best output is currently tokenized and should be detokenized

**Comment by marcotrombetti** [comment]
I see you removed the bug tag.

Just to clarify it refers to the fact that if you pass context to the nbest API it crashes. Secondo line of the post.

**Comment by davidecaroselli** [comment]
I removed just because the context is simply not supported for this API. It was intended to be a private API, used only by MERT.

Anyway, I do agree that it should be reworked to be merged with the /translate API and inherit all its options and features. I'm going to work to this task today.
