### ISSUE TITLE
Tokenizer Improvement for apos

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#53]
Some input chars will create funny stuff.

First apos in examples should be managed by the tokenizer.

Unusual Apos
```
ubuntu@ip-172-30-0-162:~$ ./translate "We’re hackers ourselves"
Commissaire aux langues officielles que les opinions des anglophones sur ce dernier point sont pour l ’ essentiel les hackers nous-mêmes
```

With standard apos
```
ubuntu@ip-172-30-0-162:~$ ./translate "We're are hackers ourselves"
Nous sommes nous-mêmes des pirates informatiques sont
```

Without apos
```
ubuntu@ip-172-30-0-162:~$ ./translate "We are are hackers ourselves"
Nous sommes nous-mêmes des pirates informatiques sont
```

**Comment by davidecaroselli** [comment]
If I've understood well, what you're saying is that MMT is not broken in the sense that it crashes if you put char " **`** ". You're suggesting to add a step before tokenization that normalizes rare characters in order to maximize recall, correct?

**Comment by marcotrombetti** [comment]
@davidecaroselli yes, those chars create sparsity.
