### ISSUE TITLE
MMT Cluster - syncing not start

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#55]
```
ubuntu@ip-172-30-0-35:~/mmt$ ./mmt start -e BIG --master-pem ../MyMemoryBot-1.pem -m ubuntu@52.23.215.71

Starting MMT engine 'BIG'... OK
```

But nothing happened afterwords. Do syncing works in 0.11.1?

mmd status not providing any info

**Comment by marcotrombetti** [comment]
Various Problem found:
- .pem files should have permission 600 -> We should notify the user with a warning
- relative path for the pem do not work, absolute works. -> Fix
- mmt status  should provide info about the sync.
- mmd start **--master** user@ip is on README and  **-m** is in the cmd line help. Which one is correct?
- Log file was hard to find. 
- mmd start said OK, but the sync failed.

**Comment by davidecaroselli** [comment]
Last merge from develop resolved all these issues:
* `mmt start` checks pem permission before starting rsync
* relative paths for pem files now works correctly
* `mmt start` ends only when the models has been correctly synchronized
* removed short version `-m` for option `--master`
* in case of error, log file path is now printed on screen
