### ISSUE TITLE
rsync models is too slow for very large models

### ISSUE THREAD

**Issue by davidecaroselli** [ModernMT/MMT#56]
I've tested the cluster infrastructure for a 46Gb engine: the rsync process was too slow even if master and slave instances were already synchronized.

We need to change provisioning algorithm of the models to make it way faster.

**Comment by marcotrombetti** [comment]
Please can you run a comparison:
1) Time Required with a single machine
2) Time Required with 2 machines

In the ideal case 2) should take 50% of the time. Slow means that it is 95%? or 55%?
I understand that is slow but I would like to understand is it make scalability impossibile or add a small penalty.

**Comment by davidecaroselli** [comment]
The problem is ~10min and high I/O to start a slave instance that is *perfectly synchronized* with the master. Anyway, I think I have a solution that I would like to discuss.

**Comment by marcotrombetti** [comment]
I guess this has been solved by removing necessary rsync checks

**Comment by davidecaroselli** [comment]
Let my commit close this issue, please :smile:
