### ISSUE TITLE
Compilation failure on Core/src/main/java/eu/modernmt/network/cluster/ExecutionQueue.java

### ISSUE THREAD

**Issue by ugermann** [ModernMT/MMT#57]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project mmt-core: Compilation failure: Compilation failure:
[ERROR] /mmt/ModernMT/src/Core/src/main/java/eu/modernmt/network/cluster/ExecutionQueue.java:[108,19] error: unmappable character for encoding ASCII
[ERROR] 
[ERROR] /mmt/ModernMT/src/Core/src/main/java/eu/modernmt/network/cluster/ExecutionQueue.java:[108,20] error: unmappable character for encoding ASCII
[ERROR] 
[ERROR] /mmt/ModernMT/src/Core/src/main/java/eu/modernmt/network/cluster/ExecutionQueue.java:[108,21] error: unmappable character for encoding ASCII
[ERROR] 
[ERROR] /mmt/ModernMT/src/Core/src/main/java/eu/modernmt/network/cluster/ExecutionQueue.java:[109,19] error: unmappable character for encoding ASCII
[ERROR] 
[ERROR] /mmt/ModernMT/src/Core/src/main/java/eu/modernmt/network/cluster/ExecutionQueue.java:[109,20] error: unmappable character for encoding ASCII
[ERROR] 
[ERROR] /mmt/ModernMT/src/Core/src/main/java/eu/modernmt/network/cluster/ExecutionQueue.java:[109,21] error: unmappable character for encoding ASCII
[ERROR] 
[ERROR] /mmt/ModernMT/src/Core/src/main/java/eu/modernmt/network/cluster/ExecutionQueue.java:[110,19] error: unmappable character for encoding ASCII
[ERROR] 
[ERROR] /mmt/ModernMT/src/Core/src/main/java/eu/modernmt/network/cluster/ExecutionQueue.java:[110,20] error: unmappable character for encoding ASCII
[ERROR] 
[ERROR] /mmt/ModernMT/src/Core/src/main/java/eu/modernmt/network/cluster/ExecutionQueue.java:[110,21] error: unmappable character for encoding ASCII

**Comment by davidecaroselli** [comment]
just removed the non-ASCII chars. Please try update the code with the
command:

git pull origin master

and then retry compilation.

- Davide

**Comment by davidecaroselli** [comment]
@ugermann have you had time to test the fix?

**Comment by davidecaroselli** [comment]
I assume this bug has been fixed, if not please reopen the issue with new infos, thanks.
