### ISSUE TITLE
moses wrongly handle verbosity parameter

### ISSUE THREAD

**Issue by nicolabertoldi** [ModernMT/MMT#58]
I did not understand why, but
Moses is not able to interpret the verbosity parameter ("v") if it is specified in the configuration file;
hence it uses the default value, which is 1.
No problem instead if you set "-v 0" in the command line   or if you set "verbose"   in the configuration file

Note that setting parameters in the command line always overwrites those set in config

In summary,
assuming that moses.ini_v0 contains   
[v]
0

moses -f moses.ini_v0       -v 0                 --> verbosity   0
moses -f moses.ini_v0      -verbose 0      --> verbosity   0
moses -f moses.ini_v0     			       --> verbosity  1

assuming that moses.ini_verbose0 contains   
[verbose]
0

moses -f moses.ini_verbose0       -v 0               --> verbosity   0
moses -f moses.ini_verbose0      -verbose 0	--> verbosity   0
moses -f moses.ini_verbose0             		--> verbosity  1

hence,
I would suggest Davide to change the script which creates the configuration files
If I am right, it is hardcoded in scripts/mt/moses.py

Maybe it would be better to set it in engine.ini.
Which step creates this file?

cheers,
Nicola

**Comment by cattoni** [comment]
@cattoni

Nicola, I think you mean
    moses -f moses.ini_verbose0 --> verbosity 0
instead of
    moses -f moses.ini_verbose0 --> verbosity 1

**Comment by nicolabertoldi** [comment]
you are right, sorry

Assuming that moses.ini_v0 contains
[v]
0

moses -f moses.ini_v0 -v 0 --> verbosity 0
moses -f moses.ini_v0 -verbose 0 --> verbosity 0
moses -f moses.ini_v0 --> verbosity 1

Assuming that moses.ini_verbose0 contains
[verbose]
0

moses -f moses.ini_verbose0 -v 0 --> verbosity 0
moses -f moses.ini_verbose0 -verbose 0 --> verbosity 0
moses -f moses.ini_verbose0 --> verbosity 0

**Comment by davidecaroselli** [comment]
who can work on this issue? @ugermann @nicolabertoldi @cattoni please set the assignee of this issue.

**Comment by davidecaroselli** [comment]
Actually I think I have found the problem: it's inside the server implementation.
The instruction  `manager.OutputNBest(cout, nBestList);` is executed no matter what the verbose level is.

I'm fixing it in the new JNI server version (branch direct-server)

**Comment by nicolabertoldi** [comment]
actually you could have spotted a different issue. i.e. that of having nbest in the log of server

I meant the problem that the parameter "v" in the config file is not handled at all.

I create a new issue for the "wrong" output of the nbest.
This issue keeps related to verbose parameter.

Nicola

**Comment by davidecaroselli** [comment]
@nicolabertoldi it seems that this bug is related to Moses instead of MMT, if you agree I'll suggest to move this issue to the mosesdecoder repository and close this report.

**Comment by nicolabertoldi** [comment]
for me its fine

@davidecaroselli: by the way you have the way to reduce verbosity in the server
I would suggest you apply the change in the MMT scripts

**Comment by davidecaroselli** [comment]
I'm going to apply this change today. Thanks for your work!

**Comment by ugermann** [comment]
Davide,

Moses has never accepted [v] as a parameter in the config file. You are in
charge of the wrapper, so you are the one who has to fix whatever writes
the moses.ini file.

- Uli

On Wed, Jan 20, 2016 at 12:15 PM, Davide Caroselli <notifications@github.com
> wrote:

> who can work on this issue? @ugermann <https://github.com/ugermann>
> @nicolabertoldi <https://github.com/nicolabertoldi> @cattoni
> <https://github.com/cattoni> please set the assignee of this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ModernMT/MMT/issues/58#issuecomment-173186271>.
>



-- 
Ulrich Germann
Senior Researcher
School of Informatics
University of Edinburgh

**Comment by ugermann** [comment]
All it tales is to replace [v] by [verbose].

On Thu, Jan 21, 2016 at 10:49 AM, Ulrich Germann <ulrich.germann@gmail.com>
wrote:

> Davide,
>
> Moses has never accepted [v] as a parameter in the config file. You are in
> charge of the wrapper, so you are the one who has to fix whatever writes
> the moses.ini file.
>
> - Uli
>
> On Wed, Jan 20, 2016 at 12:15 PM, Davide Caroselli <
> notifications@github.com> wrote:
>
>> who can work on this issue? @ugermann <https://github.com/ugermann>
>> @nicolabertoldi <https://github.com/nicolabertoldi> @cattoni
>> <https://github.com/cattoni> please set the assignee of this issue.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ModernMT/MMT/issues/58#issuecomment-173186271>.
>>
>
>
>
> --
> Ulrich Germann
> Senior Researcher
> School of Informatics
> University of Edinburgh
>



-- 
Ulrich Germann
Senior Researcher
School of Informatics
University of Edinburgh

**Comment by nicolabertoldi** [comment]
Hi Uli

just to know,
why "Moses has never accepted [v] as a parameter in the config file."

Is this true only for "v", or for all short-name parameters?


Nicola

**Comment by ugermann** [comment]
All short option names, as far a s I know. Short options are for
convenience for command line use. In a config file, explicitness is more
important than saving a few key strokes.

On Thu, Jan 21, 2016 at 11:00 AM, Nicola Bertoldi <notifications@github.com>
wrote:

> Hi Uli
>
> just to know,
> why "Moses has never accepted [v] as a parameter in the config file."
>
> Is this true only for "v", or for all short-name parameters?
>
>
> Nicola
>
> On Jan 21, 2016, at 11:49 AM, Ulrich Germann wrote:
>
> > Davide,
> >
> > Moses has never accepted [v] as a parameter in the config file. You are
> in
> > charge of the wrapper, so you are the one who has to fix whatever writes
> > the moses.ini file.
> >
> > - Uli
> >
> > On Wed, Jan 20, 2016 at 12:15 PM, Davide Caroselli <
> notifications@github.com
> > > wrote:
> >
> > > who can work on this issue? @ugermann <https://github.com/ugermann>
> > > @nicolabertoldi <https://github.com/nicolabertoldi> @cattoni
> > > <https://github.com/cattoni> please set the assignee of this issue.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/ModernMT/MMT/issues/58#issuecomment-173186271>.
> > >
> >
> >
> >
> > --
> > Ulrich Germann
> > Senior Researcher
> > School of Informatics
> > University of Edinburgh
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ModernMT/MMT/issues/58#issuecomment-173538085>.
>



-- 
Ulrich Germann
Senior Researcher
School of Informatics
University of Edinburgh
