### ISSUE TITLE
API Readability Enhancement

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#60]
```
curl "http://localhost:8045/translate?q=I+like+it&context=computer&nbest=10" | python -mjson.tool
```

"translation" should be the first entry not the last one.

**Comment by davidecaroselli** [comment]
This is impossible. The "translation" is a key of a JSON Object. Keys in json object simply has no order. The order in which they are printed depends on specific implementation of JSON libraries used.

Never ever a client should make any assumption on the order of the keys in a JSON object.
