### ISSUE TITLE
Simpler MMT Cluster without .pem

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#61]
1) Connecting using a .pem ile
Now
```
ERROR SSH connection problem: The authenticity of host '52.90.254.35' can't be established. Please try to connect to the host with 'ssh' command before retrying.
```
Should be
```
ERROR SSH connection warning: host '52.90.254.35' must be added to the ssh known hosts. You can easily do it by by connecting to the host using 'ssh' and retry.
```

2) Connection without .pem

The default way to use the cluster should be with rsync as a server so the no .pem file is necessary and not warnings will be shown.

**Comment by davidecaroselli** [comment]
Feature supported starting from commit https://github.com/ModernMT/MMT/commit/e92254ababe76ade4af27e4ec5ceb34ba60be9e3

To join a cluster now you just have to specify its LAN IP, example:
```bash
./mmt start --join 172.31.42.212
```
