### ISSUE TITLE
INSTALL.md: installing Java 8 will not make it the default

### ISSUE THREAD

**Issue by ugermann** [ModernMT/MMT#63]
`apt-get install openjdk-8-jdk` will not make Java 8 the default. MMT will compile but then crash when one tries to actually use it, complaining about the wrong Java version. If MMT compiles with Java 7, why do we need Java 8? Are there bugs in Java 7?

Actions required: 
- update instructions
- check Java version prior to compilation to provide early feedback

**Comment by marcotrombetti** [comment]
@ugermann which OS are you using?

**Comment by ugermann** [comment]
Ubuntu 14.04. If openjdk-7-jdk is already installed, this will be kept as
the the default.

On Sat, Jan 23, 2016 at 11:00 PM, Marco Trombetti <notifications@github.com>
wrote:

> @ugermann <https://github.com/ugermann> which OS are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ModernMT/MMT/issues/63#issuecomment-174228970>.
>



-- 
Ulrich Germann
Senior Researcher
School of Informatics
University of Edinburgh

**Comment by marcotrombetti** [comment]
@davidecaroselli this is relevant for  0.11.1
I have increased priority and added to milestone.
