### ISSUE TITLE
MMT should be installable in user space

### ISSUE THREAD

**Issue by ugermann** [ModernMT/MMT#64]
Not all developers have root privileges on their local system. Like Moses, MMT should be installable entirely in user space, provided that standard development tools for the platform in question are installed. 
Why do we need software versions so new that they are not available through the standard package managers (e.g., cmake 3.0 instead of cmake 2.8; Java 8 instead of Java 7)? Why do they have to be installed in /usr/local? The current set-up leads everyone to develop in their own home-cooked setup and branches, because a common set-up is simply infeasible.

**Comment by marcotrombetti** [comment]
Added to release 0.13

Today the focus is Ubuntu 14.04
In releasee 0.12 we should have all components more solid.
In 0.13, if the solution is solid, we make it multi platform and with less dependancies.

**Comment by cidermole** [comment]
```
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh
# walk through setup, choose to add to .bashrc (adds `conda`, `activate`, `deactivate` to your PATH)

conda create --name mmt -c https://conda.anaconda.org/cidermole cmake gcc boost zlib gperftools python=2.7 requests jdk8 apache-maven

# every time you use MMT in a shell
source activate mmt

cd MMT
extras/conda-setup.sh
vendor/compile.sh
cd src
mvn clean install

# once you are finished
source deactivate
```

Works with Ubuntu 12.04 and should work with anything at least as "recent".

**Comment by cidermole** [comment]
Oh, we should eventually have a discussion about install location and RPATH of libs, @davidecaroselli
