### ISSUE TITLE
Docker - Can't get translations after building and starting

### ISSUE THREAD

**Issue by ugermann** [ModernMT/MMT#65]
This pertains to commit 4af1dbab4595e65ba0d0ef6dbb9803645792360e

On a brand-new MMT instance:

````
cd ModernMT
wget https://github.com/ModernMT/MMT/files/101164/training.tar.gz -qO- | tar xzf -
./mmt create en it ./1dtrain
./mmt start
curl "http://localhost:8045/translate?q=world&context=computer" | python -mjson.tool
````

gives

````
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 8045: Connection refused
No JSON object could be decoded
````

````
./mmt status
````

tells us
````
Master instance: stopped
Slave instance: stopped
stopped
````

but 
````
./mmt start
````

then leads to 
````
ERROR Illegal State: port 5016 is already in use, please specify another port pair with option --cluster-ports
`````

# To replicate
1. Install docker if necessary (https://docs.docker.com/engine/installation/ubuntulinux/)
2. `git clone https://github.com/ModernMT/docker.git`
3. `docker build -t mmt docker/Development`
4. `docker run --name mmt -it mmt bash`
5. run commands as listed in the bug report above
6. `exit` (to leave docker container)

# To revisit
7. `docker start mmt` 
8. `docker attach mmt` (hit enter twice to get into the shell)

# To clean up afterwards
9. `docker rm mmt #` (destroys the docker container just created)
10. `docker rmi mmt #` (remove the image; you may want to keep it for future use, though!)

**Comment by davidecaroselli** [comment]
Do this problem appears only with docker? Because this release has not been tested in that condition and the result is currently unpredictable.

Another thing, looking at your commands:
```
./mmt create en it
```

Quite strange that this command executes without problems: path to training corpora is missing, it should be something like:
```
./mmt create en it /path/to/corpora
```

could you please report the output of the command:

```
./mmt create en it 
```

thank you!

**Comment by ugermann** [comment]
The missing path was an omission in the bug report. The bug report has been updated accordingly.
I'm quite certain that this has nothing to do with Docker. On the contrary, Docker ensures that I'm testing everything from scratch. I have no other way of testing things as we are still running Ubuntu 12.04 on our machines and this release insists on Ubuntu 14.04.

**Comment by marcotrombetti** [comment]
A few hypothesis:

1) It may be connected to #44 
Try killing manually the previous processes that may be still running. 

2) Port 5016 may be used by a Docker service.
try using another port using  --cluster-ports

*Last and more probable:*
We never tested MMT on Docker. MMT 0.11 is designed for a standard Ubuntu 14.04.
At been tested on AWS and on VirtualBox installing Ubuntu 14.04.
In release 0.13 we should address all multi platform issues and we could design a special and easy to deploy case for Docker. 

@ugermann, ideally what would be the dream installation for a docker user?

**Comment by davidecaroselli** [comment]
As discussed with @ugermann this was an issue with start/stop commands and was not related to docker. The bug was in fact the same as Issue #44 that has been solved.
