### ISSUE TITLE
INSTALL.md out of sync with MMT requirements

### ISSUE THREAD

**Issue by ugermann** [ModernMT/MMT#67]
MMT requires Moses branch mmt-dev_issue49 due to changes in IRSTLM   (added parameter weight_normalization=yes in IRSTLM line of moses.ini), but INSTALL.md still tells people to use mmt-dev.

**Comment by marcotrombetti** [comment]
@ugermann feel free to to edit the file. You can do it directly in the GitHub UI.

If you are not a contributor yet, @davidecaroselli will add you

**Comment by davidecaroselli** [comment]
@ugermann you're right, if the fix of issue 49 is completed, please merge it to branch "mmt-dev". The official branch of mmt is "mmt-dev", so the INSTALL.md should not be changed. Thanks for the tip!

**Comment by davidecaroselli** [comment]
@ugermann since there was no conflicts, I've done the merge and pushed to mosesdecoder repo. Now everything should work as expected.
