### ISSUE TITLE
add weights in the engine.ini after the training

### ISSUE THREAD

**Issue by nicolabertoldi** [ModernMT/MMT#70]
I would suggest to add feature weights in the engine.ini immediately after the creation of the engine.

These feature weights could be "flat", or already "optimised" somewhere else.

**Comment by marcotrombetti** [comment]
From the description I don't understand to who I should assign the task.

@nicolabertoldi can you assign it to the right person?

**Comment by nicolabertoldi** [comment]
Davide is the right person
I assign the issue to him
