### ISSUE TITLE
Moses does not use tcmalloc

### ISSUE THREAD

**Issue by nicolabertoldi** [ModernMT/MMT#71]
It seems that using the current installation instruction (on Ubuntu 14.04)
the current version of moses (branch: mmt-dev) does not compile with  tcmalloc library

$> bjam .....
XMLRPC-C: USING VERSION 1.39.7 FROM /usr/local
Tip: install tcmalloc for faster threading.  See BUILD-INSTRUCTIONS.txt for more information.

I was able to "fix" the problem by installing the package "libgoogle-perftools-dev", instead of "libtcmalloc-minimal4". Actually, "libgoogle-perftools-dev", automatically install "libtcmalloc-minimal4".

The same information is reported in the Mses documentation
http://www.statmt.org/moses/?n=Development.GetStarted

Probably this is a recent change in Moses (and in the recently merged mmt-dev).

I would suggest to update the instructions accordingly

Nicola

**Comment by davidecaroselli** [comment]
Done, thank you Nicola!

**Comment by ugermann** [comment]
If that was the version used for the speed comparison, that could account
for some of the speed difference that Nicola observed.

- Uli

On Wed, Feb 17, 2016 at 9:25 AM, Davide Caroselli <notifications@github.com>
wrote:

> Done, thank you Nicola!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ModernMT/MMT/issues/71#issuecomment-185092309>.
>



-- 
Ulrich Germann
Senior Researcher
School of Informatics
University of Edinburgh
