### ISSUE TITLE
BLEU Score Calculation Bug?

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#74]
With 0.12

The numbers I see do not make a lot sense.
If it possible that there is a BLEU score calculation error? detokenization?

```
./mmt create en it examples/data/train
./mmt start
./mmt evaluate

Testing on 30 sentences...

Matecat Post-Editing Effort:
  Google Translate    : 53.10 (Winner)
  MMT                 : 52.23
  Bing Translator     : Coming in next MMT release

BLEU:
  MMT                 : 45.05 (Winner)
  Google Translate    : 34.81
  Bing Translator     : Coming in next MMT release

Translation Speed:
  Google Translate    : 1104 words/s
  MMT                 : 92 words/s
  Bing Translator     : Coming in next MMT release
```

**Comment by marcotrombetti** [comment]
Here a few possible bugs identified:

To reproduce
```
echo "";cat runtime/default/master/tmp/evaluate/references/commocrawl.en ;cat runtime/default/master/tmp/evaluate/references/commocrawl.fr ;cat runtime/default/master/tmp/evaluate/translations/Google_Translate/commocrawl.fr ;cat runtime/default/master/tmp/evaluate/translations/MMT/commocrawl.fr ;echo ""
```

*1 - Encoded Translations*
Google json output has not been decoded. see for example &#39;
```
SOURCE: query has a power feature to list packages belonging to our system , portage or even an overlay .
REFERENCE: equery dispose d' un outil puissant permettant de lister les paquets appartenant à notre système , à Portage ou même à un « overlay » .
Google: equery dispose d&#39;une fonction de puissance à la liste des paquets appartenant à notre système, portage ou même une superposition.
MMT: equery a une fonctionnalité liste paquets appartenant à notre système, portage ou même un overlay.
```

*2 - Non Uniform Tokenization across engines.*

Is it normal they MMT and GT are detokenized and input is not? Even if the calculation is correct we should log what we actually compare.

```
SOURCE: They have a small shop with decorative objects and a wide selection of special details .
REFERENCE: Le restaurant à son charme , beaucoup de détail et très chaleureux .
Google: Ils ont une petite boutique avec des objets décoratifs et une large sélection de détails spéciaux.
MMT: Ils ont un petit magasin avec objets décoratifs et une large sélection de détails.
```

*3 - Edit Distance for translation scoring sucks.*
For a small engine where Google Translate is clearly providing better translation the BLEU keep saying MMT is better.

I think we should automatically create A/B testing that a human can quickly evaluate.
Something like providing the user with a link to the MMT website where he can do the A/B testing our outsource.

I suggest something like 
```
-/mmt human-AB-test

A/B Human Evaluation available here:
http://modernmt.eu/ab/FREDWFG
```

After a few test I realized that it only takes 20 sentences to converge to who is better.
Examples of A/B testing interfaces available on FBK and Translated websites.

**Comment by marcotrombetti** [comment]
1 and Human A/B have been addressed.

@davidecaroselli can you comment on point 2?

**Comment by davidecaroselli** [comment]
Regarding point 2, I checked and I confirm that the files are correctly generated and used. In the example in fact:

* All files **<name>.tok.it** contain the right **tokenized translation**, or reference
* All files **<name>.it** contain the right **untokenized translation**

BLEU score is calculated on <name>.tok.it files, while Matecat post editing score on <name>.it files.
I don't know how you created that output, but I suspect you used the ".tok.it" version for source and reference and ".it" version for translations.

I'm closing the bug report for now because on the last version all 3 points are solved. If you experience some problem, please, reopen it. Thank you.
