### ISSUE TITLE
./mmt start - Synchronizing models

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#77]
Why is I start mmt on a **master** it says **Synchronizing models**?

```
ubuntu@ip-172-30-0-162:~/mmt$ ./mmt start

Starting MMT engine 'default'... OK
Synchronizing models... OK
You can try the API with:
	curl "http://localhost:8045/translate?q=world&context=computer" | python -mjson.tool


```

**Comment by davidecaroselli** [comment]
Every time you launch MMT, a master process and a slave process is launched.
You're seeing the slave processes saying that everything is up-to-date with its models.
