### ISSUE TITLE
Evaluate - Decrease GT Speed

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#80]
GT has a per user limit of 10.000 bytes per 100 seconds.
Circa 1 sentence per second which is too slow for our purpose

So I always get this error:
```
Translation Speed:
  MMT                 : 125 words/s
  Bing Translator     : Coming in next MMT release
  Google Translate    : Google Translate query failed with code 403: User Rate Limit Exceeded
```

This functionality is designed by Google to prevent a single end-user to abuse.
It does not make sense in a server-to-server configuration.

In order to solve I suggest that we simulate what we do in MyMemory and Matecat (I think we pass a end user_ip parameter and/or a s2s parameter)

**Comment by davidecaroselli** [comment]
I've found in the  Google FAQs https://cloud.google.com/translate/v2/faq#technical that the problem seems to be related to a limit set in the API Key configuration.

I'll assign @luca-mastrostefano to this task for now.

**Comment by davidecaroselli** [comment]
I've reduced the concurrency of GT requests, now we request at most 2 queries at the same time. From my tests this seems to resolve the issue, if not, please, reopen the issue. Thanks.
