### ISSUE TITLE
Evaluate - Sometime it never ends

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#83]
To reproduce:

- Train the example engine on a **new** (just rebooted) machine with high number of cores (eg. c4.8xlarge)
- run ./mmt start
- run ./mmt evaluate

In most cases it will never end.

If I run ./mmt evaluate multiple time it may start working.

**Comment by davidecaroselli** [comment]
As a preliminary results, we found that changing this line https://github.com/ModernMT/MMT/blob/master/scripts/evaluation.py#L71 using only one thread:

```
pool = multithread.Pool(1)
```

has solved the problem. Also skipping Moses call for translation seems to resolve the issue. We need to indagate more accurately so discover from which side it comes the bug (core part or moses decoder).

**Comment by marcotrombetti** [comment]
Bug solved by @davidecaroselli . was a tokenizer non-managed exception.
