### ISSUE TITLE
New Logs Desgin - Discussion

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#87]
We all agree that the initial logging is not ideal and we want to change it soon in order to allow people to run their test and contribute more to the project.

Here my suggestion:

```
./mmt create en it data -e test 
Will log only errors

./mmt create en it data -e test -v 
Will log errors and warnings

./mmt create en it data -e test -vv
Will log everything inluding translation requests to the api

This should apply also to evaluate, tune etc
```

**structure**
logs (not runtime)
  -> engine_name
        -> api
        -> training
        -> tuning
        -> evaluate

For the user dividing between master and slave does not make to much sense.

**Comment by marcotrombetti** [comment]
After discussions this will go to a future release. @davidecaroselli will reserve some time to add basic logging next week.

**Comment by davidecaroselli** [comment]
This task has been scheduled for this sprint (02/29 to 03/04). Basic logging will be available at the end of this week.
