### ISSUE TITLE
Evaluate - tmp folder deleted by the tuning process

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#91]
I was running a tuning and an evaluate on the same engine.

When tuning completed it deleted the evaluate tmp folder while it should have deleted the tune folder only.

```
runtime/b1/master/tmp/evaluate/
```

**Comment by davidecaroselli** [comment]
Starting from commit https://github.com/ModernMT/MMT/commit/677aea83bd1119c4113c27d55f66819bdcac2d2b you can safely collect the translations and the references of an 'evaluate' command using:

```
./mmt evaluate --human-eval path/to/hefiles
```

Please use those files to run scripts or evaluations. Temporary files can change unexpectedly and, as temporary files, they can be deleted as needed.
