### ISSUE TITLE
Evaluate - Tokenization Standardization

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#92]
The log of the evaluation has different tokenization for the different resources.
Not sure if this affect the score calculation but is better to fix it.

```
ORIGINAL: Note : For setting the clock and changing the display mode , refer to the above questions :
HUMAN   : Nota : per l' impostazione dell' orologio e la modifica della modalità di visualizzazione , fare riferimento alle domande riportate sopra
MMT     : Nota: Per impostare l'orologio e modificare la modalità di visualizzazione, fare riferimento a quanto sopra domande:
GT      : Nota: per impostare l'orologio e cambiare la modalità di visualizzazione, fare riferimento alle domande di cui sopra:
```

**Comment by marcotrombetti** [comment]
Also check apps management for Google. Maybe spaces are not managed.
```
ORIGINAL: Is it possible to use portable HDD ?
HUMAN   : È possibile utilizzare un HDD portatile ?
MMT     : È possibile utilizzare HDD portatile?
GT      : E 'possibile usare HDD portatile?
```

**Comment by nicolabertoldi** [comment]
The tokenization of GT 
"E 'possibile...."
seems   that performed for English
Sure that the api was qeried for the correct languages?

**Comment by marcotrombetti** [comment]
@nicolabertoldi I think is a bug we introduced recently trying to manage '&apos'.

**Comment by davidecaroselli** [comment]
Actually, this is the exact output of Google Translate:
<img width="1243" alt="schermata 2016-02-29 alle 15 39 51" src="https://cloud.githubusercontent.com/assets/1674891/13397554/c8fcdf94-defa-11e5-9f98-fb0ef349468d.png">

So the output is consistent with the real translation GT has provided.

**Comment by davidecaroselli** [comment]
Regarding the first post, that is a different problem, it seems that the input corpora (or maybe only the sentence) was already tokenized.

In addition, please be sure to look at the right file "reference.it" and not "reference.tok.it".
