### ISSUE TITLE
tokenizer's bad behaviour with "embedded" tags

### ISSUE THREAD

**Issue by nicolabertoldi** [ModernMT/MMT#94]
Tokenizer has problem with embedded tags like the following (see below)
which contains well-formed tags like <PARAM NAME="_ExtentY" VALUE="714">)
inside 

Note that the corpus   TagBenchmark-v0.2, there are a few of them

The internal tags are well-managed, while the external are not.

Here an example:
The tokenized and tag-stripped output is  
Monitor TRS < ! --METADATA TYPE = " DesignerControl " startspan -- >

while the input was
Monitor TRS

**Comment by cattoni** [comment]
Actually the reported example is not a tag: it is a XML comment that has the syntax  
OPEN CHAR* CLOSE where
OPEN ::= ""

I think comments should be managed in the same way of self-closing tags.

**Comment by davidecaroselli** [comment]
After a discussion with @nicolabertoldi we decided that the best solution is to consider "" its closing tag. All inside should be parsed and translated as normal: other tags are  considered tags, while words are considered text to translate.

Here's an example on how it should work:
* **input**: `<!-- Hello <b>world</b> -->`
* **output**: `<!-- Ciao <b>mondo</b> -->`

We found a bunch of these examples in the benchmark-v1.0. @mfederico @marcotrombetti the fix should be really simple to apply, and it will take about 1-2 hours of my time and Nicola's. Do you agree in adding this tiny task to Sprint 2?

**Comment by marcotrombetti** [comment]
good for me

**Comment by davidecaroselli** [comment]
Added this feature with commit https://github.com/ModernMT/MMT/commit/e5fc8cf15f371f168a531bfb1f39a7f42286c2f5
