### ISSUE TITLE
Tokenizer tokenizes the underscore

### ISSUE THREAD

**Issue by nicolabertoldi** [ModernMT/MMT#95]
I do not know if this is the chosen policy,
so I labelled both as bug and enhancement

Input:     the folder     WKS_Migration
Output:     the folder     WKS  _   Migration

**Comment by davidecaroselli** [comment]
I'm going to change this behavior next week in order to keep the tokenization stable for this week tests

**Comment by davidecaroselli** [comment]
Solved in the latest MMT release (v0.12)
