### ISSUE TITLE
Invalid scripts in extras folder

### ISSUE THREAD

**Issue by davidecaroselli** [ModernMT/MMT#97]
I've found some invalid scripts in folder called "extras". These scripts cannot be added to master branch, and cannot be accepted in MMT because they cannot be run anywhere except a very specific setup: the scripts contains hard-coded paths and files, so nobody can actually run them without getting an error.

If this scripts are useful for the entire MMT community/project, please consider rewriting them in a more flexible way. Notice also that **you should never commit new code directly to master branch, instead create a new branch from develop one**.

I'm removing the scripts for now, a copy of them is attached to this issue:
[amazon-aws.tar.gz](https://github.com/ModernMT/MMT/files/150787/amazon-aws.tar.gz)

Thanks for your collaboration.

**Comment by marcotrombetti** [comment]
OK. I added a Usage and some parameters and committed again in the develop branch.
