### ISSUE TITLE
Can't create an engine specifying the steps

### ISSUE THREAD

**Issue by luca-mastrostefano** [ModernMT/MMT#98]
It seems that it is not possible to specify a step during the creation of an engine:

`./mmt create -s tokenize en it examples/data/train/`

Output:

> usage: mmt create [-h] [-e ENGINE] [-d] [-s STEPS [STEPS ...]]
                  [--cleaner.max MAX] [--cleaner.ratio RATIO]
                  [--cleaner.min MIN] [--context.index_lang INDEX_LANG]
                  [--suffixarrays.sample SAMPLE] [--lm.order ORDER]
                  [--moses.cube_pruning_pop_limit CUBE_PRUNING_POP_LIMIT]
                  [--moses.stack_size STACK_SIZE]
                  [--moses.distortion_limit DISTORTION_LIMIT]
                  [--engine.lm_type LM_TYPE]
                  [--engine.aligner_type ALIGNER_TYPE]
                  SOURCE_LANGUAGE TARGET_LANGUAGE CORPORA
mmt create: error: argument -s/--steps: invalid choice: 'en' (choose from 'tokenize', 'clean', 'context_analyzer', 'lm', 'tm')

The same error occurs also for the other steps.

**Comment by luca-mastrostefano** [comment]
I'm debugging. If you have any advice please tell me.

**Comment by davidecaroselli** [comment]
Ok, I think I find out where is the problem, can you please try to specify "-s tokenize" at the end of the command arguments?
