### ISSUE TITLE
De-tokenizer

### ISSUE THREAD

**Issue by mfederico** [ModernMT/MMT#99]
By running mmt on the sample benchmark I noticed several issues on the de-tokeniser:
- & gt;    spurious space introduced between "&" and "gt;"
- 445/ 00  spurious space introduced after "/"

**Comment by marcotrombetti** [comment]
@davidecaroselli is this still actual?

**Comment by davidecaroselli** [comment]
The first case ("& gt;") has been solved by the new preprocessor, while the second is still valid.

**Comment by davidecaroselli** [comment]
Solved in the latest MMT release (v0.12)
